# -*- coding: utf-8 -*- #
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the config-ssh subcommand."""

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

import io
import os
import re
import textwrap

from googlecloudsdk.api_lib.util import apis
from googlecloudsdk.command_lib.util.ssh import ssh
from tests.lib import test_case
from tests.lib.surface.compute import test_base

import mock
import six


messages = apis.GetMessagesModule('compute', 'v1')

INSTANCES = [
    messages.Instance(
        id=11111,
        name='instance-1',
        networkInterfaces=[
            messages.NetworkInterface(
                accessConfigs=[
                    messages.AccessConfig(natIP='23.251.133.75'),
                ],
            ),
        ],
        status=messages.Instance.StatusValueValuesEnum.RUNNING,
        selfLink=('https://www.googleapis.com/compute/v1/projects/my-project/'
                  'zones/zone-1/instances/instance-1'),
        zone=('https://www.googleapis.com/compute/v1/projects/my-project/'
              'zones/zone-1')),

    messages.Instance(
        id=22222,
        name='instance-2',
        networkInterfaces=[
            messages.NetworkInterface(
                accessConfigs=[
                    messages.AccessConfig(natIP='23.251.133.74'),
                ],
            ),
        ],
        status=messages.Instance.StatusValueValuesEnum.RUNNING,
        selfLink=('https://www.googleapis.com/compute/v1/projects/my-project/'
                  'zones/zone-1/instances/instance-2'),
        zone=('https://www.googleapis.com/compute/v1/projects/my-project/'
              'zones/zone-1')),

    messages.Instance(
        id=33333,
        name='instance-3',
        networkInterfaces=[
            messages.NetworkInterface(),
        ],
        status=messages.Instance.StatusValueValuesEnum.RUNNING,
        selfLink=('https://www.googleapis.com/compute/v1/projects/my-project/'
                  'zones/zone-1/instances/instance-3'),
        zone=('https://www.googleapis.com/compute/v1/projects/my-project/'
              'zones/zone-1')),
]


class ConfigSSHTest(test_base.BaseSSHTest, test_case.WithInput):

  def SetUp(self):
    self.config_path = os.path.join(self.ssh_dir, 'config')
    self.StartObjectPatch(ssh, 'PER_USER_SSH_CONFIG_FILE', self.config_path)

    lister_patcher = mock.patch(
        'googlecloudsdk.api_lib.compute.lister.GetZonalResources',
        autospec=True)
    self.addCleanup(lister_patcher.stop)
    self.mock_get_zonal_resources = lister_patcher.start()
    self.mock_get_zonal_resources.return_value = INSTANCES

  def ReadConfigFile(self):
    with open(self.config_path) as f:
      return f.read()

  def testWithNoInstancesAndNoConfigFile(self):
    self.mock_get_zonal_resources.return_value = []

    self.Run("""
        compute config-ssh
        """)
    self.AssertErrContains(
        'No host aliases were added to your SSH configs because you do not '
        'have any instances. Try running this command again after creating '
        'some instances.')

    self.assertFalse(os.path.exists(self.config_path))
    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )
    # Require SSH keys
    self.ensure_keys.assert_called_once_with(
        self.keys, None, allow_passphrase=True)

  def testWithNoInstancesAndExistingConfigFileWithComputeSection(self):
    self.mock_get_zonal_resources.return_value = []
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny

          Host my-repo.my-server.example.com

          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10

          # Google Compute Engine Section
          #
          # The following has been auto-generated by "gcloud compute config-ssh"
          # to make accessing your Google Compute Engine virtual machines easier.
          #
          # To remove this blob, run:
          #
          #   gcloud compute config-ssh --remove
          #
          # You can also manually remove this blob by deleting everything from
          # here until the comment that contains the string "End of Google Compute
          # Engine Section".
          #
          # You should not hand-edit this section, unless you are deleting it.
          #
          Host instance-1.zone-1.my-project
              HostName 23.251.133.75

          Host instance-2.zone-1.my-project
              HostName 23.251.133.74

          # End of Google Compute Engine Section
          """))

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        Host my-server
            HostName my-server.example.com
            Port 22000
            User bunny

        Host my-repo.my-server.example.com

        Host *
            ControlMaster auto
            ControlPath /tmp/ssh-%r@%h:%p
            ServerAliveInterval 10

        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74

        # End of Google Compute Engine Section
        """))
    self.AssertErrContains(
        'No host aliases were added to your SSH configs because you do not '
        'have any instances. Try running this command again after creating '
        'some instances.')

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testWithNoInstancesAndExistingConfigFileWithoutComputeSection(self):
    self.mock_get_zonal_resources.return_value = []
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny

          Host my-repo.my-server.example.com

          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10
          """))

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        Host my-server
            HostName my-server.example.com
            Port 22000
            User bunny

        Host my-repo.my-server.example.com

        Host *
            ControlMaster auto
            ControlPath /tmp/ssh-%r@%h:%p
            ServerAliveInterval 10
        """))
    self.AssertErrContains(
        'No host aliases were added to your SSH configs because you do not '
        'have any instances. Try running this command again after creating '
        'some instances.')
    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testExampleUsage(self):
    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(
        self.GetOutput(),
        textwrap.dedent("""\
            You should now be able to use ssh/scp with your instances.
            For example, try running:

              $ ssh instance-1.zone-1.my-project

            """))

  def _DoTestNewConfigFile(self):
    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testWithNewConfigFile(self):
    self._DoTestNewConfigFile()

  # Windows creates files with 0666 regardless of
  # umask/file_utils.OpenFileForWritingPrivate().
  @test_case.Filters.DoNotRunOnWindows
  def testPermsWithNewConfigFile(self):
    # We want to ensure that the new config file is created with the appropriate
    # permissions, so we change our umask to something that would result in bad
    # permissions.
    old_umask = os.umask(0o11)
    self.addCleanup(os.umask, old_umask)
    self._DoTestNewConfigFile()
    self.assertTrue(os.stat(self.config_path).st_mode & 0o777 == 0o600)

  def _DoTestExistingFile(self, perms=None):
    """Run a test with an existing key file with the given permissions."""
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          # This is my configuration file!
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny

          Host my-repo.my-server.example.com

          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10
          """))
    if perms is not None:
      os.chmod(self.config_path, perms)

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # This is my configuration file!
        Host my-server
            HostName my-server.example.com
            Port 22000
            User bunny

        Host my-repo.my-server.example.com

        Host *
            ControlMaster auto
            ControlPath /tmp/ssh-%r@%h:%p
            ServerAliveInterval 10

        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testWithExistingConfigFile(self):
    self._DoTestExistingFile(0o600)

  @test_case.Filters.RunOnlyOnWindows
  def testWithExistingConfigFileNoPermissionChanges(self):
    """Without any permission changes."""
    self._DoTestExistingFile()

  # Windows doesn't support file permissions in the same model
  @test_case.Filters.DoNotRunOnWindows
  def testWithExistingConfigFile_OkayPerms(self):
    self._DoTestExistingFile(0o600)
    self.AssertErrNotContains('Invalid permissions')
    self.AssertErrNotContains('Please change to match ssh requirements')

  @test_case.Filters.DoNotRunOnWindows
  def testWithExistingConfigFile_BadUserPerms(self):
    self._DoTestExistingFile(0o700)
    self.AssertErrContains('Invalid permissions')
    self.AssertErrContains('Please change to match ssh requirements')

  @test_case.Filters.DoNotRunOnWindows
  def testWithExistingConfigFile_BadGroupPerms(self):
    self._DoTestExistingFile(0o620)
    self.AssertErrContains('Invalid permissions')
    self.AssertErrContains('Please change to match ssh requirements')

  @test_case.Filters.DoNotRunOnWindows
  def testWithExistingConfigFile_BadOtherPerms(self):
    self._DoTestExistingFile(0o602)
    self.AssertErrContains('Invalid permissions')
    self.AssertErrContains('Please change to match ssh requirements')

  def testWithExistingConfigFileWithoutNewLineAtTheEnd(self):
    with open(self.config_path, 'w') as f:
      f.write('ServerAliveInterval 10')

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        ServerAliveInterval 10

        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testWithExistingConfigFileAndComputeSectionAtHead(self):
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          # Google Compute Engine Section
          #
          # The following has been auto-generated by "gcloud compute config-ssh"
          # to make accessing your Google Compute Engine virtual machines easier.
          #
          # To remove this blob, run:
          #
          #   gcloud compute config-ssh --remove
          #
          # You can also manually remove this blob by deleting everything from
          # here until the comment that contains the string "End of Google Compute
          # Engine Section".
          #
          # You should not hand-edit this section, unless you are deleting it.
          #
          Host instance-1.zone-2.my-project
              HostName 123.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.11111
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-2.zone-2.my-project
              HostName 123.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.22222
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-3.zone-2.my-project
              HostName 124.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.33333
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-4.zone-2.my-project
              HostName 124.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.44444
              CheckHostIP=no

          # End of Google Compute Engine Section
          # This is my configuration file!
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny

          Host my-repo.my-server.example.com

          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10
          """.format(self.private_key_file, self.known_hosts_file)))

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-2.my-project
            HostName 123.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-2.my-project
            HostName 123.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-3.zone-2.my-project
            HostName 124.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.33333
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-4.zone-2.my-project
            HostName 124.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.44444
            CheckHostIP=no

        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        # This is my configuration file!
        Host my-server
            HostName my-server.example.com
            Port 22000
            User bunny

        Host my-repo.my-server.example.com

        Host *
            ControlMaster auto
            ControlPath /tmp/ssh-%r@%h:%p
            ServerAliveInterval 10
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testWithExistingConfigFileAndComputeSectionAtTail(self):

    # In this test, we also ensure that the command respects existing
    # blank lines.
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          # This is my configuration file!
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny

          Host my-repo.my-server.example.com

          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10




          # Google Compute Engine Section
          #
          # The following has been auto-generated by "gcloud compute config-ssh"
          # to make accessing your Google Compute Engine virtual machines easier.
          #
          # To remove this blob, run:
          #
          #   gcloud compute config-ssh --remove
          #
          # You can also manually remove this blob by deleting everything from
          # here until the comment that contains the string "End of Google Compute
          # Engine Section".
          #
          # You should not hand-edit this section, unless you are deleting it.
          #
          Host instance-4.zone-2.my-project
              HostName 124.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.44444
              IdentitiesOnly=yes
              CheckHostIP=no

          # End of Google Compute Engine Section
          """.format(self.private_key_file, self.known_hosts_file)))

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # This is my configuration file!
        Host my-server
            HostName my-server.example.com
            Port 22000
            User bunny

        Host my-repo.my-server.example.com

        Host *
            ControlMaster auto
            ControlPath /tmp/ssh-%r@%h:%p
            ServerAliveInterval 10




        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-4.zone-2.my-project
            HostName 124.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.44444
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testWithExistingConfigFileAndComputeSectionInMiddle(self):

    # In this test, we also ensure that the command respects existing
    # blank lines.
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\



          # This is my configuration file!
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny
          # Google Compute Engine Section
          #
          # The following has been auto-generated by "gcloud compute config-ssh"
          # to make accessing your Google Compute Engine virtual machines easier.
          #
          # To remove this blob, run:
          #
          #   gcloud compute config-ssh --remove
          #
          # You can also manually remove this blob by deleting everything from
          # here until the comment that contains the string "End of Google Compute
          # Engine Section".
          #
          # You should not hand-edit this section, unless you are deleting it.
          #
          Host instance-4.zone-2.my-project
              HostName 124.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.44444
              IdentitiesOnly=yes
              CheckHostIP=no

          # End of Google Compute Engine Section
          Host my-repo.my-server.example.com

          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10





          """.format(self.private_key_file, self.known_hosts_file)))

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\



        # This is my configuration file!
        Host my-server
            HostName my-server.example.com
            Port 22000
            User bunny
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-4.zone-2.my-project
            HostName 124.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.44444
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        Host my-repo.my-server.example.com

        Host *
            ControlMaster auto
            ControlPath /tmp/ssh-%r@%h:%p
            ServerAliveInterval 10





        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testRemoveWithComputeSectionAndOtherConfigs(self):
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          # Google Compute Engine Section
          #
          # The following has been auto-generated by "gcloud compute config-ssh"
          # to make accessing your Google Compute Engine virtual machines easier.
          #
          # To remove this blob, run:
          #
          #   gcloud compute config-ssh --remove
          #
          # You can also manually remove this blob by deleting everything from
          # here until the comment that contains the string "End of Google Compute
          # Engine Section".
          #
          # You should not hand-edit this section, unless you are deleting it.
          #
          Host instance-1.zone-2.my-project
              HostName 123.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.11111
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-2.zone-2.my-project
              HostName 123.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.22222
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-3.zone-2.my-project
              HostName 124.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.33333
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-4.zone-2.my-project
              HostName 124.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.44444
              IdentitiesOnly=yes
              CheckHostIP=no

          # End of Google Compute Engine Section
          # This is my configuration file!
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny

          Host my-repo.my-server.example.com

          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10
          """.format(self.private_key_file, self.known_hosts_file)))

    self.Run("""
        compute config-ssh --remove
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # This is my configuration file!
        Host my-server
            HostName my-server.example.com
            Port 22000
            User bunny

        Host my-repo.my-server.example.com

        Host *
            ControlMaster auto
            ControlPath /tmp/ssh-%r@%h:%p
            ServerAliveInterval 10
        """))

    self.CheckRequests()
    self.assertFalse(self.stdout.getvalue())
    self.AssertErrNotContains('No host aliases were added')
    self.AssertErrNotContains('The following SSH key will be removed')

  def testRemoveWithComputeSectionOnly(self):
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          # Google Compute Engine Section
          #
          # The following has been auto-generated by "gcloud compute config-ssh"
          # to make accessing your Google Compute Engine virtual machines easier.
          #
          # To remove this blob, run:
          #
          #   gcloud compute config-ssh --remove
          #
          # You can also manually remove this blob by deleting everything from
          # here until the comment that contains the string "End of Google Compute
          # Engine Section".
          #
          # You should not hand-edit this section, unless you are deleting it.
          #
          Host instance-1.zone-2.my-project.cloud.google.com
              HostName 123.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.11111
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-2.zone-2.my-project.cloud.google.com
              HostName 123.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.22222
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-3.zone-2.my-project.cloud.google.com
              HostName 124.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.33333
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-4.zone-2.my-project.cloud.google.com
              HostName 124.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.44444
              IdentitiesOnly=yes
              CheckHostIP=no

          # End of Google Compute Engine Section
          """.format(self.private_key_file, self.known_hosts_file)))

    self.Run("""
        compute config-ssh --remove
        """)

    self.assertFalse(self.ReadConfigFile())
    self.CheckRequests()
    self.assertFalse(self.stdout.getvalue())
    self.AssertErrNotContains('No host aliases were added')
    self.AssertErrNotContains('The following SSH key will be removed')

  def testWithMultipleComputeSections(self):
    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
          # Google Compute Engine Section
          #
          # The following has been auto-generated by "gcloud compute config-ssh"
          # to make accessing your Google Compute Engine virtual machines easier.
          #
          # To remove this blob, run:
          #
          #   gcloud compute config-ssh --remove
          #
          # You can also manually remove this blob by deleting everything from
          # here until the comment that contains the string "End of Google Compute
          # Engine Section".
          #
          # You should not hand-edit this section, unless you are deleting it.
          #
          Host instance-1.zone-2.my-project
              HostName 123.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.11111
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-2.zone-2.my-project
              HostName 123.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.22222
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-3.zone-2.my-project
              HostName 124.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.33333
              IdentitiesOnly=yes
              CheckHostIP=no

          Host instance-4.zone-2.my-project
              HostName 124.251.133.74
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.44444
              IdentitiesOnly=yes
              CheckHostIP=no

          # End of Google Compute Engine Section
          # This is my configuration file!
          Host my-server
              HostName my-server.example.com
              Port 22000
              User bunny

          # Google Compute Engine Section
          # End of Google Compute Engine Section
          # This is my configuration file!

          Host my-repo.my-server.example.com

          # Google Compute Engine Section

          Host instance-3.zone-2.my-project
              HostName 124.251.133.75
              IdentityFile {0}
              UserKnownHostsFile={1}
              HostKeyAlias=compute.33333
              IdentitiesOnly=yes
              CheckHostIP=no

          # End of Google Compute Engine Section
          Host *
              ControlMaster auto
              ControlPath /tmp/ssh-%r@%h:%p
              ServerAliveInterval 10
          """.format(self.private_key_file, self.known_hosts_file)))

    with self.AssertRaisesToolExceptionRegexp(
        r'Found more than one Google Compute Engine section in \[{0}\]. You '
        r'can either delete \[{0}\] and let this command recreate it for you '
        r'or you can manually delete all sections marked with \[# Google '
        r'Compute Engine Section\] and \[# End of Google Compute Engine '
        r'Section\].'
        .format(re.escape(self.config_path))):
      self.Run('compute config-ssh')

  def testWithNoProjectMetadata(self):
    project_resource = messages.Project(
        name='my-project',
    )

    self.make_requests.side_effect = iter([
        [project_resource],
        [],
    ])

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],

        [(self.compute_v1.projects,
          'SetCommonInstanceMetadata',
          messages.ComputeProjectsSetCommonInstanceMetadataRequest(
              metadata=messages.Metadata(
                  items=[
                      messages.Metadata.ItemsValueListEntry(
                          key='ssh-keys',
                          value='me:' + self.public_key_material),
                  ]),

              project='my-project'))],
    )
    self.AssertErrContains('Updating project ssh metadata')

  def testWithNoSSHKeysInProject(self):
    project_resource = messages.Project(
        commonInstanceMetadata=messages.Metadata(
            items=[
                messages.Metadata.ItemsValueListEntry(
                    key='a',
                    value='b'),
            ]),
        name='my-project',
    )

    self.make_requests.side_effect = iter([
        [project_resource],
        [],
    ])

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],

        [(self.compute_v1.projects,
          'SetCommonInstanceMetadata',
          messages.ComputeProjectsSetCommonInstanceMetadataRequest(
              metadata=messages.Metadata(
                  items=[
                      messages.Metadata.ItemsValueListEntry(
                          key='a',
                          value='b'),
                      messages.Metadata.ItemsValueListEntry(
                          key='ssh-keys',
                          value='me:' + self.public_key_material),
                  ]),

              project='my-project'))],
    )
    self.AssertErrContains('Updating project ssh metadata')

  def testWithManySSHKeysInProject(self):
    ssh_keys = textwrap.dedent("""\
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwqx8+h4c6K0ipqLqXt1y4ohpbk6PxDdWzprGxNFrsir/QrOy6iQBAyvlbAb/kM5RaNkjliakfmNEMBH3/tmhBIEmSAsZ0dfhwBof0Hm+bRFI475ik/p7QKSpPXf2nCgG3QF75jfLrk+4R6P+0w3zxbq63LxrB7umUxTA2tGMqgNIW0OQ/w2mfl4DfFTTXQeJ4/Gu6grpl1+Mi7RwtV9RPE5UuveXpcj7htiqj8sv8Zip9kVE7lNQFB0xdy1pcUw93ddo4lbGIJX7PTS0fvXfFdnAZ4huVrdqCOBBMApSx3QdRYUnyz+PrxasQIu7pK8Cl0yACBFUbMhMazqzo2485 me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpBFilw+qXCrkbxzk3jQ+Bx/wLpPozc6Nz1A/LjHWlmXJ94js9PVHPwhg7JbiMlakn5rHEPRNEHF9S2m6lOIV1s0KCZR1FYpQArB312KCbH8TtovPwAOgcwcosEn54Ewko5EOCpQAMYdEs4qMAOR7tGA5Opi/rEx9S5n3DohZ5XIcbtRshgMDllYN6OAdck3WN2tj4JWjUrUXRI3BVxKTxlmH9zRqIta6Ph2M/+/DYnQa+jyAzYXiErqqmylT/OReYXxhSVbM+GLsuW82On+wa8DrL8YomHejwKAkZZgH9LGw6QIwI8GNWyF0SbMx1fYnEedp1DSi0Kt2gfIcah+0Z me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5n+uTbZOqqMapxVy621kJbpEvPiiy40rkU7d43WUQC00HPvXeN68ZzXiXgpRFtdJi9UbmmuTuPWgwkKI+Ifx/khM0BDTb9akJJnAizp26zbYoCQTxxzwvrv0DXTaMUThTdw6RVEKYVm69QoAQXpj0O06BHgb7Vp0si240Ny9xFMDfm0LURcemw0/GkakYbEa3LCpC8qNA+hjFc7LP6F//MbgxLgJPMM9e63SlxvAYfkJMzX/nCVcT55a01ng3VXihtt4+ERHhtJfZaPnAoMqagvi1iBQLPreP8euXjtZyHLiUtdYOJV6tuUFNyTeB1I0H2ll3ikDHJjpYGsSv/ffZ me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+NC6tKzpT0GiYwscFoD8n/MdktvymPO8ncn2pAIAy34yiworwx9hLlOeMDsHaFb5LoT3qgqPoiaH1KWmFILKGtb/s9xqzpGZQFPu62nE4zd6Fa82c0rREtIfvst6EbclWSS4uLSn+Pmb6AQBZm3hubbslUMRZzj0vihyVi1y0rboL2U4X8ROZwQzZKG8iQf6k0A31Nb77DOqxQD4twPs2TCU5Hzc7mGWZGDbrUljWNyLJFBoTRDVa+Llc7aKP3MEzR20VcXB1SbB1BZr93MpQkQ+hpmoMAxikmhR6EpRfDs+pw2lHdBuOljhdJhOIZLudJAEfLwZw/4B9rZo9J6xn me@my-computer
        """)

    project_resource = messages.Project(
        commonInstanceMetadata=messages.Metadata(
            items=[
                messages.Metadata.ItemsValueListEntry(
                    key='a',
                    value='b'),
                messages.Metadata.ItemsValueListEntry(
                    key='ssh-keys',
                    value=ssh_keys),
            ]),
        name='my-project',
    )

    self.make_requests.side_effect = iter([
        [project_resource],
        [],
    ])

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    new_ssh_keys = ssh_keys + 'me:' + self.public_key_material

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],

        [(self.compute_v1.projects,
          'SetCommonInstanceMetadata',
          messages.ComputeProjectsSetCommonInstanceMetadataRequest(
              metadata=messages.Metadata(
                  items=[
                      messages.Metadata.ItemsValueListEntry(
                          key='a',
                          value='b'),
                      messages.Metadata.ItemsValueListEntry(
                          key='ssh-keys',
                          value=new_ssh_keys),
                  ]),

              project='my-project'))],
    )
    self.AssertErrContains('Updating project ssh metadata')

  def testWithSSHKeyInProjectWithManyOtherSSHKeys(self):
    ssh_keys = textwrap.dedent("""\
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwqx8+h4c6K0ipqLqXt1y4ohpbk6PxDdWzprGxNFrsir/QrOy6iQBAyvlbAb/kM5RaNkjliakfmNEMBH3/tmhBIEmSAsZ0dfhwBof0Hm+bRFI475ik/p7QKSpPXf2nCgG3QF75jfLrk+4R6P+0w3zxbq63LxrB7umUxTA2tGMqgNIW0OQ/w2mfl4DfFTTXQeJ4/Gu6grpl1+Mi7RwtV9RPE5UuveXpcj7htiqj8sv8Zip9kVE7lNQFB0xdy1pcUw93ddo4lbGIJX7PTS0fvXfFdnAZ4huVrdqCOBBMApSx3QdRYUnyz+PrxasQIu7pK8Cl0yACBFUbMhMazqzo2485 me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpBFilw+qXCrkbxzk3jQ+Bx/wLpPozc6Nz1A/LjHWlmXJ94js9PVHPwhg7JbiMlakn5rHEPRNEHF9S2m6lOIV1s0KCZR1FYpQArB312KCbH8TtovPwAOgcwcosEn54Ewko5EOCpQAMYdEs4qMAOR7tGA5Opi/rEx9S5n3DohZ5XIcbtRshgMDllYN6OAdck3WN2tj4JWjUrUXRI3BVxKTxlmH9zRqIta6Ph2M/+/DYnQa+jyAzYXiErqqmylT/OReYXxhSVbM+GLsuW82On+wa8DrL8YomHejwKAkZZgH9LGw6QIwI8GNWyF0SbMx1fYnEedp1DSi0Kt2gfIcah+0Z me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5n+uTbZOqqMapxVy621kJbpEvPiiy40rkU7d43WUQC00HPvXeN68ZzXiXgpRFtdJi9UbmmuTuPWgwkKI+Ifx/khM0BDTb9akJJnAizp26zbYoCQTxxzwvrv0DXTaMUThTdw6RVEKYVm69QoAQXpj0O06BHgb7Vp0si240Ny9xFMDfm0LURcemw0/GkakYbEa3LCpC8qNA+hjFc7LP6F//MbgxLgJPMM9e63SlxvAYfkJMzX/nCVcT55a01ng3VXihtt4+ERHhtJfZaPnAoMqagvi1iBQLPreP8euXjtZyHLiUtdYOJV6tuUFNyTeB1I0H2ll3ikDHJjpYGsSv/ffZ me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+NC6tKzpT0GiYwscFoD8n/MdktvymPO8ncn2pAIAy34yiworwx9hLlOeMDsHaFb5LoT3qgqPoiaH1KWmFILKGtb/s9xqzpGZQFPu62nE4zd6Fa82c0rREtIfvst6EbclWSS4uLSn+Pmb6AQBZm3hubbslUMRZzj0vihyVi1y0rboL2U4X8ROZwQzZKG8iQf6k0A31Nb77DOqxQD4twPs2TCU5Hzc7mGWZGDbrUljWNyLJFBoTRDVa+Llc7aKP3MEzR20VcXB1SbB1BZr93MpQkQ+hpmoMAxikmhR6EpRfDs+pw2lHdBuOljhdJhOIZLudJAEfLwZw/4B9rZo9J6xn me@my-computer
        """) + 'me:' + self.public_key_material

    project_resource = messages.Project(
        commonInstanceMetadata=messages.Metadata(
            items=[
                messages.Metadata.ItemsValueListEntry(
                    key='a',
                    value='b'),
                messages.Metadata.ItemsValueListEntry(
                    key='ssh-keys',
                    value=ssh_keys),
            ]),
        name='my-project',
    )

    self.make_requests.side_effect = iter([
        [project_resource],
        [],
    ])

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],
    )

  def testWithManySSHKeysInProjectWithSpacesBetweenThem(self):
    ssh_keys = textwrap.dedent("""\



        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwqx8+h4c6K0ipqLqXt1y4ohpbk6PxDdWzprGxNFrsir/QrOy6iQBAyvlbAb/kM5RaNkjliakfmNEMBH3/tmhBIEmSAsZ0dfhwBof0Hm+bRFI475ik/p7QKSpPXf2nCgG3QF75jfLrk+4R6P+0w3zxbq63LxrB7umUxTA2tGMqgNIW0OQ/w2mfl4DfFTTXQeJ4/Gu6grpl1+Mi7RwtV9RPE5UuveXpcj7htiqj8sv8Zip9kVE7lNQFB0xdy1pcUw93ddo4lbGIJX7PTS0fvXfFdnAZ4huVrdqCOBBMApSx3QdRYUnyz+PrxasQIu7pK8Cl0yACBFUbMhMazqzo2485 me@my-computer



        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpBFilw+qXCrkbxzk3jQ+Bx/wLpPozc6Nz1A/LjHWlmXJ94js9PVHPwhg7JbiMlakn5rHEPRNEHF9S2m6lOIV1s0KCZR1FYpQArB312KCbH8TtovPwAOgcwcosEn54Ewko5EOCpQAMYdEs4qMAOR7tGA5Opi/rEx9S5n3DohZ5XIcbtRshgMDllYN6OAdck3WN2tj4JWjUrUXRI3BVxKTxlmH9zRqIta6Ph2M/+/DYnQa+jyAzYXiErqqmylT/OReYXxhSVbM+GLsuW82On+wa8DrL8YomHejwKAkZZgH9LGw6QIwI8GNWyF0SbMx1fYnEedp1DSi0Kt2gfIcah+0Z me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5n+uTbZOqqMapxVy621kJbpEvPiiy40rkU7d43WUQC00HPvXeN68ZzXiXgpRFtdJi9UbmmuTuPWgwkKI+Ifx/khM0BDTb9akJJnAizp26zbYoCQTxxzwvrv0DXTaMUThTdw6RVEKYVm69QoAQXpj0O06BHgb7Vp0si240Ny9xFMDfm0LURcemw0/GkakYbEa3LCpC8qNA+hjFc7LP6F//MbgxLgJPMM9e63SlxvAYfkJMzX/nCVcT55a01ng3VXihtt4+ERHhtJfZaPnAoMqagvi1iBQLPreP8euXjtZyHLiUtdYOJV6tuUFNyTeB1I0H2ll3ikDHJjpYGsSv/ffZ me@my-computer





        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+NC6tKzpT0GiYwscFoD8n/MdktvymPO8ncn2pAIAy34yiworwx9hLlOeMDsHaFb5LoT3qgqPoiaH1KWmFILKGtb/s9xqzpGZQFPu62nE4zd6Fa82c0rREtIfvst6EbclWSS4uLSn+Pmb6AQBZm3hubbslUMRZzj0vihyVi1y0rboL2U4X8ROZwQzZKG8iQf6k0A31Nb77DOqxQD4twPs2TCU5Hzc7mGWZGDbrUljWNyLJFBoTRDVa+Llc7aKP3MEzR20VcXB1SbB1BZr93MpQkQ+hpmoMAxikmhR6EpRfDs+pw2lHdBuOljhdJhOIZLudJAEfLwZw/4B9rZo9J6xn me@my-computer

        """)

    project_resource = messages.Project(
        commonInstanceMetadata=messages.Metadata(
            items=[
                messages.Metadata.ItemsValueListEntry(
                    key='a',
                    value='b'),
                messages.Metadata.ItemsValueListEntry(
                    key='ssh-keys',
                    value=ssh_keys),
            ]),
        name='my-project',
    )

    self.make_requests.side_effect = iter([
        [project_resource],
        [],
    ])

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    ssh_keys = textwrap.dedent("""\
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwqx8+h4c6K0ipqLqXt1y4ohpbk6PxDdWzprGxNFrsir/QrOy6iQBAyvlbAb/kM5RaNkjliakfmNEMBH3/tmhBIEmSAsZ0dfhwBof0Hm+bRFI475ik/p7QKSpPXf2nCgG3QF75jfLrk+4R6P+0w3zxbq63LxrB7umUxTA2tGMqgNIW0OQ/w2mfl4DfFTTXQeJ4/Gu6grpl1+Mi7RwtV9RPE5UuveXpcj7htiqj8sv8Zip9kVE7lNQFB0xdy1pcUw93ddo4lbGIJX7PTS0fvXfFdnAZ4huVrdqCOBBMApSx3QdRYUnyz+PrxasQIu7pK8Cl0yACBFUbMhMazqzo2485 me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpBFilw+qXCrkbxzk3jQ+Bx/wLpPozc6Nz1A/LjHWlmXJ94js9PVHPwhg7JbiMlakn5rHEPRNEHF9S2m6lOIV1s0KCZR1FYpQArB312KCbH8TtovPwAOgcwcosEn54Ewko5EOCpQAMYdEs4qMAOR7tGA5Opi/rEx9S5n3DohZ5XIcbtRshgMDllYN6OAdck3WN2tj4JWjUrUXRI3BVxKTxlmH9zRqIta6Ph2M/+/DYnQa+jyAzYXiErqqmylT/OReYXxhSVbM+GLsuW82On+wa8DrL8YomHejwKAkZZgH9LGw6QIwI8GNWyF0SbMx1fYnEedp1DSi0Kt2gfIcah+0Z me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5n+uTbZOqqMapxVy621kJbpEvPiiy40rkU7d43WUQC00HPvXeN68ZzXiXgpRFtdJi9UbmmuTuPWgwkKI+Ifx/khM0BDTb9akJJnAizp26zbYoCQTxxzwvrv0DXTaMUThTdw6RVEKYVm69QoAQXpj0O06BHgb7Vp0si240Ny9xFMDfm0LURcemw0/GkakYbEa3LCpC8qNA+hjFc7LP6F//MbgxLgJPMM9e63SlxvAYfkJMzX/nCVcT55a01ng3VXihtt4+ERHhtJfZaPnAoMqagvi1iBQLPreP8euXjtZyHLiUtdYOJV6tuUFNyTeB1I0H2ll3ikDHJjpYGsSv/ffZ me@my-computer
        me:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+NC6tKzpT0GiYwscFoD8n/MdktvymPO8ncn2pAIAy34yiworwx9hLlOeMDsHaFb5LoT3qgqPoiaH1KWmFILKGtb/s9xqzpGZQFPu62nE4zd6Fa82c0rREtIfvst6EbclWSS4uLSn+Pmb6AQBZm3hubbslUMRZzj0vihyVi1y0rboL2U4X8ROZwQzZKG8iQf6k0A31Nb77DOqxQD4twPs2TCU5Hzc7mGWZGDbrUljWNyLJFBoTRDVa+Llc7aKP3MEzR20VcXB1SbB1BZr93MpQkQ+hpmoMAxikmhR6EpRfDs+pw2lHdBuOljhdJhOIZLudJAEfLwZw/4B9rZo9J6xn me@my-computer
        """)
    new_ssh_keys = ssh_keys + 'me:' + self.public_key_material

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],

        [(self.compute_v1.projects,
          'SetCommonInstanceMetadata',
          messages.ComputeProjectsSetCommonInstanceMetadataRequest(
              metadata=messages.Metadata(
                  items=[
                      messages.Metadata.ItemsValueListEntry(
                          key='a',
                          value='b'),
                      messages.Metadata.ItemsValueListEntry(
                          key='ssh-keys',
                          value=new_ssh_keys),
                  ]),

              project='my-project'))],
    )
    self.AssertErrContains('Updating project ssh metadata')

  def testKeyRemoval(self):
    test_key = (
        'ssh-rsa '
        'AAAAB3NzaC1yc2EAAAADAQABAAABAQCwqx8+h4c6K0ipqLqXt1y4ohpbk6PxDdWzprGxNF'
        'rsir/QrOy6iQBAyvlbAb/kM5RaNkjliakfmNEMBH3/tmhBIEmSAsZ0dfhwBof0Hm+bRFI4'
        '75ik/p7QKSpPXf2nCgG3QF75jfLrk+4R6P+0w3zxbq63LxrB7umUxTA2tGMqgNIW0OQ/w2'
        'mfl4DfFTTXQeJ4/Gu6grpl1+Mi7RwtV9RPE5UuveXpcj7htiqj8sv8Zip9kVE7lNQFB0xd'
        'y1pcUw93ddo4lbGIJX7PTS0fvXfFdnAZ4huVrdqCOBBMApSx3QdRYUnyz+PrxasQIu7pK8'
        'Cl0yACBFUbMhMazqzo2485'
        ' me@my-computer')

    # Fills up a buffer with enough test_keys until we go just over
    # the max size allowed.
    buf = io.StringIO()
    i = 0
    while len(buf.getvalue()) < self.max_metadata_value_size_in_bytes:
      buf.write('user-')
      buf.write(six.text_type(i))
      buf.write(':')
      buf.write(test_key)
      buf.write('\n')
      i += 1
    ssh_keys = buf.getvalue()

    project_resource = messages.Project(
        commonInstanceMetadata=messages.Metadata(
            items=[
                messages.Metadata.ItemsValueListEntry(
                    key='a',
                    value='b'),
                messages.Metadata.ItemsValueListEntry(
                    key='ssh-keys',
                    value=ssh_keys),
            ]),
        name='my-project',
    )

    self.make_requests.side_effect = iter([
        [project_resource],
        [],
    ])

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    # If all went well, the first two keys should have been evicted.
    ssh_keys = '\n'.join(ssh_keys.split('\n')[2:])

    new_ssh_keys = ssh_keys + 'me:' + self.public_key_material

    self.CheckRequests(
        [(self.compute_v1.projects,
          'Get',
          messages.ComputeProjectsGetRequest(
              project='my-project'))],

        [(self.compute_v1.projects,
          'SetCommonInstanceMetadata',
          messages.ComputeProjectsSetCommonInstanceMetadataRequest(
              metadata=messages.Metadata(
                  items=[
                      messages.Metadata.ItemsValueListEntry(
                          key='a',
                          value='b'),
                      messages.Metadata.ItemsValueListEntry(
                          key='ssh-keys',
                          value=new_ssh_keys),
                  ]),

              project='my-project'))],
    )

    # Ensures that log messages were written for the two keys removed.
    self.AssertErrContains(
        'The following SSH key will be removed from your project '
        'because your SSH keys metadata value has reached its '
        'maximum allowed size of 262144 bytes: user-0')
    self.AssertErrContains(
        'The following SSH key will be removed from your project '
        'because your SSH keys metadata value has reached its '
        'maximum allowed size of 262144 bytes: user-1')
    self.AssertErrContains('Updating project ssh metadata')

  def testDontDuplicateHost(self):
    """Remove previous host entries if they match a newly appended host."""

    with open(self.config_path, 'w') as f:
      f.write(textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 27.182.818.28
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.98425
            IdentitiesOnly=maybe
            CheckHostIP=yes

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))

    self.Run("""
        compute config-ssh
        """)

    self.assertMultiLineEqual(self.ReadConfigFile(), textwrap.dedent("""\
        # Google Compute Engine Section
        #
        # The following has been auto-generated by "gcloud compute config-ssh"
        # to make accessing your Google Compute Engine virtual machines easier.
        #
        # To remove this blob, run:
        #
        #   gcloud compute config-ssh --remove
        #
        # You can also manually remove this blob by deleting everything from
        # here until the comment that contains the string "End of Google Compute
        # Engine Section".
        #
        # You should not hand-edit this section, unless you are deleting it.
        #
        Host instance-1.zone-1.my-project
            HostName 23.251.133.75
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.11111
            IdentitiesOnly=yes
            CheckHostIP=no

        Host instance-2.zone-1.my-project
            HostName 23.251.133.74
            IdentityFile {0}
            UserKnownHostsFile={1}
            HostKeyAlias=compute.22222
            IdentitiesOnly=yes
            CheckHostIP=no

        # End of Google Compute Engine Section
        """.format(self.private_key_file, self.known_hosts_file)))


if __name__ == '__main__':
  test_case.main()
