
.TH "GCLOUD_ALPHA_DLP_JOB\-TRIGGERS_DELETE" 1



.SH "NAME"
.HP
gcloud alpha dlp job\-triggers delete \- delete a Cloud DLP job trigger



.SH "SYNOPSIS"
.HP
\f5gcloud alpha dlp job\-triggers delete\fR \fIJOB_TRIGGER\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Delete a Cloud DLP job trigger.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Job trigger resource \- The Cloud DLP job trigger to delete. This represents a
Cloud resource. (NOTE) Some attributes are not given arguments in this group but
can be set in other ways. To set the [project] attribute: provide the argument
[job_trigger] on the command line with a fully specified name; provide the
argument [\-\-project] on the command line; set the property [core/project].
This must be specified.

.RS 2m
.TP 2m
\fIJOB_TRIGGER\fR
ID of the job_trigger or fully qualified identifier for the job_trigger.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBdlp/v2\fR API. The full documentation for this API can
be found at: https://cloud.google.com/dlp/docs/



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

