
.TH "GCLOUD_FIREBASE_TEST" 1



.SH "NAME"
.HP
gcloud firebase test \- interact with Firebase Test Lab



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Explore devices and OS versions available as test targets, run tests, monitor
test progress, and view detailed test results in the Firebase console.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBandroid\fR
Command group for Android application testing.

.TP 2m
\fBios\fR
Command group for iOS application testing.

.TP 2m
\fBnetwork\-profiles\fR
Explore network profiles available for testing.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha firebase test
$ gcloud beta firebase test
.RE

