
.TH "GCLOUD_SCHEDULER_JOBS_CREATE_APP\-ENGINE" 1



.SH "NAME"
.HP
gcloud scheduler jobs create app\-engine \- create a Cloud Scheduler job with an App Engine target



.SH "SYNOPSIS"
.HP
\f5gcloud scheduler jobs create app\-engine\fR \fIJOB\fR \fB\-\-schedule\fR=\fISCHEDULE\fR [\fB\-\-attempt\-deadline\fR=\fIATTEMPT_DEADLINE\fR] [\fB\-\-description\fR=\fIDESCRIPTION\fR] [\fB\-\-headers\fR=\fIHEADERS\fR] [\fB\-\-http\-method\fR=\fIHTTP_METHOD\fR;\ default="post"] [\fB\-\-max\-backoff\fR=\fIMAX_BACKOFF\fR;\ default="1h"] [\fB\-\-max\-doublings\fR=\fIMAX_DOUBLINGS\fR;\ default=16] [\fB\-\-max\-retry\-attempts\fR=\fIMAX_RETRY_ATTEMPTS\fR] [\fB\-\-max\-retry\-duration\fR=\fIMAX_RETRY_DURATION\fR] [\fB\-\-min\-backoff\fR=\fIMIN_BACKOFF\fR;\ default="5s"] [\fB\-\-relative\-url\fR=\fIRELATIVE_URL\fR;\ default="/"] [\fB\-\-service\fR=\fISERVICE\fR] [\fB\-\-time\-zone\fR=\fITIME_ZONE\fR;\ default="Etc/UTC"] [\fB\-\-version\fR=\fIVERSION\fR] [\fB\-\-message\-body\fR=\fIMESSAGE_BODY\fR\ |\ \fB\-\-message\-body\-from\-file\fR=\fIMESSAGE_BODY_FROM_FILE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create a Cloud Scheduler job with an App Engine target.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Job resource \- Job to create. This represents a Cloud resource. (NOTE) Some
attributes are not given arguments in this group but can be set in other ways.
To set the [project] attribute: provide the argument [job] on the command line
with a fully specified name; provide the argument [\-\-project] on the command
line; set the property [core/project]. To set the [location] attribute: provide
the argument [job] on the command line with a fully specified name; as the
location of the current project's App Engine App. This must be specified.

.RS 2m
.TP 2m
\fIJOB\fR
ID of the job or fully qualified identifier for the job.


.RE
.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-schedule\fR=\fISCHEDULE\fR
Schedule on which the job will be executed.

As a general rule, execution \f5n + 1\fR of a job will not begin until execution
\f5n\fR has finished. Cloud Scheduler will never allow two simultaneously
outstanding executions. For example, this implies that if the \f5n+1\fR
execution is scheduled to run at \f516:00\fR but the \f5n\fR execution takes
until \f516:15\fR, the \f5n+1\fR execution will not start until \f516:15\fR. A
scheduled start time will be delayed if the previous execution has not ended
when its scheduled time occurs.

If \-\-retry\-count > 0 and a job attempt fails, the job will be tried a total
of \-\-retry\-count times, with exponential backoff, until the next scheduled
start time.

The schedule can be either of the following types:
.RS 2m
.IP "\(em" 2m
Crontab: http://en.wikipedia.org/wiki/Cron#Overview
.IP "\(em" 2m
English\-like schedule:
https://cloud.google.com/scheduler/docs/quickstart#defining_the_job_schedule
.RE
.RE
.sp



.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-attempt\-deadline\fR=\fIATTEMPT_DEADLINE\fR
The deadline for job attempts. If the request handler doesn't respond by this
dealine, the request is cancelled and the attempt is marked as failed. For
example, 20s.

.TP 2m
\fB\-\-description\fR=\fIDESCRIPTION\fR
Human\-readable description of the job.

.TP 2m
\fB\-\-headers\fR=\fIHEADERS\fR
KEY=VALUE pairs of HTTP headers to include in the request. \fBCannot be
repeated\fR. For example: \f5\-\-headers
Accept\-Language=en\-us,Accept=text/plain\fR

.TP 2m
\fB\-\-http\-method\fR=\fIHTTP_METHOD\fR; default="post"
HTTP method to use for the request. \fIHTTP_METHOD\fR must be one of:
\fBdelete\fR, \fBget\fR, \fBhead\fR, \fBpost\fR, \fBput\fR.

.TP 2m
\fB\-\-max\-backoff\fR=\fIMAX_BACKOFF\fR; default="1h"
Maximum amount of time to wait before retrying a task after it fails. For
example, \f510m\fR. Default is \f51h\fR.

.TP 2m
\fB\-\-max\-doublings\fR=\fIMAX_DOUBLINGS\fR; default=16
Maximum number of times that the interval between failed job retries will be
doubled before the increase becomes constant.

.TP 2m
\fB\-\-max\-retry\-attempts\fR=\fIMAX_RETRY_ATTEMPTS\fR
Number of times to retry the request if it fails or times out. Must be in range
0\-5 inclusive. Default is 0.

.TP 2m
\fB\-\-max\-retry\-duration\fR=\fIMAX_RETRY_DURATION\fR
Time limit for retrying a failed task, measured from when the task was first
run. If specified with \f5\-\-max\-retry\-attempts\fR greater than 0, the task
will be retried until both limits are reached. Default is 0 (which means
unlimited).

.TP 2m
\fB\-\-min\-backoff\fR=\fIMIN_BACKOFF\fR; default="5s"
Minimum amount of time to wait before retrying a task after it fails. For
example, \f510s\fR. Default is \f55s\fR.

.TP 2m
\fB\-\-relative\-url\fR=\fIRELATIVE_URL\fR; default="/"
Relative URL to use for the request (beginning with "/").

.TP 2m
\fB\-\-service\fR=\fISERVICE\fR
ID of the App Engine service to send the request to.

.TP 2m
\fB\-\-time\-zone\fR=\fITIME_ZONE\fR; default="Etc/UTC"
Specifies the time zone to be used in interpreting \-\-schedule. The value of
this field must be a time zone name from the tz database
(http://en.wikipedia.org/wiki/Tz_database).

Note that some time zones include a provision for daylight savings time. The
rules for daylight saving time are determined by the chosen time zone.

For UTC use the string "utc". Default is "utc".

.TP 2m
\fB\-\-version\fR=\fIVERSION\fR
Version of the App Engine service to send the request to.

.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-message\-body\fR=\fIMESSAGE_BODY\fR
Data payload to be included as the body of the HTTP request. May only be given
with compatible HTTP methods (PUT or POST).

.TP 2m
\fB\-\-message\-body\-from\-file\fR=\fIMESSAGE_BODY_FROM_FILE\fR
Path to file containing the data payload to be included as the body of the HTTP
request. May only be given with compatible HTTP methods (PUT or POST).


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBcloudscheduler/v1\fR API. The full documentation for
this API can be found at: https://cloud.google.com/scheduler/



.SH "EXAMPLES"

The following command creates a job that sends a request to the '/cron\-handler'
path in you App Engine app every 3 hours:

.RS 2m
$ gcloud scheduler jobs create app\-engine my\-job \e
    \-\-schedule="0 */3 * * *"
  \-\-relative\-url="/cron\-handler"
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha scheduler jobs create app\-engine
$ gcloud beta scheduler jobs create app\-engine
.RE

