
.TH "GCLOUD_ALPHA_FIRESTORE_INDEXES_COMPOSITE_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha firestore indexes composite describe \- describe the given composite index



.SH "SYNOPSIS"
.HP
\f5gcloud alpha firestore indexes composite describe\fR \fIINDEX\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Describe the given composite index.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Composite index resource \- Index to describe. This represents a Cloud resource.
(NOTE) Some attributes are not given arguments in this group but can be set in
other ways. To set the [project] attribute: provide the argument [index] on the
command line with a fully specified name; set the property [core/project];
provide the argument [\-\-project] on the command line. To set the [database]
attribute: provide the argument [index] on the command line with a fully
specified name; provide the argument [\-\-database] on the command line
(currently '(default)' is the only supported value). To set the
[collection\-group] attribute: provide the argument [index] on the command line
with a fully specified name; provide the argument [\-\-collection\-group] on the
command line. This must be specified.


.RS 2m
.TP 2m
\fIINDEX\fR
ID of the composite index or fully qualified identifier for the composite index.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBfirestore/v1beta2\fR API. The full documentation for
this API can be found at: https://cloud.google.com/firestore



.SH "EXAMPLES"

The following command describes the composite index with ID \f53421ef\fR:

.RS 2m
$ gcloud alpha firestore indexes composite describe 3421ef
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. This variant is also available:

.RS 2m
$ gcloud beta firestore indexes composite describe
.RE

