
.TH "GCLOUD_ALPHA_NETWORK\-CONNECTIVITY" 1



.SH "NAME"
.HP
gcloud alpha network\-connectivity \- manage Network Connectivity Resources



.SH "SYNOPSIS"
.HP
\f5gcloud alpha network\-connectivity\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Network Connectivity Resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBhubs\fR
\fB(ALPHA)\fR Manage Network Connectivity Hubs.

.TP 2m
\fBspokes\fR
\fB(ALPHA)\fR Manage Network Connectivity Spokes.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

