
.TH "GCLOUD_BIGTABLE_CLUSTERS" 1



.SH "NAME"
.HP
gcloud bigtable clusters \- manage Cloud Bigtable clusters



.SH "SYNOPSIS"
.HP
\f5gcloud bigtable clusters\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Bigtable clusters.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe an existing Bigtable cluster.

.TP 2m
\fBlist\fR
List existing Bigtable clusters.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha bigtable clusters
$ gcloud beta bigtable clusters
.RE

