
.TH "GCLOUD_BETA_DATAFLOW_LOGS" 1



.SH "NAME"
.HP
gcloud beta dataflow logs \- a group of subcommands for working with Dataflow logs



.SH "SYNOPSIS"
.HP
\f5gcloud beta dataflow logs\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR A group of subcommands for working with Dataflow logs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlist\fR
\fB(BETA)\fR Retrieve the job logs for a specific job.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha dataflow logs
.RE

