
.TH "GCLOUD_BETA_RECOMMENDER_INSIGHTS" 1



.SH "NAME"
.HP
gcloud beta recommender insights \- manage Cloud resource insights



.SH "SYNOPSIS"
.HP
\f5gcloud beta recommender insights\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage Cloud resource insights.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe an insight.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List insights for a Cloud project.

.TP 2m
\fBmark\-accepted\fR
\fB(BETA)\fR Mark an insight's state as ACCEPTED. Can be applied to insights in
ACTIVE or ACCEPTED state.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha recommender insights
.RE

