
.TH "GCLOUD_ALPHA_FIRESTORE_OPERATIONS_CANCEL" 1



.SH "NAME"
.HP
gcloud alpha firestore operations cancel \- cancel a currently\-running Cloud Firestore admin operation



.SH "SYNOPSIS"
.HP
\f5gcloud alpha firestore operations cancel\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Cancel a currently\-running Cloud Firestore admin operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The unique name of the Operation to cancel, formatted as either the full or
relative resource path:

.RS 2m
projects/my\-app\-id/databases/(default)/operations/foo
.RE

or:

.RS 2m
foo
.RE


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta firestore operations cancel
.RE

