
.TH "GCLOUD_NETWORK\-MANAGEMENT_CONNECTIVITY\-TESTS" 1



.SH "NAME"
.HP
gcloud network\-management connectivity\-tests \- manage Network Management ConnectivityTests



.SH "SYNOPSIS"
.HP
\f5gcloud network\-management connectivity\-tests\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Network Management ConnectivityTests.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a new connectivity test.

.TP 2m
\fBdelete\fR
Delete a connectivity test.

.TP 2m
\fBdescribe\fR
Describe a connectivity test.

.TP 2m
\fBlist\fR
List connectivity tests.

.TP 2m
\fBrerun\fR
Rerun a connectivity test.

.TP 2m
\fBupdate\fR
Update an existing connectivity test.


.RE
.sp

.SH "NOTES"

This variant is also available:

.RS 2m
$ gcloud beta network\-management connectivity\-tests
.RE

