
.TH "GCLOUD_BIGTABLE_INSTANCES_TABLES" 1



.SH "NAME"
.HP
gcloud bigtable instances tables \- query Cloud Bigtable tables



.SH "SYNOPSIS"
.HP
\f5gcloud bigtable instances tables\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Query Cloud Bigtable tables.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add an IAM policy binding to a Cloud Bigtable table.

.TP 2m
\fBget\-iam\-policy\fR
Get an IAM policy on a Cloud Bigtable table.

.TP 2m
\fBlist\fR
List existing Bigtable instance tables.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove an IAM policy binding from a Cloud Bigtable table.

.TP 2m
\fBrestore\fR
Restore a Cloud Bigtable backup to a new table.

.TP 2m
\fBset\-iam\-policy\fR
Set an IAM policy on a Cloud Bigtable table.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha bigtable instances tables
$ gcloud beta bigtable instances tables
.RE

