
.TH "GCLOUD_ALPHA_DATAFLOW_SNAPSHOTS" 1



.SH "NAME"
.HP
gcloud alpha dataflow snapshots \- a group of subcommands for working with Cloud Dataflow snapshots



.SH "SYNOPSIS"
.HP
\f5gcloud alpha dataflow snapshots\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR A group of subcommands for working with Cloud Dataflow snapshots.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Creates a snapshot for a Cloud Dataflow job.

.TP 2m
\fBdelete\fR
\fB(ALPHA)\fR Delete a Cloud Dataflow snapshot.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe a Cloud Dataflow snapshot.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List all Cloud Dataflow snapshots in a project in the specified
region, optionally filtered by job ID.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta dataflow snapshots
.RE

