
.TH "GCLOUD_ALPHA_NETWORK\-SECURITY" 1



.SH "NAME"
.HP
gcloud alpha network\-security \- manage Network Security resources



.SH "SYNOPSIS"
.HP
\f5gcloud alpha network\-security\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Network Security resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBauthorization\-policies\fR
\fB(ALPHA)\fR Manage Network Security AuthorizationPolicies.

.TP 2m
\fBclient\-tls\-policies\fR
\fB(ALPHA)\fR Manage Network Security ClientTlsPolicies.

.TP 2m
\fBserver\-tls\-policies\fR
\fB(ALPHA)\fR Manage Network Security ServerTlsPolicies.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

