
.TH "GCLOUD_BETA_COMPUTE_BACKEND\-SERVICES_DELETE" 1



.SH "NAME"
.HP
gcloud beta compute backend\-services delete \- delete backend services



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute backend\-services delete\fR \fIBACKEND_SERVICE_NAME\fR [\fIBACKEND_SERVICE_NAME\fR\ ...] [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute backend\-services delete\fR deletes one or
more backend services.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBACKEND_SERVICE_NAME\fR [\fIBACKEND_SERVICE_NAME\fR ...]
Names of the backend services to delete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If set, the backend services are global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the backend services to delete. Overrides the default
\fBcompute/region\fR property value for this command invocation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute backend\-services delete
$ gcloud alpha compute backend\-services delete
.RE

