
.TH "GCLOUD_BETA_COMPUTE_NETWORKS_DELETE" 1



.SH "NAME"
.HP
gcloud beta compute networks delete \- delete Compute Engine networks



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute networks delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute networks delete\fR deletes one or more
Compute Engine networks. Networks can only be deleted when no other resources
(e.g., virtual machine instances) refer to them.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
Names of the networks to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To delete a network with the name 'network\-name', run:

.RS 2m
$ gcloud beta compute networks delete network\-name
.RE

To delete two networks with the names 'network\-name1' and 'network\-name2',
run:

.RS 2m
$ gcloud beta compute networks delete network\-name1 network\-name2
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute networks delete
$ gcloud alpha compute networks delete
.RE

