
.TH "GCLOUD_BETA_AI" 1



.SH "NAME"
.HP
gcloud beta ai \- manages entities in AI Platform



.SH "SYNOPSIS"
.HP
\f5gcloud beta ai\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manages entities in AI Platform.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcustom\-jobs\fR
\fB(BETA)\fR AI Platform custom job commands.

.TP 2m
\fBendpoints\fR
\fB(BETA)\fR AI Platform endpoint commands.

.TP 2m
\fBhp\-tuning\-jobs\fR
\fB(BETA)\fR AI Platform hyperparameter tuning job commands.

.TP 2m
\fBmodels\fR
\fB(BETA)\fR AI Platform model commands.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha ai
.RE

