
.TH "GCLOUD_ALPHA_TASKS_ACKNOWLEDGE" 1



.SH "NAME"
.HP
gcloud alpha tasks acknowledge \- acknowledge the lease on a task in a pull queue



.SH "SYNOPSIS"
.HP
\f5gcloud alpha tasks acknowledge\fR \fITASK\fR \fB\-\-schedule\-time\fR=\fISCHEDULE_TIME\fR [\fB\-\-queue\fR=\fIQUEUE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Acknowledge the lease on a task in a pull queue.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fITASK\fR
The task to acknowledge.



.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-schedule\-time\fR=\fISCHEDULE_TIME\fR
The task's current schedule time. This restriction is to check that the caller
is acknowledging the correct task.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-queue\fR=\fIQUEUE\fR
The queue the task belongs to.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

