
.TH "GCLOUD_BETA_AI\-PLATFORM_JOBS_SUBMIT" 1



.SH "NAME"
.HP
gcloud beta ai\-platform jobs submit \- AI Platform Jobs submit commands



.SH "SYNOPSIS"
.HP
\f5gcloud beta ai\-platform jobs submit\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR AI Platform Jobs submit commands.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBprediction\fR
\fB(BETA)\fR Start an AI Platform batch prediction job.

.TP 2m
\fBtraining\fR
\fB(BETA)\fR Submit an AI Platform training job.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud ai\-platform jobs submit
$ gcloud alpha ai\-platform jobs submit
.RE

