
.TH "GCLOUD_ALPHA_PUBSUB_SUBSCRIPTIONS_UPDATE" 1



.SH "NAME"
.HP
gcloud alpha pubsub subscriptions update \- this feature is part of an invite\-only release of the Cloud Pub/Sub API



.SH "SYNOPSIS"
.HP
\f5gcloud alpha pubsub subscriptions update\fR \fISUBSCRIPTION\fR [\fB\-\-ack\-deadline\fR=\fIACK_DEADLINE\fR] [\fB\-\-message\-retention\-duration\fR=\fIMESSAGE_RETENTION_DURATION\fR] [\fB\-\-push\-endpoint\fR=\fIPUSH_ENDPOINT\fR] [\fB\-\-retain\-acked\-messages\fR] [\fB\-\-update\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...]] [\fB\-\-clear\-labels\fR\ |\ \fB\-\-remove\-labels\fR=[\fIKEY\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Updates an existing Cloud Pub/Sub subscription. This feature is
part of an invitation\-only release of the underlying Cloud Pub/Sub API. The
command will generate errors unless you have access to this API. This
restriction should be relaxed in the near future. Please contact
cloud\-pubsub@google.com with any questions in the meantime.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

SUBSCRIPTION \- Name of the subscription to update. This represents a Cloud
resource. (NOTE) Some attributes are not given arguments in this group but can
be set in other ways. To set the [project] attribute: Set the property
[core/project] or provide the flag [\-\-project] on the command line. This must
be specified.

.RS 2m
.TP 2m
\fISUBSCRIPTION\fR
The ID of the subscription or a fully qualified identifier for the subscription.


.RE
.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-ack\-deadline\fR=\fIACK_DEADLINE\fR
The number of seconds the system will wait for a subscriber to acknowledge
receiving a message before re\-attempting delivery.

.TP 2m
\fB\-\-message\-retention\-duration\fR=\fIMESSAGE_RETENTION_DURATION\fR
How long to retain unacknowledged messages in the subscription's backlog, from
the moment a message is published. If \-\-retain\-acked\-messages is true, this
also configures the retention of acknowledged messages. Specify "default" to use
the default value. Valid values are strings of the form INTEGER[UNIT], where
UNIT is one of "s", "m", "h", and "d" for seconds, seconds, minutes, hours, and
days, respectively. If the unit is omitted, seconds is assumed.

.TP 2m
\fB\-\-push\-endpoint\fR=\fIPUSH_ENDPOINT\fR
A URL to use as the endpoint for this subscription. This will also automatically
set the subscription type to PUSH.

.TP 2m
\fB\-\-retain\-acked\-messages\fR
Whether or not to retain acknowledged messages. If true, messages are not
expunged from the subscription's backlog until they fall out of the
\-\-message\-retention\-duration window.

.TP 2m
\fB\-\-update\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...]
A list of label KEY=VALUE pairs to update. If a label exists its value is
modified, otherwise a new label is created.

.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-clear\-labels\fR
Removes all labels. If \f5\-\-update\-labels\fR is also specified then
\f5\-\-clear\-labels\fR is applied first.

For example, to remove all labels:

.RS 2m
$ gcloud alpha pubsub subscriptions update \-\-clear\-labels
.RE

To set the labels to exactly "foo" and "baz":

.RS 2m
$ gcloud alpha pubsub subscriptions update \-\-clear\-labels \e
  \-\-update\-labels foo=bar,baz=qux
.RE

.TP 2m
\fB\-\-remove\-labels\fR=[\fIKEY\fR,...]
A list of label keys to remove. If a label does not exist it is silently
ignored.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/.

