
.TH "GCLOUD_SPANNER_DATABASES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud spanner databases describe \- describe a Cloud Spanner database



.SH "SYNOPSIS"
.HP
\f5gcloud spanner databases describe\fR (\fIDATABASE\fR\ :\ \fB\-\-instance\fR=\fIINSTANCE\fR) [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe a Cloud Spanner database.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Database resource \- The Cloud Spanner database to describe. The arguments in
this group can be used to specify the attributes of this resource. (NOTE) Some
attributes are not given arguments in this group but can be set in other ways.
To set the [project] attribute: Set the property [core/project] or provide the
flag [\-\-project] on the command line. This must be specified.

.RS 2m
.TP 2m
\fIDATABASE\fR
The ID of the database or a fully qualified identifier for the database. This
positional must be specified if any of the other arguments in this group are
specified.

.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR
The Cloud Spanner instance for the database.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha spanner databases describe
$ gcloud beta spanner databases describe
.RE

