
.TH "GCLOUD_ALPHA_COMPUTE_INSTANCE\-GROUPS_MANAGED_INSTANCE\-CONFIGS_UPDATE" 1



.SH "NAME"
.HP
gcloud alpha compute instance\-groups managed instance\-configs update \- update per instance config of a managed instance group



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute instance\-groups managed instance\-configs update\fR \fINAME\fR \fB\-\-instance\fR=\fIINSTANCE\fR [\fB\-\-force\-instance\-update\fR] [\fB\-\-remove\-stateful\-disks\fR=\fIDEVICE_NAME\fR,[\fIDEVICE_NAME\fR,...]] [\fB\-\-remove\-stateful\-metadata\fR=\fIKEY\fR,[\fIKEY\fR,...]] [\fB\-\-update\-stateful\-disk\fR=[\fIdevice\-name\fR=\fIDEVICE\-NAME\fR],[\fImode\fR=\fIMODE\fR],[\fIsource\fR=\fISOURCE\fR]] [\fB\-\-update\-stateful\-metadata\fR=\fIKEY\fR=\fIVALUE\fR,[\fIKEY\fR=\fIVALUE\fR,...]] [\fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute instance\-groups managed instance\-configs
update\fR updates per instance config of instance controlled by a Google Compute
Engine managed instance group. Command gives option to change the list of
preserved resources by the instance during restart or recreation.

For example:

.RS 2m
$ gcloud alpha compute instance\-groups managed instance\-configs \e
    update example\-group \-\-instance=example\-instance \e
    \-\-update\-stateful\-disk=device\-name=my\-disk\-3,\e
    source=projects/my\-project/zones/us\-central1\-a/disks/my\-disk\-3 \e
    \-\-remove\-stateful\-disks=my\-disk\-1,my\-disk\-2
.RE

will update stateful disk \f5my\-disk\-3\fR to the new one pointed by
\f5source\fR (or add if \f5my\-disk\-3\fR did not exist in the instance config);
it will also remove \f5my\-disk\-1\fR and \f5my\-disk\-2\fR from the instance
config overrides \- they will not be preserved anymore during next restart or
recreation of the instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the managed instance group to update per instance config for.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR
URI to existing or non existing instance.

Name \- last part of URI \- will be preserved for existing per instance configs.

For zonal managed instance groups there is no need to specify the whole URI to
the instance \- for this case instance name can be applied instead of URI.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-force\-instance\-update\fR
The changes will be applied immediately to the instances. If this flag is not
provided, the changes will be applied once the instances are restarted or
recreated.

Example: let's say we have an instance with a disk attached to it and an
override for the disk. If we decide to delete the override and provide this
flag, this will instantly recreate the instance and detach the disk from it.
Similarly if we have attached new disk or changed its definition \- with this
flag it will instantly recreate instance with newly applied overrides.

If we omit this flag, the instance will continue to exist with no overrides
changes applied until it gets restarted or recreated either manually or by
autohealer or updater.

.TP 2m
\fB\-\-remove\-stateful\-disks\fR=\fIDEVICE_NAME\fR,[\fIDEVICE_NAME\fR,...]
List all device names which should be removed from current instance config.

.TP 2m
\fB\-\-remove\-stateful\-metadata\fR=\fIKEY\fR,[\fIKEY\fR,...]
List all stateful metadata keys which should be removed from current instance
config.

.TP 2m
\fB\-\-update\-stateful\-disk\fR=[\fIdevice\-name\fR=\fIDEVICE\-NAME\fR],[\fImode\fR=\fIMODE\fR],[\fIsource\fR=\fISOURCE\fR]
Disks considered stateful by the instance group. Usually, the managed instance
group deletes disks when deleting instances; however, in the case of stateful
disks, these disks are detached from the deleted instance and attached to new
instances the managed instance group creates.

Besides preserving disks already attached to the instance by specifying only
device names, user have an option to attach (and preserve) other existing
persistent disk(s) to the given instance.

The same disk can be attached to many instances but only in read\-only mode.

Use this argument multiple times to update multiple disks.

If stateful disk with given \f5device\-name\fR exists in current instance
config, its properties will be replaced by the newly provided ones. In other
case new stateful disk definition will be added to the instance config.

.RS 2m
.TP 2m
\fBdevice\-name\fR
Name under which disk is or will be attached.

.TP 2m
\fBsource\fR
Optional argument used to specify URI of existing persistent disk to attach
under specified \f5device\-name\fR.

.TP 2m
\fBmode\fR
Specifies the mode of the disk to attach. Supported options are \f5ro\fR for
read\-only and \f5rw\fR for read\-write. If omitted when source is specified,
\f5rw\fR is used as a default.

.RE
.sp
.TP 2m
\fB\-\-update\-stateful\-metadata\fR=\fIKEY\fR=\fIVALUE\fR,[\fIKEY\fR=\fIVALUE\fR,...]
Additional metadata to be made available to the guest operating system on top of
the metadata defined in the instance template.

Stateful metadata may be used to define a key/value pair specific for the one
given instance to differentiate it from the other instances in the managed
instance group.

Stateful metadata have priority over the metadata defined in the instance
template. It means that stateful metadata defined for the keys already existing
in the instance template override their values.

Each metadata entry is a key/value pair separated by an equals sign. Metadata
keys must be unique and less than 128 bytes in length. Multiple entries can be
passed to this flag, e.g., \f5\fI\-\-update\-stateful\-metadata
key\-1=value\-1,key\-2=value\-2,key\-3=value\-3\fR\fR.

If stateful metadata with the given key exists in current instance config, its
value will be overridden with the newly provided one. If the key does not exist
in the current instance config, a new key/value pair will be added.

.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the managed instance group to update per instance config for. If
not specified, you will be prompted to select a region.

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

Overrides the default \fBcompute/region\fR property value for this command
invocation.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone of the managed instance group to update per instance config for. If not
specified, you may be prompted to select a zone.

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE

Overrides the default \fBcompute/zone\fR property value for this command
invocation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/.

