
.TH "GCLOUD_BETA_COMPUTE_VPN\-GATEWAYS" 1



.SH "NAME"
.HP
gcloud beta compute vpn\-gateways \- read and manipulate Google Compute Engine Highly Available VPN Gateways



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute vpn\-gateways\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR read and manipulate Highly Available VPN Gateways.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(BETA)\fR Create a new Google Compute Engine High Available VPN gateway.

.TP 2m
\fBdelete\fR
\fB(BETA)\fR Delete Google Compute Engine Highly Available VPN Gateways.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe a Google Compute Engine Highly Available VPN Gateway.

.TP 2m
\fBget\-status\fR
\fB(BETA)\fR Get status of a Google Compute Engine VPN Gateway.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List Google Compute Engine Highly Available VPN Gateways.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR Update a Google Compute Engine Highly Available VPN gateway.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha compute vpn\-gateways
.RE

