
.TH "GCLOUD_COMPUTE_ROUTERS_NATS" 1



.SH "NAME"
.HP
gcloud compute routers nats \- list, create, describe, and delete Cloud NAT



.SH "SYNOPSIS"
.HP
\f5gcloud compute routers nats\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, describe, and delete Cloud NAT.

For more information about Cloud NAT, see the Cloud NAT documentation
(https://cloud.google.com/nat/docs/using\-nat).



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Add a NAT to a Google Compute Engine router.

.TP 2m
\fBdelete\fR
Remove a NAT from a Google Compute Engine router.

.TP 2m
\fBdescribe\fR
Describe a NAT in a Google Compute Engine router.

.TP 2m
\fBlist\fR
Lists the NATs on a Google Compute Engine router.

.TP 2m
\fBupdate\fR
Update a NAT on a Google Compute Engine router.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute routers nats
$ gcloud beta compute routers nats
.RE

