
.TH "GCLOUD_ALPHA_COMPUTE_HEALTH\-CHECKS_UPDATE_GRPC" 1



.SH "NAME"
.HP
gcloud alpha compute health\-checks update grpc \- update a gRPC health check



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute health\-checks update grpc\fR \fINAME\fR [\fB\-\-check\-interval\fR=\fICHECK_INTERVAL\fR] [\fB\-\-description\fR=\fIDESCRIPTION\fR] [\fB\-\-enable\-logging\fR] [\fB\-\-grpc\-service\-name\fR=\fIGRPC_SERVICE_NAME\fR] [\fB\-\-healthy\-threshold\fR=\fIHEALTHY_THRESHOLD\fR] [\fB\-\-timeout\fR=\fITIMEOUT\fR] [\fB\-\-unhealthy\-threshold\fR=\fIUNHEALTHY_THRESHOLD\fR] [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fB\-\-port\fR=\fIPORT\fR\ \fB\-\-port\-name\fR=\fIPORT_NAME\fR\ \fB\-\-use\-serving\-port\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute health\-checks update grpc\fR is used to
update an existing gRPC health check. Only arguments passed in will be updated
on the health check. Other attributes will remain unaffected.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the gRPC health check to update.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-check\-interval\fR=\fICHECK_INTERVAL\fR
How often to perform a health check for an instance. For example, specifying
\f5\fI10s\fR\fR will run the check every 10 seconds. See $ gcloud topic
datetimes for information on duration formats.

.TP 2m
\fB\-\-description\fR=\fIDESCRIPTION\fR
A textual description for the gRPC health check. Pass in an empty string to
unset.

.TP 2m
\fB\-\-enable\-logging\fR
Enable logging of health check probe results to Stackdriver. Logging is disabled
by default.

.RS 2m
Use \-\-no\-enable\-logging to disable logging.
.RE

.TP 2m
\fB\-\-grpc\-service\-name\fR=\fIGRPC_SERVICE_NAME\fR
An optional gRPC service name string of up to 1024 characters to include in the
gRPC health check request. Pass in an empty string to unset. Only ASCII
characters are allowed.

.TP 2m
\fB\-\-healthy\-threshold\fR=\fIHEALTHY_THRESHOLD\fR
The number of consecutive successful health checks before an unhealthy instance
is marked as healthy.

.TP 2m
\fB\-\-timeout\fR=\fITIMEOUT\fR
If Google Compute Engine doesn't receive a healthy response from the instance by
the time specified by the value of this flag, the health check request is
considered a failure. For example, specifying \f5\fI10s\fR\fR will cause the
check to wait for 10 seconds before considering the request a failure. See $
gcloud topic datetimes for information on duration formats.

.TP 2m
\fB\-\-unhealthy\-threshold\fR=\fIUNHEALTHY_THRESHOLD\fR
The number of consecutive health check failures before a healthy instance is
marked as unhealthy.

.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If set, the gRPC health check is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the gRPC health check to update. If not specified, you may be prompted
to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.

.RE
.sp
.TP 2m

These flags configure the port that the health check monitors. If both
\f5\-\-port\fR and \f5\-\-port\-name\fR are specified, \f5\-\-port\fR takes
precedence.

.RS 2m
.TP 2m
\fB\-\-port\fR=\fIPORT\fR
The TCP port number that this health check monitors.

.TP 2m
\fB\-\-port\-name\fR=\fIPORT_NAME\fR
The port name that this health check monitors. By default, this is empty.
Setting this to an empty string will clear any existing port\-name value.

.TP 2m
\fB\-\-use\-serving\-port\fR
If given, use the "serving port" for health checks:

.RS 2m
.IP "\(bu" 2m
When health checking network endpoints in a Network Endpoint Group, use the port
specified with each endpoint.
.IP "\(bu" 2m
When health checking other backends, use the port or named port of the backend
service.
.RE
.RE
.RE
.sp



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

