
.TH "GCLOUD_ML_VISION_DETECT\-TEXT\-TIFF" 1



.SH "NAME"
.HP
gcloud ml vision detect\-text\-tiff \- detect and transcribe text from TIFF files stored in Google Cloud Storage



.SH "SYNOPSIS"
.HP
\f5gcloud ml vision detect\-text\-tiff\fR \fIINPUT_FILE\fR \fIOUTPUT_PATH\fR [\fB\-\-batch\-size\fR=\fIBATCH_SIZE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Detect and transcribe text from TIFF files stored in Google Cloud Storage.

The Vision API accepts TIFF files up to 2000 pages. Larger files will return an
error.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINPUT_FILE\fR
Google Cloud Storage location to read the input from. It must be in Google Cloud
Storage format (gs://bucket/object)

.TP 2m
\fIOUTPUT_PATH\fR
Google Cloud Storage location to store the output file. It must be in Google
Cloud Storage format (gs://bucket/object)


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-batch\-size\fR=\fIBATCH_SIZE\fR
Maximum number of response protos to put into each output JSON file on Google
Cloud Storage. The valid range is [1, 100]. If not specified, the default value
is 20.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBvision/v1\fR API. The full documentation for this API
can be found at: https://cloud.google.com/vision/



.SH "EXAMPLES"

To detect text for input TIFF file \f5gs://my_bucket/input_file\fR and store
output in \f5gs://my_bucket/out_put_prefix\fR:

.RS 2m
$ gcloud ml vision detect\-text\-tiff gs://my_bucket/input_file
gs://my_bucket/out_put_prefix
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha ml vision detect\-text\-tiff
$ gcloud beta ml vision detect\-text\-tiff
.RE

