
.TH "GCLOUD_BETA_DATAPROC_JOBS_WAIT" 1



.SH "NAME"
.HP
gcloud beta dataproc jobs wait \- view the output of a job as it runs or after it completes



.SH "SYNOPSIS"
.HP
\f5gcloud beta dataproc jobs wait\fR \fIJOB\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR View the output of a job as it runs or after it completes.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB\fR
The ID of the job to wait for.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Cloud Dataproc region to use. Each Cloud Dataproc region constitutes an
independent resource namespace constrained to deploying instances into Compute
Engine zones inside the region. The default value of \f5global\fR is a special
multi\-region namespace which is capable of deploying instances into all Compute
Engine zones globally, and is disjoint from other Cloud Dataproc regions.
Overrides the default \fBdataproc/region\fR property value for this command
invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To see a list of all jobs, run:

.RS 2m
$ gcloud dataproc jobs list
.RE

To display these jobs with their respective IDs and underlying REST calls, run:

.RS 2m
$ gcloud dataproc jobs list \-\-format "table(reference.jobId)" \e
  \-\-limit 1 \-\-log\-http
.RE

To view the output of a job as it runs, run:

.RS 2m
$ gcloud beta dataproc jobs wait job_id
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud dataproc jobs wait
$ gcloud alpha dataproc jobs wait
.RE

