
.TH "GCLOUD_COMPOSER_ENVIRONMENTS_STORAGE" 1



.SH "NAME"
.HP
gcloud composer environments storage \- manage Cloud Storage objects stored as part of Cloud Composer environments



.SH "SYNOPSIS"
.HP
\f5gcloud composer environments storage\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud composer environments storage command group lets you manage DAGs,
Airflow plugins and data used inside your Cloud Composer Environments.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdags\fR
Manage DAGs for Cloud Composer environments.

.TP 2m
\fBdata\fR
Manage data for Cloud Composer environments.

.TP 2m
\fBplugins\fR
Manage plugins for Cloud Composer environments.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha composer environments storage
$ gcloud beta composer environments storage
.RE

