
.TH "GCLOUD_ALPHA_DEPLOYMENT\-MANAGER_TYPE\-PROVIDERS_DELETE" 1



.SH "NAME"
.HP
gcloud alpha deployment\-manager type\-providers delete \- delete a type provider



.SH "SYNOPSIS"
.HP
\f5gcloud alpha deployment\-manager type\-providers delete\fR \fIPROVIDER_NAME\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command deletes a type provider.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROVIDER_NAME\fR
Type provider name or URI.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Return immediately and print information about the Operation in progress rather
than waiting for the Operation to complete. (default=False)


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To delete a type provider, run:

.RS 2m
$ gcloud alpha deployment\-manager type\-providers delete \e
    my\-type\-provider
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta deployment\-manager type\-providers delete
.RE

