
.TH "GCLOUD_COMPUTE_SOLE\-TENANCY_NODE\-TEMPLATES" 1



.SH "NAME"
.HP
gcloud compute sole\-tenancy node\-templates \- read and manage Google Compute Engine sole\-tenancy node templates



.SH "SYNOPSIS"
.HP
\f5gcloud compute sole\-tenancy node\-templates\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Node templates are used to create the nodes in node groups. Nodes are Compute
Engine servers that are dedicated to your workload. Node templates define either
the node type or the requirements for a node in terms of vCPU, memory, and
localSSD.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Creates a Google Compute Engine node template.

.TP 2m
\fBdelete\fR
Deletes a Google Compute Engine node template.

.TP 2m
\fBdescribe\fR
Describes a Google Compute Engine node template.

.TP 2m
\fBlist\fR
List Google Compute Engine node templates.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute sole\-tenancy node\-templates
$ gcloud beta compute sole\-tenancy node\-templates
.RE

