
.TH "GCLOUD_COMPOSER_ENVIRONMENTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud composer environments describe \- get details about a Cloud Composer environment



.SH "SYNOPSIS"
.HP
\f5gcloud composer environments describe\fR (\fIENVIRONMENT\fR\ :\ \fB\-\-location\fR=\fILOCATION\fR) [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Get details about a Cloud Composer environment.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Environment resource \- The environment to describe. The arguments in this group
can be used to specify the attributes of this resource. (NOTE) Some attributes
are not given arguments in this group but can be set in other ways. To set the
[project] attribute: provide the argument [environment] on the command line with
a fully specified name; provide the argument [\-\-project] on the command line;
set the property [core/project]. This must be specified.

.RS 2m
.TP 2m
\fIENVIRONMENT\fR
ID of the environment or fully qualified identifier for the environment. This
positional must be specified if any of the other arguments in this group are
specified.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
Compute Engine region in which to create the environment.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha composer environments describe
$ gcloud beta composer environments describe
.RE

