
.TH "GCLOUD_ALPHA_TASKS_CREATE\-PULL\-TASK" 1



.SH "NAME"
.HP
gcloud alpha tasks create\-pull\-task \- create and add a task to a pull queue



.SH "SYNOPSIS"
.HP
\f5gcloud alpha tasks create\-pull\-task\fR [\fITASK_ID\fR] \fB\-\-queue\fR=\fIQUEUE\fR [\fB\-\-schedule\-time\fR=\fISCHEDULE_TIME\fR] [\fB\-\-tag\fR=\fITAG\fR] [\fB\-\-payload\-content\fR=\fIPAYLOAD_CONTENT\fR\ |\ \fB\-\-payload\-file\fR=\fIPAYLOAD_FILE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Create and add a task to a pull queue.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
[\fITASK_ID\fR]
The task to create.

If not specified then the system will generate a random unique task ID.
Explicitly specifying a task ID enables task de\-duplication. If a task's ID is
identical to that of an existing task or a task that was deleted or completed
recently then the call will fail.

Because there is an extra lookup cost to identify duplicate task names, tasks
created with IDs have significantly increased latency. Using hashed strings for
the task ID or for the prefix of the task ID is recommended.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-queue\fR=\fIQUEUE\fR
The queue the task belongs to.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-schedule\-time\fR=\fISCHEDULE_TIME\fR
The time when the task is scheduled to be first attempted. Defaults to "now" if
not specified.

.TP 2m
\fB\-\-tag\fR=\fITAG\fR
An optional label used to group similar tasks.

.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-payload\-content\fR=\fIPAYLOAD_CONTENT\fR
Data payload used by the task worker to process the task.

.TP 2m
\fB\-\-payload\-file\fR=\fIPAYLOAD_FILE\fR
File containing data payload used by the task worker to process the task.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

