
.TH "GCLOUD_BETA_SQL_CONNECT" 1



.SH "NAME"
.HP
gcloud beta sql connect \- connects to a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud beta sql connect\fR \fIINSTANCE\fR [\fB\-\-database\fR=\fIDATABASE\fR,\ \fB\-d\fR\ \fIDATABASE\fR] [\fB\-\-user\fR=\fIUSER\fR,\ \fB\-u\fR\ \fIUSER\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Connects to a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-database\fR=\fIDATABASE\fR, \fB\-d\fR \fIDATABASE\fR
The PostgreSQL database to connect to.

.TP 2m
\fB\-\-user\fR=\fIUSER\fR, \fB\-u\fR \fIUSER\fR
Cloud SQL instance user to connect as.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To connect to a Cloud SQL instance, run:

.RS 2m
$ gcloud beta sql connect my\-instance \-\-user=root
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud sql connect
.RE

