
.TH "GCLOUD_BETA_RESOURCE\-MANAGER_FOLDERS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud beta resource\-manager folders set\-iam\-policy \- set IAM policy for a folder



.SH "SYNOPSIS"
.HP
\f5gcloud beta resource\-manager folders set\-iam\-policy\fR \fIFOLDER_ID\fR \fIPOLICY_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Sets the IAM policy for a folder, given a folder ID and a file
encoded in JSON or YAML that contains the IAM policy.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIFOLDER_ID\fR
ID for the folder whose policy you want to set.

.TP 2m
\fIPOLICY_FILE\fR
JSON or YAML file with the IAM policy.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

The following command reads an IAM policy defined in a JSON file
\f5policy.json\fR and sets it for a folder with the ID \f53589215982\fR:

.RS 2m
$ gcloud beta resource\-manager folders set\-iam\-policy 3589215982 \e
    policy.json
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud resource\-manager folders set\-iam\-policy
$ gcloud alpha resource\-manager folders set\-iam\-policy
.RE

