
.TH "GCLOUD_BETA_TASKS_LOCATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta tasks locations describe \- show details about a location



.SH "SYNOPSIS"
.HP
\f5gcloud beta tasks locations describe\fR \fILOCATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Show details about a location.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fILOCATION\fR
The Cloud location to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha tasks locations describe
.RE

