
.TH "GCLOUD_ALPHA_COMPUTE_INSTANCE\-GROUPS_MANAGED_UPDATE" 1



.SH "NAME"
.HP
gcloud alpha compute instance\-groups managed update \- update Google Compute Engine managed instance groups



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute instance\-groups managed update\fR \fINAME\fR [\fB\-\-add\-stateful\-disks\fR=\fIDEVICE_NAME\fR,[\fIDEVICE_NAME\fR,...]] [\fB\-\-instance\-redistribution\-type\fR=\fITYPE\fR] [\fB\-\-remove\-stateful\-disks\fR=\fIDEVICE_NAME\fR,[\fIDEVICE_NAME\fR,...]] [\fB\-\-stateful\-names\fR] [\fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute instance\-groups managed update\fR allows
to update StatefulPolicy for a managed instance group. Stateful Policy defines
what stateful resources should be preserved for the group. When instances in the
group are removed or recreated, those stateful properties are always applied to
them. This command allows to change the preserved resources by adding more disks
or removing existing disks and to turn on and off preserving instance names.

Example:

.RS 2m
$ gcloud alpha compute instance\-groups managed update \e
    example\-group \-\-add\-stateful\-disks my\-disk\-1,my\-disk\-2 \e
\-\-remove\-stateful\-disks my\-disk\-0
.RE

will for each instance mark disk \f5my\-disk\-0\fR as not stateful and disks
\f5my\-disk\-1\fR and \f5my\-disk\-2\fR as stateful. That means that disks
\f5my\-disk\-1\fR and \f5my\-disk\-2\fR will be preserved when the instances get
recreated or restarted, while disk \f5my\-disk\-0\fR will not be preserved
anymore.

When there are any disks marked as stateful, the instances automatically will be
assigned stateful names as well. You cannot turn off stateful names without
marking all disks as non\-stateful.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the managed instance group to update.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-add\-stateful\-disks\fR=\fIDEVICE_NAME\fR,[\fIDEVICE_NAME\fR,...]
Add more disks to be considered stateful by the instance group. Usually, the
managed instance group deletes disks when deleting instances; however, in the
case of stateful disks, these disks are detached from the deleted instance and
attached to new instances the managed instance group creates.

.TP 2m
\fB\-\-instance\-redistribution\-type\fR=\fITYPE\fR
Specify type of instance redistribution policy. Instance redistribution type
gives possibility to enable or disable automatic instance redistribution between
zones to its target distribution. Target distribution is a state of regional
managed instance group where all instances are spread out equally between all
target zones.

Instance redistribution type may be specified for non\-autoscaled regional
managed instance group only. By default it is set to PROACTIVE.

The following types are available:

.RS 2m
.IP "\(em" 2m
NONE \- managed instance group will not take any action to bring instances to
its target distribution.

.IP "\(em" 2m
PROACTIVE \- managed instance group will actively converge all instances between
zones to its target distribution.

.RE
.RE
.sp
\fITYPE\fR must be one of: \fBNONE\fR, \fBPROACTIVE\fR.

.RS 2m
.TP 2m
\fB\-\-remove\-stateful\-disks\fR=\fIDEVICE_NAME\fR,[\fIDEVICE_NAME\fR,...]
Stop considering the disks stateful by the instance group.

.TP 2m
\fB\-\-stateful\-names\fR
Enable stateful names of instances. Whenever instances with those names are
restarted or recreated, they will have the same names as before. Use
\-\-no\-stateful\-names to disable stateful names.

.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the managed instance group to update. If not specified, you may be
prompted to select a region.

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

Overrides the default \fBcompute/region\fR property value for this command
invocation.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone of the managed instance group to update. If not specified, you may be
prompted to select a zone.

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE

Overrides the default \fBcompute/zone\fR property value for this command
invocation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/.

