
.TH "GCLOUD_ACTIVE\-DIRECTORY" 1



.SH "NAME"
.HP
gcloud active\-directory \- manage Managed Microsoft AD resources



.SH "SYNOPSIS"
.HP
\f5gcloud active\-directory\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Managed Microsoft AD resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdomains\fR
Manage Managed Microsoft AD domains.

.TP 2m
\fBoperations\fR
Manage Managed Microsoft AD operations.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha active\-directory
$ gcloud beta active\-directory
.RE

