
.TH "GCLOUD_BETA_SQL_RESCHEDULE\-MAINTENANCE" 1



.SH "NAME"
.HP
gcloud beta sql reschedule\-maintenance \- reschedule a Cloud SQL instance's maintenance



.SH "SYNOPSIS"
.HP
\f5gcloud beta sql reschedule\-maintenance\fR \fIINSTANCE\fR \fB\-\-reschedule\-type\fR=\fIRESCHEDULE_TYPE\fR [\fB\-\-schedule\-time\fR=\fISCHEDULE_TIME\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR gcloud beta sql reschedule\-maintenance reschedules a Cloud SQL
instance's maintenance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-reschedule\-type\fR=\fIRESCHEDULE_TYPE\fR
The type of reschedule operation to perform. \fIRESCHEDULE_TYPE\fR must be one
of: \fBIMMEDIATE\fR, \fBNEXT_AVAILABLE_WINDOW\fR, \fBSPECIFIC_TIME\fR.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-schedule\-time\fR=\fISCHEDULE_TIME\fR
When specifying SPECIFIC_TIME, the date and time at which to schedule the
maintenance in ISO 8601 format.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To run maintenance on instance \f5my\-instance\fR immediately, run:

.RS 2m
$ gcloud beta sql reschedule\-maintenance my\-instance \e
    \-\-reschedule\-type=IMMEDIATE
.RE

To reschedule maintenance on instance \f5my\-instance\fR to the next available
window, run:

.RS 2m
$ gcloud beta sql reschedule\-maintenance my\-instance \e
    \-\-reschedule\-type=NEXT_AVAILABLE_WINDOW
.RE

To reschedule maintenance on instance \f5my\-instance\fR to 2019\-11\-07 at 4:00
am UTC, run:

.RS 2m
$ gcloud beta sql reschedule\-maintenance my\-instance \e
    \-\-reschedule\-type=SPECIFIC_TIME \e
    \-\-schedule\-time=2019\-11\-07T04:00Z
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud sql reschedule\-maintenance
$ gcloud alpha sql reschedule\-maintenance
.RE

