
.TH "GCLOUD_BETA_KMS_KEYRINGS" 1



.SH "NAME"
.HP
gcloud beta kms keyrings \- create and manage keyrings



.SH "SYNOPSIS"
.HP
\f5gcloud beta kms keyrings\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR A keyring is a toplevel logical grouping of keys.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
\fB(BETA)\fR Add IAM policy binding for a kms keyring.

.TP 2m
\fBcreate\fR
\fB(BETA)\fR Create a new keyring.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Get metadata for a keyring.

.TP 2m
\fBget\-iam\-policy\fR
\fB(BETA)\fR Get the IAM policy for a keyring.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List keyrings within a location.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
\fB(BETA)\fR Remove IAM policy binding for a kms keyring.

.TP 2m
\fBset\-iam\-policy\fR
\fB(BETA)\fR Set the IAM policy for a keyring.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud kms keyrings
$ gcloud alpha kms keyrings
.RE

