
.TH "GCLOUD_BETA_SPANNER_OPERATIONS_CANCEL" 1



.SH "NAME"
.HP
gcloud beta spanner operations cancel \- cancel a Cloud Spanner operation



.SH "SYNOPSIS"
.HP
\f5gcloud beta spanner operations cancel\fR \fIOPERATION\-ID\fR \fB\-\-instance\fR=\fIINSTANCE\fR [\fB\-\-database\fR=\fIDATABASE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Cancel a Cloud Spanner operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\-ID\fR
ID of the operation


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR
The ID of the instance the operation is executing on.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-database\fR=\fIDATABASE\fR
For a database operation, the name of the database the operation is executing
on.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To cancel an instance operation with ID \fIauto_12345, run:

.RS 2m
$ gcloud beta spanner operations cancel _auto_12345 \e
    \-\-instance=my\-instance\-id
.RE

To cancel a database operation with ID \fRauto_12345, run:

.RS 2m
$ gcloud beta spanner operations cancel  _auto_12345 \e
    \-\-instance=my\-instance\-id
    \-\-database=my\-database\-id
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud spanner operations cancel
$ gcloud alpha spanner operations cancel
.RE

