
.TH "GCLOUD_BETA_ML_VISION_PRODUCT\-SEARCH_PRODUCTS" 1



.SH "NAME"
.HP
gcloud beta ml vision product\-search products \- uses Google Cloud Vision to manipulate products



.SH "SYNOPSIS"
.HP
\f5gcloud beta ml vision product\-search products\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Uses Google Cloud Vision to manipulate products.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(BETA)\fR create a product.

.TP 2m
\fBdelete\fR
\fB(BETA)\fR delete a product.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR describe a product.

.TP 2m
\fBlist\fR
\fB(BETA)\fR list all products in a location.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR update a product.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha ml vision product\-search products
.RE

