
.TH "GCLOUD_ALPHA_SOURCE_PROJECT\-CONFIGS" 1



.SH "NAME"
.HP
gcloud alpha source project\-configs \- manage Cloud Source Repositories configuration of a project



.SH "SYNOPSIS"
.HP
\f5gcloud alpha source project\-configs\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Source Repositories configuration of a project.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Show details about the configuration of a project.

.TP 2m
\fBupdate\fR
\fB(ALPHA)\fR Update the Cloud Source Repositories configuration of the current
project.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. These variants are also available:

.RS 2m
$ gcloud source project\-configs
$ gcloud beta source project\-configs
.RE

