
.TH "GCLOUD_ALPHA_EMULATORS_DATASTORE_ENV\-UNSET" 1



.SH "NAME"
.HP
gcloud alpha emulators datastore env\-unset \- print the commands required to unset a datastore emulators env variables



.SH "SYNOPSIS"
.HP
\f5gcloud alpha emulators datastore env\-unset\fR [\fB\-\-data\-dir\fR=\fIDATA_DIR\fR] [\fB\-\-legacy\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Print the commands required to unset a datastore emulators env
variables.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-data\-dir\fR=\fIDATA_DIR\fR
The directory to be used to store/retrieve data/config for an emulator run. The
default value is \f5<USER_CONFIG_DIR>/emulators/datastore\fR. The value of
USER_CONFIG_DIR can be found by running:

.RS 2m
$ gcloud info \-\-format='get(config.paths.global_config_dir)'
.RE

.TP 2m
\fB\-\-legacy\fR
(DEPRECATED) Set to use the legacy emulator which supports Cloud Datastore API
v1beta2.

This flag is deprecated due to the legacy Datastore emulator no longer being
supported. It will be removed in early October 2019.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To print the commands necessary to unset the env variables for a datastore
emulator, run:

.RS 2m
$ gcloud alpha emulators datastore env\-unset \-\-data\-dir DATA\-DIR
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. This variant is also available:

.RS 2m
$ gcloud beta emulators datastore env\-unset
.RE

