
.TH "GCLOUD_ACCESS\-CONTEXT\-MANAGER" 1



.SH "NAME"
.HP
gcloud access\-context\-manager \- manage Access Context Manager resources



.SH "SYNOPSIS"
.HP
\f5gcloud access\-context\-manager\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Policy API for configuring context aware access features and access zones.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlevels\fR
Manage Access Context Manager levels.

.TP 2m
\fBperimeters\fR
Manage Access Context Manager service perimeters.

.TP 2m
\fBpolicies\fR
Manage Access Context Manager policies.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha access\-context\-manager
$ gcloud beta access\-context\-manager
.RE

