
.TH "GCLOUD_ALPHA_COMPUTE_PACKET\-MIRRORINGS_DELETE" 1



.SH "NAME"
.HP
gcloud alpha compute packet\-mirrorings delete \- delete a Google Compute Engine packet mirroring



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute packet\-mirrorings delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Delete a Google Compute Engine Packet Mirroring



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
Names of the packet mirrorings to delete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the packet mirrorings to delete. Overrides the default
\fBcompute/region\fR property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

Delete the Packet Mirroring resource pm\-1 in region us\-central1.

.RS 2m
$ gcloud alpha compute packet\-mirrorings delete pm\-1
  \-\-region us\-central1
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. This variant is also available:

.RS 2m
$ gcloud beta compute packet\-mirrorings delete
.RE

