
.TH "GCLOUD_COMPUTE_OS\-LOGIN_DESCRIBE\-PROFILE" 1



.SH "NAME"
.HP
gcloud compute os\-login describe\-profile \- describe the OS Login profile for the current user



.SH "SYNOPSIS"
.HP
\f5gcloud compute os\-login describe\-profile\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute os\-login describe\-profile\fR displays the OS Login profile
for the currently authenticated user, including Posix accounts and SSH keys
associated with the user.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute os\-login describe\-profile
$ gcloud beta compute os\-login describe\-profile
.RE

