
.TH "GCLOUD_ALPHA_HEALTHCARE_DICOM\-STORES_DELETE" 1



.SH "NAME"
.HP
gcloud alpha healthcare dicom\-stores delete \- delete a Cloud Healthcare API DICOM store



.SH "SYNOPSIS"
.HP
\f5gcloud alpha healthcare dicom\-stores delete\fR (\fIDICOM_STORE\fR\ :\ \fB\-\-dataset\fR=\fIDATASET\fR\ \fB\-\-location\fR=\fILOCATION\fR) [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Delete a Cloud Healthcare API DICOM store.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

DicomStore resource \- Cloud Healthcare API DICOM store to delete. The arguments
in this group can be used to specify the attributes of this resource. (NOTE)
Some attributes are not given arguments in this group but can be set in other
ways. To set the [project] attribute: provide the argument [dicom_store] on the
command line with a fully specified name; provide the argument [\-\-project] on
the command line; set the property [core/project]. This must be specified.

.RS 2m
.TP 2m
\fIDICOM_STORE\fR
ID of the dicomStore or fully qualified identifier for the dicomStore. This
positional must be specified if any of the other arguments in this group are
specified.

.TP 2m
\fB\-\-dataset\fR=\fIDATASET\fR
Cloud Healthcare dataset.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
Google Cloud location.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBhealthcare/v1alpha2\fR API. The full documentation for
this API can be found at: https://cloud.google.com/healthcare



.SH "EXAMPLES"

To delete the dicom\-store 'test\-dicom\-store', run:

.RS 2m
$ gcloud alpha healthcare dicom\-stores delete test\-dicom\-store \e
    \-\-dataset=test\-dataset
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. These variants are also available:

.RS 2m
$ gcloud healthcare dicom\-stores delete
$ gcloud beta healthcare dicom\-stores delete
.RE

