
.TH "GCLOUD_FIRESTORE" 1



.SH "NAME"
.HP
gcloud firestore \- manage your Cloud Firestore resources



.SH "SYNOPSIS"
.HP
\f5gcloud firestore\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage your Cloud Firestore resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBindexes\fR
Manage indexes for Cloud Firestore.

.TP 2m
\fBoperations\fR
Manage Long Running Operations for Cloud Firestore.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBexport\fR
export Cloud Firestore documents to Google Cloud Storage.

.TP 2m
\fBimport\fR
import Cloud Firestore documents from Google Cloud Storage.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha firestore
$ gcloud beta firestore
.RE

