
.TH "GCLOUD_ALPHA_COMPUTE_INSTANCES_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud alpha compute instances set\-iam\-policy \- set IAM policy for an instance



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute instances set\-iam\-policy\fR \fIINSTANCE_NAME\fR \fIPOLICY_FILE\fR [\fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute instances set\-iam\-policy\fR sets the IAM
Policy associated with a Google Compute Engine instance in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE_NAME\fR
Name of the instance to set the IAM policy of.

.TP 2m
\fIPOLICY_FILE\fR
JSON or YAML file containing the IAM policy.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
Zone of the instance to set the IAM policy of. If not specified, you may be
prompted to select a zone. \f5gcloud\fR will attempt to identify the zone by
searching for resources in your project. If the zone cannot be determined, you
will then be prompted with all Google Cloud Platform zones.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/zone\fR\fR property:

.RS 2m
$ gcloud config set compute/zone ZONE
.RE

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/zone
.RE

Alternatively, the zone can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_ZONE\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "EXAMPLES"

The following command will read an IAM policy defined in a JSON file
\'policy.json' and set it for an instance with identifier 'my\-instance'

.RS 2m
$ gcloud alpha compute instances set\-iam\-policy my\-instance \e
    policy.json
.RE


See https://cloud.google.com/iam/docs/managing\-policies for details of the
policy file format and contents.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta compute instances set\-iam\-policy
.RE

