
.TH "GCLOUD_BETA_RUNTIME\-CONFIG_CONFIGS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta runtime\-config configs describe \- describe runtime\-config resources



.SH "SYNOPSIS"
.HP
\f5gcloud beta runtime\-config configs describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR This command displays information about the runtime\-config
resource with the specified name.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The runtime\-config resource name.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "EXAMPLES"

To describe a runtime\-config resource named "my\-config", run:

.RS 2m
$ gcloud beta runtime\-config configs describe my\-config
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice.

