
.TH "GCLOUD_FIRESTORE_INDEXES" 1



.SH "NAME"
.HP
gcloud firestore indexes \- manage indexes for Cloud Firestore



.SH "SYNOPSIS"
.HP
\f5gcloud firestore indexes\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage indexes for Cloud Firestore.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcomposite\fR
Manage composite indexes for Cloud Firestore.

.TP 2m
\fBfields\fR
Manage single\-field indexes for Cloud Firestore.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha firestore indexes
$ gcloud beta firestore indexes
.RE

