
.TH "GCLOUD_BETA_IAM_SERVICE\-ACCOUNTS_DISABLE" 1



.SH "NAME"
.HP
gcloud beta iam service\-accounts disable \- disable an IAM service account



.SH "SYNOPSIS"
.HP
\f5gcloud beta iam service\-accounts disable\fR \fISERVICE_ACCOUNT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Disable an IAM service account. After the service account is
disabled, credential generation and API requests using this service account will
fail. Using \f5gcloud iam service\-accounts enable\fR to re\-enable it.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

ServiceAccount resource \- The IAM service account to disable. This represents a
Cloud resource. (NOTE) Some attributes are not given arguments in this group but
can be set in other ways. To set the [project] attribute: provide the argument
[service_account] on the command line with a fully specified name; set the
property [core/project]; provide the argument [\-\-project] on the command line.
This must be specified.

.RS 2m
.TP 2m
\fISERVICE_ACCOUNT\fR
ID of the serviceAccount or fully qualified identifier for the serviceAccount.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBiam/v1\fR API. The full documentation for this API can
be found at: https://cloud.google.com/iam/



.SH "EXAMPLES"

To disable a service account from your project, run:

.RS 2m
$ gcloud beta iam service\-accounts disable \e
    my\-iam\-account@somedomain.com
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud iam service\-accounts disable
$ gcloud alpha iam service\-accounts disable
.RE

