
.TH "GCLOUD_BETA_DATAPROC_JOBS_KILL" 1



.SH "NAME"
.HP
gcloud beta dataproc jobs kill \- kill an active job



.SH "SYNOPSIS"
.HP
\f5gcloud beta dataproc jobs kill\fR \fIJOB\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Kill an active job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB\fR
The ID of the job to kill.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Cloud Dataproc region to use. Each Cloud Dataproc region constitutes an
independent resource namespace constrained to deploying instances into Compute
Engine zones inside the region. The default value of \f5global\fR is a special
multi\-region namespace which is capable of deploying instances into all Compute
Engine zones globally, and is disjoint from other Cloud Dataproc regions.
Overrides the default \fBdataproc/region\fR property value for this command
invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To cancel a job, run:

.RS 2m
$ gcloud beta dataproc jobs kill job_id
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud dataproc jobs kill
.RE

