
.TH "GCLOUD_REDIS_INSTANCES" 1



.SH "NAME"
.HP
gcloud redis instances \- manage Cloud Memorystore Redis instances



.SH "SYNOPSIS"
.HP
\f5gcloud redis instances\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a Memorystore Redis instance.

.TP 2m
\fBdelete\fR
Delete a Redis instance.

.TP 2m
\fBdescribe\fR
Show metadata for a Memorystore Redis instance.

.TP 2m
\fBexport\fR
Export data from a Memorystore Redis instance to Google Cloud Storage.

.TP 2m
\fBfailover\fR
Failover a standard tier Cloud Memorystore for Redis instance from the master
node to its replica.

.TP 2m
\fBimport\fR
Import data to a Memorystore Redis instance from Google Cloud Storage.

.TP 2m
\fBlist\fR
List Memorystore Redis instances.

.TP 2m
\fBupdate\fR
Update Memorystore Redis instances.

.TP 2m
\fBupgrade\fR
Upgrade a Memorystore for Redis instance to a specified Redis version.


.RE
.sp

.SH "EXAMPLES"

To create an instance with the name \f5my\-redis\-instance\fR, run:

.RS 2m
$ gcloud redis instances create my\-redis\-instance
.RE

To delete an instance with the name \f5my\-redis\-instance\fR, run:

.RS 2m
$ gcloud redis instances delete my\-redis\-instance
.RE

To display the details for an instance with the name \f5my\-redis\-instance\fR,
run:

.RS 2m
$ gcloud redis instances describe my\-redis\-instance
.RE

To list all the instances, run:

.RS 2m
$ gcloud redis instances list
.RE

To set the label \f5env\fR to \f5prod\fR for an instance with the name
\f5my\-redis\-instance\fR, run:

.RS 2m
$ gcloud redis instances my\-redis\-instance \-\-update\-labels=env=prod
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha redis instances
$ gcloud beta redis instances
.RE

