
.TH "GCLOUD_ALPHA_SCHEDULER_JOBS" 1



.SH "NAME"
.HP
gcloud alpha scheduler jobs \- manage Cloud Scheduler jobs



.SH "SYNOPSIS"
.HP
\f5gcloud alpha scheduler jobs\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Scheduler jobs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Create Cloud Scheduler jobs for various types of targets.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdelete\fR
\fB(ALPHA)\fR Delete a job.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Show details about a job.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List jobs.

.TP 2m
\fBpause\fR
\fB(ALPHA)\fR Pause the execution of a job.

.TP 2m
\fBresume\fR
\fB(ALPHA)\fR Resume execution of a paused job.

.TP 2m
\fBrun\fR
\fB(ALPHA)\fR Trigger an on\-demand execution of a job.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta scheduler jobs
.RE

