
.TH "GCLOUD_BETA_SERVICES_VPC\-PEERINGS_LIST" 1



.SH "NAME"
.HP
gcloud beta services vpc\-peerings list \- list connections to a service via VPC peering for a project network



.SH "SYNOPSIS"
.HP
\f5gcloud beta services vpc\-peerings list\fR \fB\-\-network\fR=\fINETWORK\fR [\fB\-\-service\fR=\fISERVICE\fR;\ default="servicenetworking.googleapis.com"] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR This command lists connections of a network to a service via VPC
peering for a project.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-network\fR=\fINETWORK\fR
The network in the current project to list connections with the service


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR; default="servicenetworking.googleapis.com"
The service to list connections


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "EXAMPLES"

To list connections of a network called \f5my\-network\fR to a service called
\f5your\-service\fR, run:

.RS 2m
$ gcloud beta services vpc\-peerings list \-\-network my\-network \e
    \-\-service your\-service \e
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha services vpc\-peerings list
.RE

