
.TH "GCLOUD_ALPHA_DEPLOYMENT\-MANAGER_RESOURCES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha deployment\-manager resources describe \- provide information about a resource



.SH "SYNOPSIS"
.HP
\f5gcloud alpha deployment\-manager resources describe\fR \fIRESOURCE\fR [\fB\-\-deployment\fR=\fIDEPLOYMENT\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command prints out all available details about a resource.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIRESOURCE\fR
Resource name.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-deployment\fR=\fIDEPLOYMENT\fR
Deployment name


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To display information about a resource, run:

.RS 2m
$ gcloud alpha deployment\-manager resources describe \e
    \-\-deployment=my\-deployment my\-resource\-name
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud deployment\-manager resources describe
$ gcloud beta deployment\-manager resources describe
.RE

