
.TH "GCLOUD_BETA_DOMAINS_VERIFY" 1



.SH "NAME"
.HP
gcloud beta domains verify \- verifies a domain via an in\-browser workflow



.SH "SYNOPSIS"
.HP
\f5gcloud beta domains verify\fR \fIDOMAIN\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Verifies a domain via an in\-browser workflow.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDOMAIN\fR
The domain to be verified.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To verify a domain for the current user, run:

.RS 2m
$ gcloud beta domains verify example.com
.RE

This will allow the domain to be used with App Engine through gcloud beta
domains app domain\-mappings and across Google Cloud products.



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud domains verify
.RE

