
.TH "GCLOUD_RESOURCE\-MANAGER" 1



.SH "NAME"
.HP
gcloud resource\-manager \- manage Cloud Resources



.SH "SYNOPSIS"
.HP
\f5gcloud resource\-manager\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Commands to query and update your Cloud Organizations, Folders, and Projects.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBfolders\fR
Manage Cloud Folders.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha resource\-manager
$ gcloud beta resource\-manager
.RE

