
.TH "GCLOUD_ALPHA_COMPUTE_PROJECT\-INFO_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha compute project\-info describe \- describe the Google Compute Engine project resource



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute project\-info describe\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute project\-info describe\fR displays all
data associated with the Google Compute Engine project resource. The project
resource contains data such as global quotas, common instance metadata, and the
project's creation time.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. These variants are also available:

.RS 2m
$ gcloud compute project\-info describe
$ gcloud beta compute project\-info describe
.RE

