
.TH "GCLOUD_ALPHA_RESOURCE\-MANAGER" 1



.SH "NAME"
.HP
gcloud alpha resource\-manager \- manage Cloud Resources



.SH "SYNOPSIS"
.HP
\f5gcloud alpha resource\-manager\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Commands to query and update your Cloud Organizations, Folders,
and Projects.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBfolders\fR
\fB(ALPHA)\fR Manage Cloud Folders.

.TP 2m
\fBliens\fR
\fB(ALPHA)\fR Manage Cloud Resource Manager Liens.

.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Query Cloud Resource Manager long\-running operations.

.TP 2m
\fBorg\-policies\fR
\fB(ALPHA)\fR Manage Org Policies.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta resource\-manager
.RE

