
.TH "GCLOUD_ALPHA_ACCESS\-CONTEXT\-MANAGER_PERIMETERS_REPLACE\-ALL" 1



.SH "NAME"
.HP
gcloud alpha access\-context\-manager perimeters replace\-all \- replace all existing service perimeters



.SH "SYNOPSIS"
.HP
\f5gcloud alpha access\-context\-manager perimeters replace\-all\fR [\fIPOLICY\fR] \fB\-\-source\-file\fR=\fISOURCE_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Replace all existing service perimeter in specified access policy
with service perimeters specified in a file.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Policy resource \- The access policy that contains the perimeters you want to
replace. This represents a Cloud resource.

.RS 2m
.TP 2m
[\fIPOLICY\fR]
ID of the policy or fully qualified identifier for the policy.


.RE
.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-source\-file\fR=\fISOURCE_FILE\fR
Path to a file containing a list of service perimeters.

An service perimeter file is a YAML\-formatted list of service perimeters, which
are YAML objects representing a Condition as described in the API reference. For
example:

.RS 2m
\- name: my_perimeter
  title: My Perimeter
  description: Perimeter for foo.
  perimeterType: PERIMETER_TYPE_REGULAR
  status:
    resources:
    \- projects/0123456789
    accessLevels:
    \- accessPolicies/my_policy/accessLevels/my_level
    unrestrictedServices:
    \- "*"
    restrictedServices:
    \- storage.googleapis.com
.RE

For more information, see:
https://cloud.google.com/access\-context\-manager/docs/reference/rest/v1beta/accessPolicies.servicePerimeters


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBaccesscontextmanager/v1beta\fR API. The full
documentation for this API can be found at:
https://cloud.google.com/access\-context\-manager/docs/reference/rest/



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

