
.TH "GCLOUD_ALPHA_AUTH_CONFIGURE\-DOCKER" 1



.SH "NAME"
.HP
gcloud alpha auth configure\-docker \- register \f5gcloud\fR as a Docker credential helper



.SH "SYNOPSIS"
.HP
\f5gcloud alpha auth configure\-docker\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR gcloud alpha auth configure\-docker adds the Docker
\f5credHelper\fR entry to Docker's configuration file, or creates the file if it
doesn't exist. This will register \f5gcloud\fR as the credential helper for all
Google\-supported Docker registries. If the Docker configuration already
contains a \f5credHelper\fR entry, it will be overwritten.

Note, \f5docker\fR and \f5gcloud\fR need to be on the same system \f5PATH\fR to
work correctly.

For more details on Docker credential helpers, see
https://docs.docker.com/engine/reference/commandline/login/#credential\-helpers.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. These variants are also available:

.RS 2m
$ gcloud auth configure\-docker
$ gcloud beta auth configure\-docker
.RE

