
.TH "GCLOUD_ALPHA_COMPUTE_GROUPS_CREATE" 1



.SH "NAME"
.HP
gcloud alpha compute groups create \- create Google Compute Engine groups



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute groups create\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-description\fR=\fIDESCRIPTION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute groups create\fR creates Google Compute
Engine groups.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The name of the group to create.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-description\fR=\fIDESCRIPTION\fR
An optional, textual description for the group being created.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To create a group, run:

.RS 2m
$ gcloud alpha compute groups create example\-group
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. This variant is also available:

.RS 2m
$ gcloud beta compute groups create
.RE

