
.TH "GCLOUD_BETA_SECRETS_REPLICATION_GET" 1



.SH "NAME"
.HP
gcloud beta secrets replication get \- describe a secret's replication



.SH "SYNOPSIS"
.HP
\f5gcloud beta secrets replication get\fR \fISECRET\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Describe a secret's replication



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Secret resource \- The secret to describe. This represents a Cloud resource.
(NOTE) Some attributes are not given arguments in this group but can be set in
other ways. To set the [project] attribute: provide the argument [SECRET] on the
command line with a fully specified name; provide the argument [\-\-project] on
the command line; set the property [core/project]. This must be specified.

.RS 2m
.TP 2m
\fISECRET\fR
ID of the secret or fully qualified identifier for the secret.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To describe the replication of a secret named ``my\-secret", run:

.RS 2m
$ gcloud beta secrets replication get my\-secret
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice.

