
.TH "GCLOUD_DOMAINS_LIST\-USER\-VERIFIED" 1



.SH "NAME"
.HP
gcloud domains list\-user\-verified \- lists the user's verified domains



.SH "SYNOPSIS"
.HP
\f5gcloud domains list\-user\-verified\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Lists the user's verified domains.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To list domains that have been verified by the current user, run:

.RS 2m
$ gcloud domains list\-user\-verified list\-user\-verified
.RE

Use the gcloud domains verify command to verify additional domains.



.SH "NOTES"

This variant is also available:

.RS 2m
$ gcloud beta domains list\-user\-verified
.RE

