
.TH "GCLOUD_RECOMMENDER" 1



.SH "NAME"
.HP
gcloud recommender \- manage Cloud recommendations and recommendation rules



.SH "SYNOPSIS"
.HP
\f5gcloud recommender\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Recommender allows you to retrieve recommendations for Cloud resources, helping
you to improve security, save costs, and more. Each recommendation includes a
suggested action, its justification, and its impact. Recommendations are grouped
into a per\-resource collection. To apply a recommendation, you must use the
desired service's API, not the Recommender. Interact with and manage resources
in Cloud Recommender.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBrecommendations\fR
Manage Cloud resource recommendations.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha recommender
$ gcloud beta recommender
.RE

