
.TH "GCLOUD_HEALTHCARE_HL7V2\-STORES" 1



.SH "NAME"
.HP
gcloud healthcare hl7v2\-stores \- manage Cloud Healthcare API HL7v2 stores



.SH "SYNOPSIS"
.HP
\f5gcloud healthcare hl7v2\-stores\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Healthcare API HL7v2 stores.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add an IAM policy binding to a Cloud Healthcare API HL7v2 store.

.TP 2m
\fBcreate\fR
Create a Cloud Healthcare API HL7v2 store.

.TP 2m
\fBdelete\fR
Delete a Cloud Healthcare API HL7v2 store.

.TP 2m
\fBdescribe\fR
Describe a Cloud Healthcare API HL7v2 store.

.TP 2m
\fBget\-iam\-policy\fR
Retrieve the IAM policy for a Cloud Healthcare API HL7v2 store.

.TP 2m
\fBlist\fR
List Cloud Healthcare API HL7v2 stores.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove an IAM policy binding from a Cloud Healthcare API HL7v2 store.

.TP 2m
\fBset\-iam\-policy\fR
Set the IAM policy for a Cloud Healthcare API HL7v2 store.

.TP 2m
\fBupdate\fR
Create a Cloud Healthcare API HL7v2 store.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha healthcare hl7v2\-stores
$ gcloud beta healthcare hl7v2\-stores
.RE

