
.TH "GCLOUD_BETA_BILLING" 1



.SH "NAME"
.HP
gcloud beta billing \- manage billing accounts and associate them with projects



.SH "SYNOPSIS"
.HP
\f5gcloud beta billing\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage billing accounts and associate them with projects.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBaccounts\fR
\fB(BETA)\fR Manage billing accounts.

.TP 2m
\fBprojects\fR
\fB(BETA)\fR Manage the billing account configuration of your projects.


.RE
.sp

.SH "EXAMPLES"

To list billing accounts associated with the current user, run:

.RS 2m
$ gcloud beta billing accounts list
.RE

To link one of the billing accounts \f50X0X0X\-0X0X0X\-0X0X0X\fR with a project
\f5my\-project\fR, run:

.RS 2m
$ gcloud beta billing projects link my\-project \e
    \-\-billing\-account 0X0X0X\-0X0X0X\-0X0X0X
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha billing
.RE

