
.TH "GCLOUD_ALPHA_DIALOGFLOW" 1



.SH "NAME"
.HP
gcloud alpha dialogflow \- interact with and manage Dialogflow agents, entities, and intents



.SH "SYNOPSIS"
.HP
\f5gcloud alpha dialogflow\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Interact with and manage Dialogflow agents, entities, and intents.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBagent\fR
\fB(ALPHA)\fR Manage, train, and query the Dialogflow agent for a project.

.TP 2m
\fBentity\-types\fR
\fB(ALPHA)\fR Create, list, describe, update, and delete Dialogflow entity
types.

.TP 2m
\fBintents\fR
\fB(ALPHA)\fR Create, list, describe, and delete Dialogflow intents.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

