
.TH "GCLOUD_BETA_FIRESTORE" 1



.SH "NAME"
.HP
gcloud beta firestore \- manage your Cloud Firestore imports and exports



.SH "SYNOPSIS"
.HP
\f5gcloud beta firestore\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage your Cloud Firestore imports and exports.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBindexes\fR
\fB(BETA)\fR Manage indexes for Cloud Firestore.

.TP 2m
\fBoperations\fR
\fB(BETA)\fR Manage Long Running Operations for Cloud Firestore.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBexport\fR
\fB(BETA)\fR export Cloud Firestore documents to Google Cloud Storage.

.TP 2m
\fBimport\fR
\fB(BETA)\fR import Cloud Firestore documents from Google Cloud Storage.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha firestore
.RE

