
.TH "GCLOUD_BETA_IDENTITY_GROUPS" 1



.SH "NAME"
.HP
gcloud beta identity groups \- manage Cloud Identity Groups



.SH "SYNOPSIS"
.HP
\f5gcloud beta identity groups\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Commands for managing Cloud Identity Groups.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBmemberships\fR
\fB(BETA)\fR Manage Cloud Identity Groups Memberships.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(BETA)\fR Create a new group.

.TP 2m
\fBdelete\fR
\fB(BETA)\fR Delete an existing group.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe an existing group.

.TP 2m
\fBpreview\fR
\fB(BETA)\fR Retrieve a list of users in a customer account using CEL query.

.TP 2m
\fBsearch\fR
\fB(BETA)\fR Search groups.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR Update a group.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud identity groups
$ gcloud alpha identity groups
.RE

