
.TH "GCLOUD_BETA_ML\-ENGINE_OPERATIONS" 1



.SH "NAME"
.HP
gcloud beta ml\-engine operations \- manage AI Platform operations



.SH "SYNOPSIS"
.HP
\f5gcloud beta ml\-engine operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage AI Platform operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcancel\fR
\fB(BETA)\fR Cancel an AI Platform operation.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe an AI Platform operation.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List existing AI Platform jobs.

.TP 2m
\fBwait\fR
\fB(BETA)\fR Wait for an AI Platform operation to complete.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud ml\-engine operations
$ gcloud alpha ml\-engine operations
.RE

