
.TH "GCLOUD_ALPHA_MONITORING" 1



.SH "NAME"
.HP
gcloud alpha monitoring \- manage Stackdriver Monitoring alerting policies and notification channels



.SH "SYNOPSIS"
.HP
\f5gcloud alpha monitoring\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Stackdriver Monitoring alerting policies and notification
channels.

More information can be found here: https://cloud.google.com/monitoring/api/v3/



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBchannel\-descriptors\fR
\fB(ALPHA)\fR Read Stackdriver Monitoring notification channel descriptors.

.TP 2m
\fBchannels\fR
\fB(ALPHA)\fR Manage Stackdriver Monitoring notification channels.

.TP 2m
\fBpolicies\fR
\fB(ALPHA)\fR Manage Stackdriver Monitoring alerting policies.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/.

