
.TH "GCLOUD_COMPUTE_SSL\-CERTIFICATES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute ssl\-certificates describe \- describe a Google Compute Engine SSL certificate



.SH "SYNOPSIS"
.HP
\f5gcloud compute ssl\-certificates describe\fR \fINAME\fR [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute ssl\-certificates describe\fR displays all data (except
private keys) associated with Google Compute Engine SSL certificate in a
project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the SSL certificate to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
(Default) If set, the SSL certificate is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the SSL certificate to describe. If not specified, you may be prompted
to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To display a description of a certificate 'my\-cert', run:

.RS 2m
$ gcloud compute ssl\-certificates describe my\-cert
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute ssl\-certificates describe
$ gcloud beta compute ssl\-certificates describe
.RE

