
.TH "GCLOUD_BIGTABLE_INSTANCES_DELETE" 1



.SH "NAME"
.HP
gcloud bigtable instances delete \- delete an existing Bigtable instance



.SH "SYNOPSIS"
.HP
\f5gcloud bigtable instances delete\fR \fIINSTANCE\fR [\fIINSTANCE\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete an existing Bigtable instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Instance resource \- The instances to delete. This represents a Cloud resource.
(NOTE) Some attributes are not given arguments in this group but can be set in
other ways. To set the [project] attribute: provide the argument [instance] on
the command line with a fully specified name; provide the argument [\-\-project]
on the command line; set the property [core/project]. This must be specified.

.RS 2m
.TP 2m
\fIINSTANCE\fR [\fIINSTANCE\fR ...]
IDs of the instances or fully qualified identifiers for the instances.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To delete an instance, run:

.RS 2m
$ gcloud bigtable instances delete my\-instance\-id
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha bigtable instances delete
$ gcloud beta bigtable instances delete
.RE

