
.TH "GCLOUD_ALPHA_CONTAINER_BUILDS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha container builds describe \- get information about a particular build



.SH "SYNOPSIS"
.HP
\f5gcloud alpha container builds describe\fR \fIBUILD\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Get information about a particular build.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBUILD\fR
The build to describe. The ID of the build is printed at the end of the build
submission process, or in the ID column when listing builds.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. These variants are also available:

.RS 2m
$ gcloud container builds describe
$ gcloud beta container builds describe
.RE

