
.TH "GCLOUD_ALPHA_DLP_JOB\-TRIGGERS" 1



.SH "NAME"
.HP
gcloud alpha dlp job\-triggers \- cloud DLP commands for creating and managing Cloud DLP job triggers



.SH "SYNOPSIS"
.HP
\f5gcloud alpha dlp job\-triggers\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Job triggers contain configurations to run Cloud DLP jobs on a set
schedule.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Creates a Cloud DLP job trigger.

.TP 2m
\fBdelete\fR
\fB(ALPHA)\fR Delete a Cloud DLP job trigger.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Get the latest status of a Cloud DLP job trigger.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Cloud DLP job triggers.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/.

