
.TH "GCLOUD_BETA_PUBSUB_SUBSCRIPTIONS_UPDATE" 1



.SH "NAME"
.HP
gcloud beta pubsub subscriptions update \- updates an existing Cloud Pub/Sub subscription



.SH "SYNOPSIS"
.HP
\f5gcloud beta pubsub subscriptions update\fR \fISUBSCRIPTION\fR [\fB\-\-ack\-deadline\fR=\fIACK_DEADLINE\fR] [\fB\-\-expiration\-period\fR=\fIEXPIRATION_PERIOD\fR] [\fB\-\-message\-retention\-duration\fR=\fIMESSAGE_RETENTION_DURATION\fR] [\fB\-\-push\-auth\-service\-account\fR=\fISERVICE_ACCOUNT_EMAIL\fR] [\fB\-\-push\-auth\-token\-audience\fR=\fIOPTIONAL_AUDIENCE_OVERRIDE\fR] [\fB\-\-push\-endpoint\fR=\fIPUSH_ENDPOINT\fR] [\fB\-\-retain\-acked\-messages\fR] [\fB\-\-update\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...]] [\fB\-\-clear\-labels\fR\ |\ \fB\-\-remove\-labels\fR=[\fIKEY\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Updates an existing Cloud Pub/Sub subscription.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Subscription resource \- Name of the subscription to update. This represents a
Cloud resource. (NOTE) Some attributes are not given arguments in this group but
can be set in other ways. To set the [project] attribute: provide the argument
[subscription] on the command line with a fully specified name; provide the
argument [\-\-project] on the command line; set the property [core/project].
This must be specified.

.RS 2m
.TP 2m
\fISUBSCRIPTION\fR
ID of the subscription or fully qualified identifier for the subscription.


.RE
.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-ack\-deadline\fR=\fIACK_DEADLINE\fR
The number of seconds the system will wait for a subscriber to acknowledge
receiving a message before re\-attempting delivery.

.TP 2m
\fB\-\-expiration\-period\fR=\fIEXPIRATION_PERIOD\fR
The subscription will expire if it is inactive for the given period. Valid
values are strings of the form INTEGER[UNIT], where UNIT is one of "s", "m",
"h", and "d" for seconds, minutes, hours, and days, respectively. If the unit is
omitted, seconds is assumed. This flag additionally accepts the special value
"never" to indicate that the subscription will never expire.

.TP 2m
\fB\-\-message\-retention\-duration\fR=\fIMESSAGE_RETENTION_DURATION\fR
How long to retain unacknowledged messages in the subscription's backlog, from
the moment a message is published. If \-\-retain\-acked\-messages is true, this
also configures the retention of acknowledged messages. Specify "default" to use
the default value. Valid values are strings of the form INTEGER[UNIT], where
UNIT is one of "s", "m", "h", and "d" for seconds, minutes, hours, and days,
respectively. If the unit is omitted, seconds is assumed.

.TP 2m
\fB\-\-push\-auth\-service\-account\fR=\fISERVICE_ACCOUNT_EMAIL\fR
Service account email used as the identity for the generated Open ID Connect
token for authenticated push.

.TP 2m
\fB\-\-push\-auth\-token\-audience\fR=\fIOPTIONAL_AUDIENCE_OVERRIDE\fR
Audience used in the generated Open ID Connect token for authenticated push. If
not specified, it will be set to the push\-endpoint.

.TP 2m
\fB\-\-push\-endpoint\fR=\fIPUSH_ENDPOINT\fR
A URL to use as the endpoint for this subscription. This will also automatically
set the subscription type to PUSH.

.TP 2m
\fB\-\-retain\-acked\-messages\fR
Whether or not to retain acknowledged messages. If true, messages are not
expunged from the subscription's backlog until they fall out of the
\-\-message\-retention\-duration window. Acknowledged messages are not retained
by default.

.TP 2m
\fB\-\-update\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...]
List of label KEY=VALUE pairs to update. If a label exists its value is
modified, otherwise a new label is created.

Keys must start with a lowercase character and contain only hyphens (\f5\-\fR),
underscores (\f5_\fR), lowercase characters, and numbers. Values must contain
only hyphens (\f5\-\fR), underscores (\f5_\fR), lowercase characters, and
numbers.

.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-clear\-labels\fR
Remove all labels. If \f5\-\-update\-labels\fR is also specified then
\f5\-\-clear\-labels\fR is applied first.

For example, to remove all labels:

.RS 2m
$ gcloud beta pubsub subscriptions update \-\-clear\-labels
.RE

To set the labels to exactly "foo" and "baz":

.RS 2m
$ gcloud beta pubsub subscriptions update \-\-clear\-labels \e
  \-\-update\-labels foo=bar,baz=qux
.RE

.TP 2m
\fB\-\-remove\-labels\fR=[\fIKEY\fR,...]
List of label keys to remove. If a label does not exist it is silently ignored.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud pubsub subscriptions update
$ gcloud alpha pubsub subscriptions update
.RE

