
.TH "GCLOUD_COMPUTE_OS\-LOGIN_REMOVE\-PROFILE" 1



.SH "NAME"
.HP
gcloud compute os\-login remove\-profile \- remove the posix account information for the current user



.SH "SYNOPSIS"
.HP
\f5gcloud compute os\-login remove\-profile\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute os\-login remove\-profile\fR removes the posix account
information for the current user where the account ID field is set to the
current project ID. Posix account entries for G Suite users do not set the
account ID field and can only be modified by a domain administrator.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute os\-login remove\-profile
$ gcloud beta compute os\-login remove\-profile
.RE

