
.TH "GCLOUD_ALPHA_MONITORING_CHANNELS_DELETE" 1



.SH "NAME"
.HP
gcloud alpha monitoring channels delete \- delete a notification channel



.SH "SYNOPSIS"
.HP
\f5gcloud alpha monitoring channels delete\fR \fICHANNEL\fR [\fB\-\-force\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Delete a notification channel.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

CHANNEL \- The notification channel to delete. This represents a Cloud resource.
(NOTE) Some attributes are not given arguments in this group but can be set in
other ways. To set the [project] attribute: Set the property [core/project] or
provide the flag [\-\-project] on the command line. This must be specified.

.RS 2m
.TP 2m
\fICHANNEL\fR
The ID of the notification_channel or a fully qualified identifier for the
notification_channel.


.RE
.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-force\fR
If true, the notification channel will be deleted regardless of its use in
alerting policies (the policies will be updated to remove the channel).


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBmonitoring/v3\fR API. The full documentation for this
API can be found at: https://cloud.google.com/monitoring/api/



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/.

