
.TH "GCLOUD_ALPHA_CONTAINER_BINAUTHZ_POLICY_IMPORT" 1



.SH "NAME"
.HP
gcloud alpha container binauthz policy import \- import a Binary Authorization policy to the current project



.SH "SYNOPSIS"
.HP
\f5gcloud alpha container binauthz policy import\fR \fIPOLICY_FILE\fR [\fB\-\-strict\-validation\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command accepts a description of the desired policy in the
form of a YAML\-formatted file. A representation of the current policy can be
retrieved using the $ gcloud alpha container binauthz policy describe command.
One method of modifying the policy is to run gcloud alpha container binauthz
policy export, dump the contents to a file, modify them to reflect the desired
end\-state, and provide this modifyied file to gcloud alpha container binauthz
policy import.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPOLICY_FILE\fR
The file containing the YAML\-formatted policy description.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-strict\-validation\fR
Whether to perform additional checks on the validity of policy contents.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "EXAMPLE"

One way of updating the current project's policy is to run:

.RS 2m
$ gcloud alpha container binauthz policy export > my_policy.yaml
$ edit my_policy.yaml
$ gcloud alpha container binauthz policy import \e
  \-\-policy\-file=my_policy.yaml
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta container binauthz policy import
.RE

