
.TH "GCLOUD_DATA\-CATALOG_ENTRY\-GROUPS" 1



.SH "NAME"
.HP
gcloud data\-catalog entry\-groups \- manage entry groups in Cloud Data Catalog



.SH "SYNOPSIS"
.HP
\f5gcloud data\-catalog entry\-groups\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage entry groups in Cloud Data Catalog.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add an IAM policy binding to a Cloud Data Catalog entry group.

.TP 2m
\fBcreate\fR
Create a Cloud Data Catalog entry group.

.TP 2m
\fBdelete\fR
Delete a Cloud Data Catalog entry group.

.TP 2m
\fBdescribe\fR
Describe a Cloud Data Catalog entry group.

.TP 2m
\fBget\-iam\-policy\fR
Get the IAM policy for a Cloud Data Catalog entry group.

.TP 2m
\fBlist\fR
List all entry groups in a Cloud Data Catalog location.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove an IAM policy binding from a Cloud Data Catalog entry group.

.TP 2m
\fBset\-iam\-policy\fR
Set the IAM policy for a Cloud Data Catalog entry group.

.TP 2m
\fBupdate\fR
Update a Cloud Data Catalog entry group.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha data\-catalog entry\-groups
$ gcloud beta data\-catalog entry\-groups
.RE

