
.TH "GCLOUD_BETA_APP_SERVICES_UPDATE" 1



.SH "NAME"
.HP
gcloud beta app services update \- update service\-level settings



.SH "SYNOPSIS"
.HP
\f5gcloud beta app services update\fR [\fISERVICES\fR\ ...] \fB\-\-ingress\fR=\fIINGRESS\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR At present, this command is only used to update ingress traffic
settings for an app.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
[\fISERVICES\fR ...]
The services to modify.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-ingress\fR=\fIINGRESS\fR
Control what traffic can reach the app. \fIINGRESS\fR must be one of: \fBall\fR,
\fBinternal\-only\fR, \fBinternal\-and\-cloud\-load\-balancing\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice.

