
.TH "GCLOUD_ALPHA_COMPUTE_INSTANCES_OPS\-AGENTS" 1



.SH "NAME"
.HP
gcloud alpha compute instances ops\-agents \- manage Operation Suite (Ops) agents for Compute Engine VM instances



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute instances ops\-agents\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Operation Suite (Ops) agents for Compute Engine VM
instances.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBpolicies\fR
\fB(ALPHA)\fR Manage Operation Suite (Ops) agents policies that install, update,
and uninstall agents for Compute Engine VM instances.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

