
.TH "GCLOUD_ALPHA_SERVICE\-DIRECTORY_LOCATIONS_LIST" 1



.SH "NAME"
.HP
gcloud alpha service\-directory locations list \- list locations



.SH "SYNOPSIS"
.HP
\f5gcloud alpha service\-directory locations list\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR List locations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To describe a Service Directory location, run:

.RS 2m
$ gcloud alpha service\-directory locations list
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta service\-directory locations list
.RE

