
.TH "GCLOUD_ALPHA_RECOMMENDER_INSIGHTS_MARK\-ACCEPTED" 1



.SH "NAME"
.HP
gcloud alpha recommender insights mark\-accepted \- mark an insight's state as ACCEPTED. Can be applied to insights in ACTIVE or ACCEPTED state



.SH "SYNOPSIS"
.HP
\f5gcloud alpha recommender insights mark\-accepted\fR (\fIINSIGHT\fR\ :\ \fB\-\-insight\-type\fR=\fIINSIGHT_TYPE\fR\ \fB\-\-location\fR=\fILOCATION\fR) \fB\-\-etag\fR=\fIETAG\fR [\fB\-\-state\-metadata\fR=\fIKEY\fR=\fIVALUE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Mark an insight's state as ACCEPTED. Can be applied to insights in
ACTIVE or ACCEPTED state.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Insight resource \- The insight to mark as accepted. The arguments in this group
can be used to specify the attributes of this resource. (NOTE) Some attributes
are not given arguments in this group but can be set in other ways. To set the
[project] attribute: provide the argument [insight] on the command line with a
fully specified name; provide the argument [\-\-project] on the command line;
set the property [core/project]. This must be specified.

.RS 2m
.TP 2m
\fIINSIGHT\fR
ID of the insight or fully qualified identifier for the insight. This positional
must be specified if any of the other arguments in this group are specified.

.TP 2m
\fB\-\-insight\-type\fR=\fIINSIGHT_TYPE\fR
The insight type.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location ID.


.RE
.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-etag\fR=\fIETAG\fR
Insight's current etag value.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-state\-metadata\fR=\fIKEY\fR=\fIVALUE\fR
State properties to include with this state. This fully replaces the current
state_metadata for this insight.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBrecommender/v1alpha2\fR API. The full documentation for
this API can be found at: https://cloud.google.com/recommender/docs/



.SH "EXAMPLES"

To mark an insight as ACCEPTED:

.RS 2m
$ gcloud alpha recommender insights mark\-accepted abcd\-1234 \e
    \-\-project=project\-name \-\-location=global \e
    \-\-insight\-type=google.compute.firewall.Insight \-\-etag=abc123
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

