
.TH "GCLOUD_ALPHA_ASSURED_WORKLOADS_CREATE" 1



.SH "NAME"
.HP
gcloud alpha assured workloads create \- create a new Assured Workloads environment



.SH "SYNOPSIS"
.HP
\f5gcloud alpha assured workloads create\fR \fB\-\-billing\-account\fR=\fIBILLING_ACCOUNT\fR \fB\-\-compliance\-regime\fR=\fICOMPLIANCE_REGIME\fR \fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR \fB\-\-location\fR=\fILOCATION\fR \fB\-\-next\-rotation\-time\fR=\fINEXT_ROTATION_TIME\fR \fB\-\-organization\fR=\fIORGANIZATION\fR \fB\-\-rotation\-period\fR=\fIROTATION_PERIOD\fR [\fB\-\-external\-identifier\fR=\fIEXTERNAL_IDENTIFIER\fR] [\fB\-\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Create a new Assured Workloads environment



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-billing\-account\fR=\fIBILLING_ACCOUNT\fR
The billing account of the new Assured Workloads environment, for example,
billingAccounts/0000AA\-AAA00A\-A0A0A0

.TP 2m
\fB\-\-compliance\-regime\fR=\fICOMPLIANCE_REGIME\fR
The compliance regime of the new Assured Workloads environment.
\fICOMPLIANCE_REGIME\fR must be one of: \fBCJIS\fR, \fBFEDRAMP_HIGH\fR,
\fBFEDRAMP_MODERATE\fR, \fBIL4\fR.

.TP 2m
\fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR
The display name of the new Assured Workloads environment

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the new Assured Workloads environment. For a current list of
supported LOCATION values, see Assured Workloads locations
(http://cloud/assured\-workloads/docs/locations).

.TP 2m
\fB\-\-next\-rotation\-time\fR=\fINEXT_ROTATION_TIME\fR
The next rotation time of the new Assured Workloads environment, for example,
2020\-12\-30T10:15:30.00Z

.TP 2m
\fB\-\-organization\fR=\fIORGANIZATION\fR
The parent organization of the new Assured Workloads environment, provided as an
organization ID

.TP 2m
\fB\-\-rotation\-period\fR=\fIROTATION_PERIOD\fR
The billing account of the new Assured Workloads environment, for example,
172800s


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-external\-identifier\fR=\fIEXTERNAL_IDENTIFIER\fR
The external identifier of the new Assured Workloads environment

.TP 2m
\fB\-\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...]
The labels of the new Assured Workloads environment, for example,
LabelKey1=LabelValue1,LabelKey2=LabelValue2


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

The following example command creates a new Assured Workloads environment with
these properties:

.RS 2m
.IP "\(bu" 2m
belonging to an organization with ID 123
.IP "\(bu" 2m
located in the \f5us\-central1\fR region
.IP "\(bu" 2m
display name \f5Test\-Workload\fR
.IP "\(bu" 2m
compliance regime \f5FEDRAMP_MODERATE\fR (other options include:
\f5FEDRAMP_HIGH\fR, \f5IL4\fR and \f5CJIS\fR)
.IP "\(bu" 2m
billing account \f5billingAccounts/456\fR
.IP "\(bu" 2m
first key rotation set for 10:15am on the December 30, 2020
.IP "\(bu" 2m
key rotation interval set for every 48 hours
.IP "\(bu" 2m
with the label: key = 'LabelKey1', value = 'LabelValue1'
.IP "\(bu" 2m
with the label: key = 'LabelKey2', value = 'LabelValue2'
.RE
.sp

.RS 2m
$ gcloud alpha assured workloads create \-\-organization=123 \e
    \-\-location=us\-central1 \-\-display\-name=Test\-Workload \e
    \-\-compliance\-regime=FEDRAMP_MODERATE \e
    \-\-billing\-account=billingAccounts/456 \e
    \-\-next\-rotation\-time=2020\-12\-30T10:15:00.00Z \e
    \-\-rotation\-period=172800s \e
    \-\-labels LabelKey1=LabelValue1,LabelKey2=LabelValue2
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta assured workloads create
.RE

