
.TH "GCLOUD_ALPHA_SERVICES_API\-KEYS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha services api\-keys describe \- describe an API key's metadata



.SH "SYNOPSIS"
.HP
\f5gcloud alpha services api\-keys describe\fR \fIKEY\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Describe an API key's metadata.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Key resource \- The name of the key to describe. This represents a Cloud
resource. (NOTE) Some attributes are not given arguments in this group but can
be set in other ways. To set the [project] attribute: provide the argument [key]
on the command line with a fully specified name; provide the argument
[\-\-project] on the command line; set the property [core/project]. This must be
specified.

.RS 2m
.TP 2m
\fIKEY\fR
ID of the key or fully qualified identifier for the key.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

