
.TH "GCLOUD_SPANNER_DATABASES_SESSIONS_DELETE" 1



.SH "NAME"
.HP
gcloud spanner databases sessions delete \- delete a Cloud Spanner session



.SH "SYNOPSIS"
.HP
\f5gcloud spanner databases sessions delete\fR (\fISESSION\fR\ :\ \fB\-\-database\fR=\fIDATABASE\fR\ \fB\-\-instance\fR=\fIINSTANCE\fR) [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a Cloud Spanner session.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Session resource \- The Cloud Spanner session to delete. The arguments in this
group can be used to specify the attributes of this resource. (NOTE) Some
attributes are not given arguments in this group but can be set in other ways.
To set the [project] attribute: Set the property [core/project] or provide the
flag [\-\-project] on the command line. This must be specified.

.RS 2m
.TP 2m
\fISESSION\fR
The ID of the session or a fully qualified identifier for the session. This
positional must be specified if any of the other arguments in this group are
specified.

.TP 2m
\fB\-\-database\fR=\fIDATABASE\fR
The Cloud Spanner database for the session.

.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR
The Cloud Spanner instance for the session.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha spanner databases sessions delete
$ gcloud beta spanner databases sessions delete
.RE

