
.TH "GCLOUD_ALPHA_ANTHOS" 1



.SH "NAME"
.HP
gcloud alpha anthos \- anthos command Group



.SH "SYNOPSIS"
.HP
\f5gcloud alpha anthos\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Anthos command Group.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBauth\fR
\fB(ALPHA)\fR Authenticate clusters using the Anthos client.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud anthos
$ gcloud beta anthos
.RE

