
.TH "GCLOUD_BETA_IDENTITY_GROUPS_MEMBERSHIPS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta identity groups memberships describe \- describe a membership in a group



.SH "SYNOPSIS"
.HP
\f5gcloud beta identity groups memberships describe\fR \fB\-\-group\-email\fR=\fIGROUP_EMAIL\fR \fB\-\-member\-email\fR=\fIMEMBER_EMAIL\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Describe a membership in a group.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-group\-email\fR=\fIGROUP_EMAIL\fR
The email address of the group whose membership is being described.

.TP 2m
\fB\-\-member\-email\fR=\fIMEMBER_EMAIL\fR
The email address of the member whose membership is being described.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBcloudidentity/v1beta1\fR API. The full documentation
for this API can be found at: https://cloud.google.com/identity/



.SH "EXAMPLES"

To describe a membership in a group:

.RS 2m
$ gcloud beta identity groups memberships describe \e
    \-\-group\-email="eng\-discuss@foo.com" \e
    \-\-member\-email="user@foo.com"
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud identity groups memberships describe
$ gcloud alpha identity groups memberships describe
.RE

