
.TH "GCLOUD_ALPHA_NETWORK\-CONNECTIVITY_SPOKES_DELETE" 1



.SH "NAME"
.HP
gcloud alpha network\-connectivity spokes delete \- delete a spoke



.SH "SYNOPSIS"
.HP
\f5gcloud alpha network\-connectivity spokes delete\fR (\fISPOKE\fR\ :\ \fB\-\-region\fR=\fIREGION\fR) [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Delete the specified spoke.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Spoke resource \- Name of the spoke to be deleted. The arguments in this group
can be used to specify the attributes of this resource. (NOTE) Some attributes
are not given arguments in this group but can be set in other ways. To set the
[project] attribute: provide the argument [spoke] on the command line with a
fully specified name; set the property [core/project]; provide the argument
[\-\-project] on the command line. This must be specified.

.RS 2m
.TP 2m
\fISPOKE\fR
ID of the spoke or fully qualified identifier for the spoke. This positional
must be specified if any of the other arguments in this group are specified.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The location Id.


.RE
.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Return immediately, without waiting for the operation in progress to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBnetworkconnectivity/v1alpha1\fR API. The full
documentation for this API can be found at: https://cloud.google.com/



.SH "EXAMPLES"

Delete a spoke with name \f5\fImyspoke\fR\fR in region \f5\fIus\-central1\fR\fR.

.RS 2m
$ gcloud alpha network\-connectivity spokes delete myspoke \e
    \-\-region=us\-central1
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

