
.TH "GCLOUD_ALPHA_COMPUTE_OS\-LOGIN_REMOVE\-PROFILE" 1



.SH "NAME"
.HP
gcloud alpha compute os\-login remove\-profile \- remove the posix account information for the current user



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute os\-login remove\-profile\fR [\fB\-\-operating\-system\fR=\fIOPERATING_SYSTEM\fR;\ default="linux"] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute os\-login remove\-profile\fR removes the
posix account information for the current user where the account ID field is set
to the current project ID. Posix account entries for G Suite users do not set
the account ID field and can only be modified by a domain administrator.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-operating\-system\fR=\fIOPERATING_SYSTEM\fR; default="linux"
Specifies the profile type to remove. \fIOPERATING_SYSTEM\fR must be one of:
\fBlinux\fR, \fBwindows\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud compute os\-login remove\-profile
$ gcloud beta compute os\-login remove\-profile
.RE

