
.TH "GCLOUD_SCHEDULER_JOBS" 1



.SH "NAME"
.HP
gcloud scheduler jobs \- manage Cloud Scheduler jobs



.SH "SYNOPSIS"
.HP
\f5gcloud scheduler jobs\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Scheduler jobs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create Cloud Scheduler jobs for various types of targets.

.TP 2m
\fBupdate\fR
Update Cloud Scheduler jobs for various types of targets.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdelete\fR
Delete a job.

.TP 2m
\fBdescribe\fR
Show details about a job.

.TP 2m
\fBlist\fR
List jobs.

.TP 2m
\fBpause\fR
Pause the execution of a job.

.TP 2m
\fBresume\fR
Resume execution of a paused job.

.TP 2m
\fBrun\fR
Trigger an on\-demand execution of a job.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha scheduler jobs
$ gcloud beta scheduler jobs
.RE

