
.TH "GCLOUD_PUBSUB_TOPICS" 1



.SH "NAME"
.HP
gcloud pubsub topics \- manage Cloud Pub/Sub topics



.SH "SYNOPSIS"
.HP
\f5gcloud pubsub topics\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Pub/Sub topics.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding to a topic.

.TP 2m
\fBcreate\fR
Creates one or more Cloud Pub/Sub topics.

.TP 2m
\fBdelete\fR
Deletes one or more Cloud Pub/Sub topics.

.TP 2m
\fBdescribe\fR
Describes a Cloud Pub/Sub topic.

.TP 2m
\fBdetach\-subscription\fR
Detaches one or more Cloud Pub/Sub subscriptions.

.TP 2m
\fBget\-iam\-policy\fR
Get the IAM policy for a Cloud Pub/Sub Topic.

.TP 2m
\fBlist\fR
Lists Cloud Pub/Sub topics within a project.

.TP 2m
\fBlist\-subscriptions\fR
Lists Cloud Pub/Sub subscriptions from a given topic.

.TP 2m
\fBpublish\fR
Publishes a message to the specified topic.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove IAM policy binding of a topic.

.TP 2m
\fBset\-iam\-policy\fR
Set IAM policy for a topic.

.TP 2m
\fBupdate\fR
Updates an existing Cloud Pub/Sub topic.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha pubsub topics
$ gcloud beta pubsub topics
.RE

