
.TH "GCLOUD_BETA_COMPUTE_OPERATIONS" 1



.SH "NAME"
.HP
gcloud beta compute operations \- read and manipulate Compute Engine operations



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Read and manipulate Compute Engine operations.

For more information about operations, see the operations documentation
(https://cloud.google.com/compute/docs/audit\-logging).

See also: Operations API
(https://cloud.google.com/compute/docs/reference/rest/v1/regionOperations).



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe a Google Compute Engine operation.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List Google Compute Engine operations.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute operations
$ gcloud alpha compute operations
.RE

