
.TH "GCLOUD_BIGTABLE_APP\-PROFILES" 1



.SH "NAME"
.HP
gcloud bigtable app\-profiles \- manage Cloud Bigtable app profiles



.SH "SYNOPSIS"
.HP
\f5gcloud bigtable app\-profiles\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Bigtable app profiles.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a new Bigtable app profile.

.TP 2m
\fBdelete\fR
Delete a Bigtable app profile.

.TP 2m
\fBdescribe\fR
Describe an existing Bigtable app profile.

.TP 2m
\fBlist\fR
List Bigtable app profiles.

.TP 2m
\fBupdate\fR
Update a Bigtable app profile.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha bigtable app\-profiles
$ gcloud beta bigtable app\-profiles
.RE

