
.TH "GCLOUD_ALPHA_BILLING_PROJECTS_UNLINK" 1



.SH "NAME"
.HP
gcloud alpha billing projects unlink \- unlink the account (if\ any) linked with a project



.SH "SYNOPSIS"
.HP
\f5gcloud alpha billing projects unlink\fR \fIPROJECT_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command unlinks a project from its linked billing account.
This disables billing on the project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
Specify a project id.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To unlink the project \f5my\-project\fR from its linked billing account, run:

.RS 2m
$ gcloud alpha billing projects unlink my\-project
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta billing projects unlink
.RE

