
.TH "GCLOUD_ALPHA_COMPUTE_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha compute operations describe \- describe a Compute Engine operation



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute operations describe\fR \fINAME\fR [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute operations describe\fR displays all data
associated with a Compute Engine operation in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the operation to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If set, the operation is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the operation to describe. Overrides the default \fBcompute/region\fR
property value for this command invocation.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
Zone of the operation to describe. Overrides the default \fBcompute/zone\fR
property value for this command invocation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To get details about a global operation, run:

.RS 2m
$ gcloud alpha compute operations describe OPERATION \-\-global
.RE

To get details about a regional operation, run:

.RS 2m
$ gcloud alpha compute operations describe OPERATION \e
    \-\-region=us\-central1
.RE

To get details about a zonal operation, run:

.RS 2m
$ gcloud alpha compute operations describe OPERATION \e
    \-\-zone=us\-central1\-a
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. These variants are also available:

.RS 2m
$ gcloud compute operations describe
$ gcloud beta compute operations describe
.RE

