
.TH "GCLOUD_BETA_SERVICES_VPC\-PEERINGS_OPERATIONS_WAIT" 1



.SH "NAME"
.HP
gcloud beta services vpc\-peerings operations wait \- waits for an operation to complete  for a given operation name



.SH "SYNOPSIS"
.HP
\f5gcloud beta services vpc\-peerings operations wait\fR \fB\-\-name\fR=\fIOPERATION_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR This command will block until an operation has been marked as
complete.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-name\fR=\fIOPERATION_NAME\fR
The name of operation to wait


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "EXAMPLES"

To wait on an operation named \f5operations/abc\fR to complete, run:

.RS 2m
$ gcloud beta services vpc\-peerings operations wait \e
    \-\-name=operations/abc
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha services vpc\-peerings operations wait
.RE

