
.TH "GCLOUD_ALPHA_ML" 1



.SH "NAME"
.HP
gcloud alpha ml \- use Google Cloud machine learning capabilities



.SH "SYNOPSIS"
.HP
\f5gcloud alpha ml\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Use Google Cloud machine learning capabilities.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlanguage\fR
\fB(ALPHA)\fR Use the Google Cloud Natural Language API to analyze text.

.TP 2m
\fBspeech\fR
\fB(ALPHA)\fR Use Google Cloud Speech to get transcripts of audio.

.TP 2m
\fBtranslate\fR
\fB(ALPHA)\fR Cloud ML Translate command groups.

.TP 2m
\fBvideo\fR
\fB(ALPHA)\fR Cloud ML Video\-Intelligence command groups.

.TP 2m
\fBvision\fR
\fB(ALPHA)\fR Use Google Cloud Vision to analyze images.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud ml
$ gcloud beta ml
.RE

