
.TH "GCLOUD_BETA_FIREBASE_TEST_IOS_MODELS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta firebase test ios models describe \- describe an iOS model



.SH "SYNOPSIS"
.HP
\f5gcloud beta firebase test ios models describe\fR \fIMODEL_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Describe an iOS model.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIMODEL_ID\fR
ID of the model to describe, found using $ gcloud beta firebase test ios models
list.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To describe an iOS model, run:

.RS 2m
gcloud beta firebase test ios models describe iphone7
.RE

To describe an iOS model in JSON format, run:

.RS 2m
gcloud beta firebase test ios models describe iphone7 \-\-format=json
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud firebase test ios models describe
$ gcloud alpha firebase test ios models describe
.RE

