
.TH "GCLOUD_ALPHA_BUILDS_DEPLOY_GKE" 1



.SH "NAME"
.HP
gcloud alpha builds deploy gke \- build and deploy to a target Google Kubernetes Engine cluster



.SH "SYNOPSIS"
.HP
\f5gcloud alpha builds deploy gke\fR [\fISOURCE\fR] \fB\-\-cluster\fR=\fICLUSTER\fR \fB\-\-location\fR=\fILOCATION\fR (\fB\-\-image\fR=\fIIMAGE\fR\ |\ \fB\-\-tag\fR=\fITAG\fR\ |\ \fB\-\-tag\-default\fR) [\fB\-\-app\-name\fR=\fIAPP_NAME\fR] [\fB\-\-app\-version\fR=\fIAPP_VERSION\fR] [\fB\-\-async\fR] [\fB\-\-config\fR=\fICONFIG\fR] [\fB\-\-expose\fR=\fIEXPOSE\fR] [\fB\-\-gcs\-staging\-dir\fR=\fIGCS_STAGING_DIR\fR] [\fB\-\-namespace\fR=\fINAMESPACE\fR;\ default="default"] [\fB\-\-timeout\fR=\fITIMEOUT\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Build and deploy to a target Google Kubernetes Engine cluster.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
[\fISOURCE\fR]
Location of the source and configs to build and deploy. The \f5\-\-config\fR
option, if provided, is a relative path in the source directory. The location
can be a directory on a local disk or a gzipped archive file (.tar.gz) in Google
Cloud Storage.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-cluster\fR=\fICLUSTER\fR
Name of the target cluster to deploy to.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
Region or zone of the target cluster to deploy to.

.TP 2m

Exactly one of these must be specified:

.RS 2m
.TP 2m
\fB\-\-image\fR=\fIIMAGE\fR
Existing container image to deploy. If set, Cloud Build deploys the container
image to the target Kubernetes cluster. The image must be in the gcr.io/* or
*.gcr.io/* namespaces.

.TP 2m
\fB\-\-tag\fR=\fITAG\fR
Tag to use with a 'docker build' image creation. Cloud Build runs a remote
\'docker build \-t $TAG .' command, where $TAG is the tag provided by this flag.
The tag must be in the gcr.io/* or *.gcr.io/* namespaces. If you specify a tag
in this command, your source must include a Dockerfile. For instructions on
building using a Dockerfile see
https://cloud.google.com/cloud\-build/docs/quickstart\-docker.

If you would like a default tag to build with, supply the flag
\f5\-\-tag\-default\fR.

.TP 2m
\fB\-\-tag\-default\fR
Default tag to use with a 'docker build' image creation. Cloud Build runs a
remote 'docker build \-t $TAG .' command, where $TAG is the tag, in the format
\'gcr.io/$PROJECT_ID/<source directory>:$SHORT_SHA'.

Your source must include a Dockerfile. For instructions on building using a
Dockerfile see https://cloud.google.com/cloud\-build/docs/quickstart\-docker.


.RE
.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-app\-name\fR=\fIAPP_NAME\fR
If specified, the following label is added to the Kubernetes manifests:
\'app.kubernetes.io/name: APP_NAME'. Defaults to the container image name
provided by \f5\-\-image\fR or \f5\-\-tag\fR without the tag, e.g. 'my\-app' for
\'gcr.io/my\-project/my\-app:1.0.0'.

.TP 2m
\fB\-\-app\-version\fR=\fIAPP_VERSION\fR
If specified, the following label is added to the Kubernetes manifests:
\'app.kubernetes.io/version: APP_VERSION'. Defaults to the container image tag
provided by \f5\-\-image\fR or \f5\-\-tag\fR. If no image tag is provided and
\f5SOURCE\fR is a valid git repository, defaults to the short revision hash of
the HEAD commit.

.TP 2m
\fB\-\-async\fR
Return immediately, without waiting for the operation in progress to complete.

.TP 2m
\fB\-\-config\fR=\fICONFIG\fR
Path to the Kubernetes YAML, or directory containing multiple Kubernetes YAML
files, used to deploy the container image, relative to SOURCE. The files must
reference the provided container image or tag.

If this field is not set, a default Deployment config and Horizontal Pod
Autoscaler config are used to deploy the image.

.TP 2m
\fB\-\-expose\fR=\fIEXPOSE\fR
Port that the deployed application listens to. If set, a Kubernetes Service of
type 'LoadBalancer' is created with a single TCP port mapping that exposes this
port.

.TP 2m
\fB\-\-gcs\-staging\-dir\fR=\fIGCS_STAGING_DIR\fR
Path to the Google Cloud Storage subdirectory into which to copy the source and
configs (suggested base and expanded Kubernetes YAML files) that are used to
stage and deploy your app. If the bucket in this path doesn't exist, Cloud Build
creates it.

If this field is not set, the source and configs are written to
\'gs://[PROJECT_ID]\fIcloudbuild/deploy', where source is written to the
\'source' sub\-directory and configs are written to the 'config' sub\-directory.

.TP 2m
\fB\-\-namespace\fR=\fRNAMESPACE\fI; default="default"
Namespace of the target cluster to deploy to. If this field is not set, the
\'default' namespace is used.

.TP 2m
\fB\-\-timeout\fR=\fRTIMEOUT\fI
Maximum time a build is run before it times out. For example, "2h15m5s" is 2
hours, 15 minutes, and 5 seconds. If you do not specify a unit, seconds is
assumed. Overrides the default builds/timeout property value for this command
invocation.


\fR
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

