
.TH "GCLOUD_ALPHA_COMPUTE_RESERVATIONS_UPDATE" 1



.SH "NAME"
.HP
gcloud alpha compute reservations update \- update a Compute Engine reservation



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute reservations update\fR (\fIRESERVATION\fR\ :\ \fB\-\-zone\fR=\fIZONE\fR) \fB\-\-vm\-count\fR=\fIVM_COUNT\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Update a Compute Engine reservation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Reservation resource \- The name of the reservation to update. The arguments in
this group can be used to specify the attributes of this resource. (NOTE) Some
attributes are not given arguments in this group but can be set in other ways.
To set the [project] attribute: provide the argument [reservation] on the
command line with a fully specified name; set the property [core/project];
provide the argument [\-\-project] on the command line. This must be specified.

.RS 2m
.TP 2m
\fIRESERVATION\fR
ID of the reservation or fully qualified identifier for the reservation. This
positional must be specified if any of the other arguments in this group are
specified.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The name of the Google Compute Engine zone.


.RE
.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-vm\-count\fR=\fIVM_COUNT\fR
Number of VM instances can be updated. The value of this field must be an int in
the range [1, 1000].


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Return immediately, without waiting for the operation in progress to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBcompute/alpha\fR API. The full documentation for this
API can be found at:
https://developers.google.com/compute/docs/reference/latest/



.SH "EXAMPLES"

To update a given Compute Enginer reservation with 500 VM instances, run:

.RS 2m
$ gcloud alpha compute reservations update my\-reservation \e
    \-\-zone=ZONE \-\-vm\-count=500
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud compute reservations update
$ gcloud beta compute reservations update
.RE

