
.TH "GCLOUD_BETA_ML\-ENGINE_VERSIONS_DELETE" 1



.SH "NAME"
.HP
gcloud beta ml\-engine versions delete \- delete an existing AI Platform version



.SH "SYNOPSIS"
.HP
\f5gcloud beta ml\-engine versions delete\fR \fIVERSION\fR \fB\-\-model\fR=\fIMODEL\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Delete an existing AI Platform version.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSION\fR
Name of the model version.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-model\fR=\fIMODEL\fR
Name of the model.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud ml\-engine versions delete
$ gcloud alpha ml\-engine versions delete
.RE

