
.TH "GCLOUD_BETA_GAME_SERVERS_DEPLOYMENTS" 1



.SH "NAME"
.HP
gcloud beta game servers deployments \- deploy and manage Cloud Game Server Deployments



.SH "SYNOPSIS"
.HP
\f5gcloud beta game servers deployments\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Deploy and manage Cloud Game Server Deployments.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(BETA)\fR Create a Deployment.

.TP 2m
\fBdelete\fR
\fB(BETA)\fR Delete a Deployment.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe a Deployment.

.TP 2m
\fBdescribe\-rollout\fR
\fB(BETA)\fR Describe a Rollout.

.TP 2m
\fBfetch\-state\fR
\fB(BETA)\fR Fetches the state of a Deployment.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List Deployments.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR Update a Deployment.

.TP 2m
\fBupdate\-rollout\fR
\fB(BETA)\fR Update a Deployment Rollout.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud game servers deployments
$ gcloud alpha game servers deployments
.RE

