
.TH "GCLOUD_ALPHA_CONTAINER_BINAUTHZ_POLICY_EXPORT" 1



.SH "NAME"
.HP
gcloud alpha container binauthz policy export \- export the Binary Authorization policy for the current project



.SH "SYNOPSIS"
.HP
\f5gcloud alpha container binauthz policy export\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This function's default output is a valid policy YAML file. If
dumped to a file and edited, the new policy can be provided to the \f5$ gcloud
alpha container binauthz policy import\fR command to cause these edits to be
reflected in the project policy.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To export the current project's policy:

.RS 2m
$ gcloud alpha container binauthz policy export > my_policy.yaml
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. These variants are also available:

.RS 2m
$ gcloud container binauthz policy export
$ gcloud beta container binauthz policy export
.RE

