
.TH "GCLOUD_ALPHA_REDIS" 1



.SH "NAME"
.HP
gcloud alpha redis \- manage Cloud Memorystore Redis resources



.SH "SYNOPSIS"
.HP
\f5gcloud alpha redis\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Memorystore Redis resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBinstances\fR
\fB(ALPHA)\fR Manage Cloud Memorystore Redis instances.

.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Manage Cloud Memorystore Redis operations.

.TP 2m
\fBregions\fR
\fB(ALPHA)\fR Manage Cloud Memorystore Redis regions.

.TP 2m
\fBzones\fR
\fB(ALPHA)\fR Manage Cloud Memorystore Redis zones.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. These variants are also available:

.RS 2m
$ gcloud redis
$ gcloud beta redis
.RE

