
.TH "GCLOUD_ALPHA_SERVICES_VPC\-PEERINGS_LIST" 1



.SH "NAME"
.HP
gcloud alpha services vpc\-peerings list \- list connections to a service via VPC peering for a project network



.SH "SYNOPSIS"
.HP
\f5gcloud alpha services vpc\-peerings list\fR \fB\-\-network\fR=\fINETWORK\fR [\fB\-\-service\fR=\fISERVICE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command lists connections of a network to a service via VPC
peering for a project.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-network\fR=\fINETWORK\fR
The network in the current project to list connections with the service


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR
The service to list connections


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To list connections of a network called \f5my\-network\fR to a service called
\f5your\-service\fR, run:

.RS 2m
$ gcloud alpha services vpc\-peerings list \-\-network=my\-network \e
    \-\-service=your\-service
.RE

To list connections of a network against all services, run:

.RS 2m
$ gcloud alpha services vpc\-peerings list \-\-network=my\-network
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud services vpc\-peerings list
$ gcloud beta services vpc\-peerings list
.RE

