
.TH "GCLOUD_ML_VIDEO" 1



.SH "NAME"
.HP
gcloud ml video \- cloud ML Video\-Intelligence command groups



.SH "SYNOPSIS"
.HP
\f5gcloud ml video\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Cloud ML Video\-Intelligence command groups.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBoperations\fR
Command group for working with Cloud Video Intelligence operations.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdetect\-explicit\-content\fR
Detect explicit content in videos.

.TP 2m
\fBdetect\-labels\fR
Detect general labels for videos.

.TP 2m
\fBdetect\-shot\-changes\fR
Detect shot changes in videos.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha ml video
$ gcloud beta ml video
.RE

