
.TH "GCLOUD_ALPHA_SCC_SETTINGS_SERVICES_MODULES" 1



.SH "NAME"
.HP
gcloud alpha scc settings services modules \- manage Cloud SCC modules settings



.SH "SYNOPSIS"
.HP
\f5gcloud alpha scc settings services modules\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud SCC modules settings.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Display effective module settings of Security Command Center(SCC).

.TP 2m
\fBdescribe\-explicit\fR
\fB(ALPHA)\fR Display module settings of Security Command Center(SCC).

.TP 2m
\fBdisable\fR
\fB(ALPHA)\fR Disable a module in Security Command Center(SCC).

.TP 2m
\fBenable\fR
\fB(ALPHA)\fR Enable a module in Security Command Center(SCC).


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

