
.TH "GCLOUD_BETA_DNS_DNS\-KEYS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta dns dns\-keys describe \- show details about a DNS key resource



.SH "SYNOPSIS"
.HP
\f5gcloud beta dns dns\-keys describe\fR \fIKEY\-ID\fR \fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR This command displays the details of a single DNS key resource.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIKEY\-ID\fR
The DNS key identifier.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
The name of the managed\-zone the DNSKEY record belongs to


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To show details about a DNS key resource with ID 3 in a managed zone
\f5my_zone\fR, run:

.RS 2m
$ gcloud beta dns dns\-keys describe \-\-zone my_zone 3
.RE

To get the DS record corresponding for the DNSKEY record from the previous
example, run (the DNSKEY record must be for a key\-signing key):

.RS 2m
$ gcloud beta dns dns\-keys describe \-\-zone my_zone 3 \e
    \-\-format 'value(ds_record())'
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud dns dns\-keys describe
.RE

