
.TH "GCLOUD_DNS_MANAGED\-ZONES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dns managed\-zones describe \- view the details of a Cloud DNS managed\-zone



.SH "SYNOPSIS"
.HP
\f5gcloud dns managed\-zones describe\fR \fIZONE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command displays the details of the specified managed\-zone.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

ZONE \- The name of the managed\-zone to be described. This represents a Cloud
resource. (NOTE) Some attributes are not given arguments in this group but can
be set in other ways. To set the [project] attribute: Set the property
[core/project] or provide the flag [\-\-project] on the command line. This must
be specified.

.RS 2m
.TP 2m
\fIZONE\fR
The ID of the zone or a fully qualified identifier for the zone.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To display the details of your managed\-zone, run:

.RS 2m
$ gcloud dns managed\-zones describe my_zone
.RE



.SH "NOTES"

This variant is also available:

.RS 2m
$ gcloud beta dns managed\-zones describe
.RE

