
.TH "GCLOUD_ALPHA_SERVICES_IDENTITY" 1



.SH "NAME"
.HP
gcloud alpha services identity \- manage service identity



.SH "SYNOPSIS"
.HP
\f5gcloud alpha services identity\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage service identity.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Create a service identity for a consumer.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. This variant is also available:

.RS 2m
$ gcloud beta services identity
.RE

