
.TH "GCLOUD_BETA_COMPUTE_GROUPS_REMOVE\-MEMBERS" 1



.SH "NAME"
.HP
gcloud beta compute groups remove\-members \- remove a user from a Google Compute Engine group



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute groups remove\-members\fR \fINAME\fR [\fINAME\fR\ ...] \fB\-\-members\fR=\fIUSERNAME\fR,[\fIUSERNAME\fR,...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute groups remove\-members\fR removes a user
from a Google Compute Engine group.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the groups to remove members from.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-members\fR=\fIUSERNAME\fR,[\fIUSERNAME\fR,...]
The names or fully\-qualified URLs of the users to remove.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To remove a user from a group, run:

.RS 2m
$ gcloud beta compute groups remove\-members example\-group \e
    \-\-members example\-user
.RE

To remove multiple users from multiple groups with one command, run

.RS 2m
$ gcloud beta compute groups remove\-members example\-group\-1 \e
    example\-group\-2 \-\-members example\-user\-1,example\-user\-2
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha compute groups remove\-members
.RE

