
.TH "GCLOUD_PUBSUB_SNAPSHOTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud pubsub snapshots describe \- describes a Cloud Pub/Sub snapshot



.SH "SYNOPSIS"
.HP
\f5gcloud pubsub snapshots describe\fR \fISNAPSHOT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describes a Cloud Pub/Sub snapshot.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISNAPSHOT\fR
snapshot to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha pubsub snapshots describe
$ gcloud beta pubsub snapshots describe
.RE

