
.TH "GCLOUD_ACTIVE\-DIRECTORY_DOMAINS" 1



.SH "NAME"
.HP
gcloud active\-directory domains \- manage Managed Microsoft AD domains



.SH "SYNOPSIS"
.HP
\f5gcloud active\-directory domains\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Managed Microsoft AD domains.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBtrusts\fR
Manage Managed Microsoft AD domains.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a Managed Microsoft AD domain.

.TP 2m
\fBdelete\fR
Delete a managed Microsoft Active Directory domain.

.TP 2m
\fBdescribe\fR
Describe a Managed Microsoft AD domain.

.TP 2m
\fBget\-iam\-policy\fR
Describe the IAM policy for a Managed Microsoft AD domain.

.TP 2m
\fBlist\fR
List Managed Microsoft AD domains.

.TP 2m
\fBreset\-admin\-password\fR
Reset the admin password for a Managed Microsoft AD domain.

.TP 2m
\fBset\-iam\-policy\fR
Set the IAM policy for a Managed Microsoft AD domain.

.TP 2m
\fBupdate\fR
Update a Managed Microsoft AD domain.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha active\-directory domains
$ gcloud beta active\-directory domains
.RE

