
.TH "GCLOUD_ALPHA_GENOMICS" 1



.SH "NAME"
.HP
gcloud alpha genomics \- manage Genomics resources using version 1 of the API



.SH "SYNOPSIS"
.HP
\f5gcloud alpha genomics\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Genomics resources using version 1 of the API.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcallsets\fR
\fB(ALPHA)\fR Commands for Genomics callsets.

.TP 2m
\fBdatasets\fR
\fB(ALPHA)\fR Commands for Genomics datasets.

.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Commands for Genomics operations.

.TP 2m
\fBpipelines\fR
\fB(ALPHA)\fR Commands for Genomics pipelines.

.TP 2m
\fBreadgroupsets\fR
\fB(ALPHA)\fR Commands for Genomics read group sets.

.TP 2m
\fBreads\fR
\fB(ALPHA)\fR Commands for Genomics reads.

.TP 2m
\fBreferences\fR
\fB(ALPHA)\fR Commands for Genomics references.

.TP 2m
\fBreferencesets\fR
\fB(ALPHA)\fR Commands for Genomics reference sets.

.TP 2m
\fBvariants\fR
\fB(ALPHA)\fR Commands for Genomics variants.

.TP 2m
\fBvariantsets\fR
\fB(ALPHA)\fR Commands for Genomics variant sets.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/.

