
.TH "GCLOUD_ALPHA_IDENTITY_GROUPS_MEMBERSHIPS_ADD" 1



.SH "NAME"
.HP
gcloud alpha identity groups memberships add \- create a new membership in an existing group



.SH "SYNOPSIS"
.HP
\f5gcloud alpha identity groups memberships add\fR \fB\-\-group\-email\fR=\fIGROUP_EMAIL\fR \fB\-\-member\-email\fR=\fIMEMBER_EMAIL\fR \fB\-\-organization\fR=\fIORGANIZATION\fR [\fB\-\-expiration\fR=\fIEXPIRATION\fR] [\fB\-\-roles\fR=[\fIROLES\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Create a new membership in an existing group.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-group\-email\fR=\fIGROUP_EMAIL\fR
The email address of the group the new membership is being added to.

.TP 2m
\fB\-\-member\-email\fR=\fIMEMBER_EMAIL\fR
The email address of the group or user being added to a group.

.TP 2m
\fB\-\-organization\fR=\fIORGANIZATION\fR
The organization of the group the new membership is being added to.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-expiration\fR=\fIEXPIRATION\fR
Optional time of expiration for the membership. This is given as a duration from
now, for example '30d', '6m', '3y' for 30 days, 6 months, or 3 years
respectively.

.TP 2m
\fB\-\-roles\fR=[\fIROLES\fR,...]
Roles for the membership within the Group. If not specified, MEMBER will be used
as a default value.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBcloudidentity/v1alpha1\fR API. The full documentation
for this API can be found at: https://cloud.google.com/identity/



.SH "EXAMPLES"

To create a new membership in a group:

.RS 2m
$ gcloud alpha identity groups memberships add \e
    \-\-group\-email="eng\-discuss@foo.com"  \e
    \-\-organization="5149234212"  \e
    \-\-member\-email="user@foo.com"
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta identity groups memberships add
.RE

