
.TH "GCLOUD_COMPUTE_IMAGES_ADD\-LABELS" 1



.SH "NAME"
.HP
gcloud compute images add\-labels \- add labels to Google Compute Engine images



.SH "SYNOPSIS"
.HP
\f5gcloud compute images add\-labels\fR \fIIMAGE_NAME\fR \fB\-\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute images add\-labels\fR adds labels to a Google Compute Engine
image.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE_NAME\fR
Name of the disk image to operate on.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-labels\fR=[\fIKEY\fR=\fIVALUE\fR,...]
A list of labels to add.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To add key\-value pairs \f5\fIk0\fR\fR=\f5\fIv0\fR\fR and
\f5\fIk1\fR\fR=\f5\fIv1\fR\fR to 'example\-image'

.RS 2m
$ gcloud compute images add\-labels example\-image \-\-labels=k0=v0,k1=v1
.RE

Labels can be used to identify the image and to filter them. To find a image
labeled with key\-value pair \f5\fIk1\fR\fR, \f5\fIv2\fR\fR

.RS 2m
$ gcloud compute images list \-\-filter='labels.k1:v2'
.RE

To list only the labels when describing a resource, use \-\-format

.RS 2m
$ gcloud compute images describe example\-image \e
    \-\-format='default(labels)'
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute images add\-labels
$ gcloud beta compute images add\-labels
.RE

