
.TH "GCLOUD_COMPOSER" 1



.SH "NAME"
.HP
gcloud composer \- create and manage Cloud Composer Environments



.SH "SYNOPSIS"
.HP
\f5gcloud composer\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Cloud Composer is a managed Apache Airflow service that helps you create,
schedule, monitor and manage workflows. Cloud Composer automation helps you
create Airflow environments quickly and use Airflow\-native tools, such as the
powerful Airflow web interface and command line tools, so you can focus on your
workflows and not your infrastructure.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBenvironments\fR
Create and manage Cloud Composer environments.

.TP 2m
\fBoperations\fR
Manage Cloud Composer operations.


.RE
.sp

.SH "EXAMPLES"

To see how to create and manage environments, run:

.RS 2m
$ gcloud composer environments \-\-help
.RE

To see how to manage long\-running operations, run:

.RS 2m
$ gcloud composer operations \-\-help
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha composer
$ gcloud beta composer
.RE

