
.TH "GCLOUD_ALPHA_BUILD\-ARTIFACTS" 1



.SH "NAME"
.HP
gcloud alpha build\-artifacts \- manage Cloud Build Artifacts resources



.SH "SYNOPSIS"
.HP
\f5gcloud alpha build\-artifacts\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Build Artifacts resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Manage Cloud Build Artifacts long\-running operations.

.TP 2m
\fBpackages\fR
\fB(ALPHA)\fR Manage Cloud Build Artifacts packages.

.TP 2m
\fBprint\-settings\fR
\fB(ALPHA)\fR Print snippets to add to native tools settings files.

.TP 2m
\fBrepositories\fR
\fB(ALPHA)\fR Manage Cloud Build Artifacts repositories.

.TP 2m
\fBversions\fR
\fB(ALPHA)\fR Manage Cloud Build Artifacts package versions.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

