
.TH "GCLOUD_DNS_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dns operations describe \- describe an operation



.SH "SYNOPSIS"
.HP
\f5gcloud dns operations describe\fR \fIOPERATION_ID\fR \fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command displays the details of a single managed\-zone operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION_ID\fR
The id of the operation to display.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
Name of zone to get operations from.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To describe a managed\-zone operation:

.RS 2m
$ gcloud dns operations describe 1234 \-\-zone=my_zone
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha dns operations describe
$ gcloud beta dns operations describe
.RE

