
.TH "GCLOUD_ALPHA_COMPUTE_ORG\-SECURITY\-POLICIES" 1



.SH "NAME"
.HP
gcloud alpha compute org\-security\-policies \- manage Google Compute Engine organization security policies



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute org\-security\-policies\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Google Compute Organization Engine security policies.
Organization security policies are used to control incoming/outgoing traffic.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBassociations\fR
\fB(ALPHA)\fR Read and manipulate Google Compute Engine organization security
policy associations.

.TP 2m
\fBrules\fR
\fB(ALPHA)\fR Read and manipulate Google Compute Engine organization security
policy rules.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcopy\-rules\fR
\fB(ALPHA)\fR Replace the rules of a Google Compute Engine organization security
policy with rules from another policy.

.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Create a Google Compute Engine organization security policy.

.TP 2m
\fBdelete\fR
\fB(ALPHA)\fR Delete a Google Compute Engine organization security policy.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe a Google Compute Engine organization security policy.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Google Compute Engine organization security policies.

.TP 2m
\fBmove\fR
\fB(ALPHA)\fR Move a Google Compute Engine organization security policy.

.TP 2m
\fBupdate\fR
\fB(ALPHA)\fR Update a Google Compute Engine organization security policy.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

