
.TH "GCLOUD_ALPHA_AI_ENDPOINTS_UNDEPLOY\-MODEL" 1



.SH "NAME"
.HP
gcloud alpha ai endpoints undeploy\-model \- undeploy a model from an existing AI Platform endpoint



.SH "SYNOPSIS"
.HP
\f5gcloud alpha ai endpoints undeploy\-model\fR (\fIENDPOINT\fR\ :\ \fB\-\-region\fR=\fIREGION\fR) \fB\-\-deployed\-model\-id\fR=\fIDEPLOYED_MODEL_ID\fR [\fB\-\-traffic\-split\fR=[\fIDEPLOYED_MODEL_ID\fR=\fIVALUE\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Undeploy a model from an existing AI Platform endpoint.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Endpoint resource \- The endpoint to undeploy a model from. The arguments in
this group can be used to specify the attributes of this resource. (NOTE) Some
attributes are not given arguments in this group but can be set in other ways.
To set the [project] attribute: provide the argument [endpoint] on the command
line with a fully specified name; provide the argument [\-\-project] on the
command line; set the property [core/project]. This must be specified.

.RS 2m
.TP 2m
\fIENDPOINT\fR
ID of the endpoint or fully qualified identifier for the endpoint. This
positional must be specified if any of the other arguments in this group are
specified.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Cloud region for the endpoint.


.RE
.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-deployed\-model\-id\fR=\fIDEPLOYED_MODEL_ID\fR
Id of the deployed model.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-traffic\-split\fR=[\fIDEPLOYED_MODEL_ID\fR=\fIVALUE\fR,...]
List of paris of deployed model id and value to set as traffic split.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta ai endpoints undeploy\-model
.RE

