
.TH "GCLOUD_DATAPROC_AUTOSCALING\-POLICIES_IMPORT" 1



.SH "NAME"
.HP
gcloud dataproc autoscaling\-policies import \- import an autoscaling policy



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc autoscaling\-policies import\fR (\fIAUTOSCALING_POLICY\fR\ :\ \fB\-\-region\fR=\fIREGION\fR) [\fB\-\-source\fR=\fISOURCE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

If the specified autoscaling policy already exists, it will be overwritten.
Otherwise, a new autoscaling policy will be created. To edit an existing
autoscaling policy, you can export the autoscaling policy to a file, edit its
configuration, and then import the new configuration.

This command does not allow output only fields, such as policy id and resource
name. It populates the id field based on the resource name specified as the
first command line argument.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Autoscaling policy resource \- The autoscaling policy to import. The arguments
in this group can be used to specify the attributes of this resource. (NOTE)
Some attributes are not given arguments in this group but can be set in other
ways. To set the [project] attribute: provide the argument [autoscaling_policy]
on the command line with a fully specified name; provide the argument
[\-\-project] on the command line; set the property [core/project]. This must be
specified.

.RS 2m
.TP 2m
\fIAUTOSCALING_POLICY\fR
ID of the autoscaling policy or fully qualified identifier for the autoscaling
policy. This positional must be specified if any of the other arguments in this
group are specified.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Dataproc region for the autoscaling policy. Each Dataproc region constitutes an
independent resource namespace constrained to deploying instances into Compute
Engine zones inside the region. Overrides the default \f5dataproc/region\fR
property value for this command invocation.


.RE
.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-source\fR=\fISOURCE\fR
Path to a YAML file containing autoscaling policy configuration export data. The
YAML file must not contain any output\-only fields. Alternatively, you may omit
this flag to read from standard input. A schema describing the export/import
format can be found in:
$CLOUDSDKROOT/lib/googlecloudsdk/schemas/dataproc/v1/AutoscalingPolicy.yaml.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

The following command creates or updates the contents of autoscaling policy
\f5example\-autoscaling\-policy\fR based on a yaml file:

.RS 2m
$ gcloud dataproc autoscaling\-policies import \e
    example\-autoscaling\-policy \-\-source=saved\-policy.yaml
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha dataproc autoscaling\-policies import
$ gcloud beta dataproc autoscaling\-policies import
.RE

