
.TH "GCLOUD_BETA_FUNCTIONS_EVENT\-TYPES_LIST" 1



.SH "NAME"
.HP
gcloud beta functions event\-types list \- list types of events that can be a trigger for a Google Cloud Function



.SH "SYNOPSIS"
.HP
\f5gcloud beta functions event\-types list\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \f5gcloud beta functions event\-types list\fR displays types of
events that can be a trigger for a Google Cloud Function.

.RS 2m
.IP "\(bu" 2m
For an event type, \f5EVENT_TYPE_DEFAULT\fR marks whether the given event type
is the default for its provider (in which case the \f5\-\-event\-type\fR flag
may be omitted).
.IP "\(bu" 2m
For a resource, \f5RESOURCE_OPTIONAL\fR marks whether the resource has a
corresponding default value (in which case the \f5\-\-trigger\-resource\fR flag
may be omitted).
.RE
.sp



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud functions event\-types list
$ gcloud alpha functions event\-types list
.RE

