
.TH "GCLOUD_BETA_ERROR\-REPORTING_EVENTS" 1



.SH "NAME"
.HP
gcloud beta error\-reporting events \- manages your project's events data



.SH "SYNOPSIS"
.HP
\f5gcloud beta error\-reporting events\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manages your project's events data.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdelete\fR
\fB(BETA)\fR Deletes all error events of the project.

.TP 2m
\fBreport\fR
\fB(BETA)\fR Report an error.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice.

