
.TH "GCLOUD_BETA_IOT_DEVICES_CONFIGS_GET\-VALUE" 1



.SH "NAME"
.HP
gcloud beta iot devices configs get\-value \- show the binary data of a device's latest configuration



.SH "SYNOPSIS"
.HP
\f5gcloud beta iot devices configs get\-value\fR (\fB\-\-device\fR=\fIDEVICE\fR\ :\ \fB\-\-region\fR=\fIREGION\fR\ \fB\-\-registry\fR=\fIREGISTRY\fR) [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Show the binary data of a device's latest configuration.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m

Device resource \- The device for the configuration to get the value of. The
arguments in this group can be used to specify the attributes of this resource.
(NOTE) Some attributes are not given arguments in this group but can be set in
other ways. To set the [project] attribute: provide the argument [\-\-device] on
the command line with a fully specified name; provide the argument [\-\-project]
on the command line; set the property [core/project]. This must be specified.

.RS 2m
.TP 2m
\fB\-\-device\fR=\fIDEVICE\fR
ID of the device or fully qualified identifier for the device. This flag must be
specified if any of the other arguments in this group are specified.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The Cloud region for the device.

.TP 2m
\fB\-\-registry\fR=\fIREGISTRY\fR
The device registry for the device.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud iot devices configs get\-value
$ gcloud alpha iot devices configs get\-value
.RE

