
.TH "GCLOUD_BETA_CONTAINER_MEMBERSHIPS" 1



.SH "NAME"
.HP
gcloud beta container memberships \- manage Google Kubernetes Hub memberships



.SH "SYNOPSIS"
.HP
\f5gcloud beta container memberships\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage Google Kubernetes Hub memberships.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(BETA)\fR Create a new membership.

.TP 2m
\fBdelete\fR
\fB(BETA)\fR Delete a membership.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe a membership.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List memberships.

.TP 2m
\fBregister\fR
\fB(BETA)\fR Registers a cluster with Google Cloud Platform.

.TP 2m
\fBunregister\fR
\fB(BETA)\fR Unregisters a cluster from Google Cloud Platform.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR Update a membership.


.RE
.sp

.SH "EXAMPLES"

Create a membership:

.RS 2m
$ gcloud container memberships create a\-membership
    \-\-description="Description of a\-membership."
.RE

Check the status of a membership:

.RS 2m
$ gcloud container memberships describe a\-membership
.RE

List the memberships in a project:

.RS 2m
$ gcloud container memberships list
.RE

Delete a membership:

.RS 2m
$ gcloud container memberships delete a\-membership
.RE

Register a cluster referenced from the default kubeconfig file, installing the
Connect agent:

.RS 2m
$ gcloud beta container memberships register my\-cluster            \e
   \-\-context=my\-cluster\-context             \e
  \-\-service\-account\-key\-file=/tmp/keyfile.json
.RE

Upgrade the Connect agent in a cluster:

.RS 2m
$ gcloud beta container memberships register my\-cluster            \e
   \-\-context=my\-cluster\-context             \e
  \-\-service\-account\-key\-file=/tmp/keyfile.json
.RE

Register a cluster and output a manifest that can be used to install the Connect
agent:

.RS 2m
$ gcloud beta container memberships register my\-cluster            \e
   \-\-context=my\-cluster\-context             \e
  \-\-manifest\-output\-file=/tmp/manifest.yaml             \e
  \-\-service\-account\-key\-file=/tmp/keyfile.json
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha container memberships
.RE

