
.TH "GCLOUD_ALPHA_DATABASE\-MIGRATION" 1



.SH "NAME"
.HP
gcloud alpha database\-migration \- manage Cloud Database Migration Service resources



.SH "SYNOPSIS"
.HP
\f5gcloud alpha database\-migration\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Commands for managing Cloud Database Migration Service resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBconnection\-profiles\fR
\fB(ALPHA)\fR Manage Cloud Database Migration Service connection profiles.

.TP 2m
\fBmigration\-jobs\fR
\fB(ALPHA)\fR Manage Cloud Database Migration Service migration jobs.

.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Manage Cloud Database Migration Service operations.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

