
.TH "GCLOUD_ALPHA_SOURCE_PROJECT\-CONFIGS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha source project\-configs describe \- show details about the configuration of a project



.SH "SYNOPSIS"
.HP
\f5gcloud alpha source project\-configs describe\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Show details about the configuration of a project.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBsourcerepo/v1\fR API. The full documentation for this
API can be found at: https://cloud.google.com/source\-repositories/docs/apis



.SH "EXAMPLES"

To show the current configuration of the current project run:

.RS 2m
$ gcloud alpha source project\-configs describe
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. These variants are also available:

.RS 2m
$ gcloud source project\-configs describe
$ gcloud beta source project\-configs describe
.RE

