
.TH "GCLOUD_TASKS_QUEUES" 1



.SH "NAME"
.HP
gcloud tasks queues \- manage Cloud Tasks queues



.SH "SYNOPSIS"
.HP
\f5gcloud tasks queues\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Commands for managing Google Cloud Tasks queues.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding for a tasks queue.

.TP 2m
\fBcreate\fR
Create a Cloud Tasks queue.

.TP 2m
\fBdelete\fR
Delete a queue.

.TP 2m
\fBdescribe\fR
Show details about a queue.

.TP 2m
\fBget\-iam\-policy\fR
Get the IAM policy for a queue.

.TP 2m
\fBlist\fR
List all queues.

.TP 2m
\fBpause\fR
Pause a queue.

.TP 2m
\fBpurge\fR
Purge a queue by deleting all of its tasks.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove IAM policy binding of tasks queue.

.TP 2m
\fBresume\fR
Request to resume a paused or disabled queue.

.TP 2m
\fBset\-iam\-policy\fR
Set the IAM policy for a queue.

.TP 2m
\fBupdate\fR
Update a Cloud Tasks queue.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha tasks queues
$ gcloud beta tasks queues
.RE

