
.TH "GCLOUD_ALPHA_REDIS_INSTANCES" 1



.SH "NAME"
.HP
gcloud alpha redis instances \- manage Cloud Memorystore Redis instances



.SH "SYNOPSIS"
.HP
\f5gcloud alpha redis instances\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Memorystore Redis instances.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Create a Memorystore Redis instance.

.TP 2m
\fBdelete\fR
\fB(ALPHA)\fR Delete a Redis instance.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Show metadata for a Memorystore Redis instance.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Memorystore Redis instances.

.TP 2m
\fBupdate\fR
\fB(ALPHA)\fR Update Memorystore Redis instances.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta redis instances
.RE

