
.TH "GCLOUD_BETA_COMPUTE_ROUTERS_NATS_DELETE" 1



.SH "NAME"
.HP
gcloud beta compute routers nats delete \- remove a NAT from a Compute Engine router



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute routers nats delete\fR \fINAME\fR [\fINAME\fR\ ...] \fB\-\-router\fR=\fIROUTER\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute routers nats delete\fR is used to delete a
NAT on a Compute Engine router.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
Name of the NATs to delete


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-router\fR=\fIROUTER\fR
The Router to use for NAT.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the NATs to delete. If not specified, you may be prompted to select a
region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To delete NAT 'n1' in router 'r1', run:

.RS 2m
$ gcloud beta compute routers nats delete n1 \-\-router=r1 \e
    \-\-region=us\-central1
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute routers nats delete
$ gcloud alpha compute routers nats delete
.RE

