
.TH "GCLOUD_BETA_ENDPOINTS_SERVICES_DEPLOY" 1



.SH "NAME"
.HP
gcloud beta endpoints services deploy \- deploys a service configuration for the given service name



.SH "SYNOPSIS"
.HP
\f5gcloud beta endpoints services deploy\fR \fISERVICE_CONFIG_FILE\fR [\fISERVICE_CONFIG_FILE\fR\ ...] [\fB\-\-async\fR] [\fB\-\-force\fR,\ \fB\-f\fR] [\fB\-\-validate\-only\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR This command is used to deploy a service configuration for a
service to Google Service Management. As input, it takes one or more paths to
service configurations that should be uploaded. These configuration files can be
Proto Descriptors, Open API (Swagger) specifications, or Google Service
Configuration files in JSON or YAML formats.

If a service name is present in multiple configuration files (given in the
\f5host\fR field in OpenAPI specifications or the \f5name\fR field in Google
Service Configuration files), the first one will take precedence.

When deploying a new service configuration to an already\-existing service, some
safety checks will be made comparing the new configuration to the active
configuration. If any actionable advice is provided, it will be printed out to
the log, and the deployment will be halted. It is recommended that these
warnings be addressed before proceeding, but they can be overridden with the
\-\-force flag.

This command will block until deployment is complete unless the \f5\-\-async\fR
flag is passed.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE_CONFIG_FILE\fR [\fISERVICE_CONFIG_FILE\fR ...]
The service configuration file (or files) containing the API specification to
upload. Proto Descriptors, Open API (Swagger) specifications, and Google Service
Configuration files in JSON and YAML formats are acceptable.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.

.TP 2m
\fB\-\-force\fR, \fB\-f\fR
Force the deployment even if any hazardous changes to the service configuration
are detected.

.TP 2m
\fB\-\-validate\-only\fR
If included, the command validates the service configuration(s), but does not
deploy them. The service must exist in order to validate the configuration(s).


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "EXAMPLES"

To deploy a single Open API service configuration, run:

.RS 2m
$ gcloud beta endpoints services deploy ~/my_app/openapi.json
.RE

To run the deployment asynchronously (non\-blocking), run:

.RS 2m
$ gcloud beta endpoints services deploy ~/my_app/openapi.json \-\-async
.RE

To deploy a service config with a Proto, run:

.RS 2m
$ gcloud beta endpoints services deploy \e
    ~/my_app/service\-config.yaml ~/my_app/service\-protos.pb
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud endpoints services deploy
$ gcloud alpha endpoints services deploy
.RE

