
.TH "GCLOUD_BETA_COMPUTE_PROJECT\-INFO_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta compute project\-info describe \- describe the Google Compute Engine project resource



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute project\-info describe\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute project\-info describe\fR displays all data
associated with the Google Compute Engine project resource. The project resource
contains data such as global quotas, common instance metadata, and the project's
creation time.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute project\-info describe
$ gcloud alpha compute project\-info describe
.RE

