
.TH "GCLOUD_BETA_BIGTABLE_INSTANCES_UPDATE" 1



.SH "NAME"
.HP
gcloud beta bigtable instances update \- modify an existing Bigtable instance



.SH "SYNOPSIS"
.HP
\f5gcloud beta bigtable instances update\fR \fIINSTANCE\fR [\fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Modify an existing Bigtable instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
ID of the instance.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR
Friendly name of the instance.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice.

