
.TH "GCLOUD_ENDPOINTS" 1



.SH "NAME"
.HP
gcloud endpoints \- create, enable and manage API services



.SH "SYNOPSIS"
.HP
\f5gcloud endpoints\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Google Service Management is an infrastructure service of Google Cloud Platform
that manages other APIs and services, including Google's own Cloud Platform
services and their APIs, and services created using Google Cloud Endpoints.

More information on Service Management can be found here:
https://cloud.google.com/service\-management and detailed documentation can be
found here: https://cloud.google.com/service\-management/docs/



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBconfigs\fR
View configurations for various services.

.TP 2m
\fBoperations\fR
Manage Operation for various services.

.TP 2m
\fBservices\fR
Manage Services.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha endpoints
$ gcloud beta endpoints
.RE

