
.TH "GCLOUD_BETA_IDENTITY_GROUPS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta identity groups describe \- describe an existing group



.SH "SYNOPSIS"
.HP
\f5gcloud beta identity groups describe\fR \fIEMAIL\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Describe an existing group.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIEMAIL\fR
The email address of the group being described.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBcloudidentity/v1beta1\fR API. The full documentation
for this API can be found at: https://cloud.google.com/identity/



.SH "EXAMPLES"

To describe a group:

.RS 2m
$ gcloud beta identity groups describe eng\-discuss@foo.com
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud identity groups describe
$ gcloud alpha identity groups describe
.RE

