
.TH "GCLOUD_ALPHA_COMPUTE_TPUS" 1



.SH "NAME"
.HP
gcloud alpha compute tpus \- list, create, and delete Cloud TPUs



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute tpus\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR List, create, and delete Cloud TPUs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBaccelerator\-types\fR
\fB(ALPHA)\fR List or Describe Available Cloud TPU accelerator types.

.TP 2m
\fBlocations\fR
\fB(ALPHA)\fR List or Describe Available Cloud TPU Locations.

.TP 2m
\fBversions\fR
\fB(ALPHA)\fR Explore Available Tensorflow versions for Cloud TPUs.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Create a new Cloud TPU.

.TP 2m
\fBdelete\fR
\fB(ALPHA)\fR Deletes a Cloud TPU.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe a Cloud TPU.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Cloud TPUs.

.TP 2m
\fBreimage\fR
\fB(ALPHA)\fR Reimages the OS on a Cloud TPU.

.TP 2m
\fBstart\fR
\fB(ALPHA)\fR Start a Cloud TPU.

.TP 2m
\fBstop\fR
\fB(ALPHA)\fR Stop a Cloud TPU.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. This variant is also available:

.RS 2m
$ gcloud beta compute tpus
.RE

