
.TH "GCLOUD_ALPHA_RECOMMENDER_INSIGHTS_MARK\-ACCEPTED" 1



.SH "NAME"
.HP
gcloud alpha recommender insights mark\-accepted \- mark an insight's state as ACCEPTED



.SH "SYNOPSIS"
.HP
\f5gcloud alpha recommender insights mark\-accepted\fR \fIINSIGHT\fR \fB\-\-etag\fR=\fIetag\fR (\fB\-\-billing\-account\fR=\fIBILLING_ACCOUNT\fR\ |\ \fB\-\-folder\fR=\fIFOLDER_ID\fR\ |\ \fB\-\-organization\fR=\fIORGANIZATION_ID\fR\ |\ \fB\-\-project\fR=\fIPROJECT_ID\fR) [\fB\-\-insight\-type\fR=\fIInsight\fR\ \fIType\fR] [\fB\-\-location\fR=\fILOCATION\fR] [\fB\-\-state\-metadata\fR=\fIKEY\fR=\fIVALUE\fR,[\fIKEY\fR=\fIVALUE\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Mark an insight's state as ACCEPTED. Can be applied to insights in
ACTIVE or ACCEPTED state. we currently support project, billing_account, folder
and organization.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSIGHT\fR
Insight id which will be marked as accepted


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-etag\fR=\fIetag\fR
Etag of a insight

.TP 2m

Resource that is associated with cloud entity type. Currently four mutually
exclusive flags are supported, \-\-project, \-\-billing\-account, \-\-folder,
\-\-organization. Exactly one of these must be specified:

.RS 2m
.TP 2m
\fB\-\-billing\-account\fR=\fIBILLING_ACCOUNT\fR
The Google Cloud Platform Billing Account ID to use for this invocation.

.TP 2m
\fB\-\-folder\fR=\fIFOLDER_ID\fR
Folder ID to use for this invocation.

.TP 2m
\fB\-\-organization\fR=\fIORGANIZATION_ID\fR
The Google Cloud Platform Organization ID to use for this invocation.

.TP 2m
\fB\-\-project\fR=\fIPROJECT_ID\fR
The Google Cloud Platform Project Number to use for this invocation.

The Google Cloud Platform project ID to use for this invocation. If omitted,
then the current project is assumed; the current project can be listed using
\f5gcloud config list \-\-format='text(core.project)'\fR and can be set using
\f5gcloud config set project PROJECTID\fR.

\f5\-\-project\fR and its fallback \f5core/project\fR property play two roles in
the invocation. It specifies the project of the resource to operate on. It also
specifies the project for API enablement check, quota, and billing. To specify a
different project for quota and billing, use \f5\-\-billing\-project\fR or
\f5billing/quota_project\fR property.


.RE
.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-insight\-type\fR=\fIInsight\fR \fIType\fR
Insight Type of the insights

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
Location

.TP 2m
\fB\-\-state\-metadata\fR=\fIKEY\fR=\fIVALUE\fR,[\fIKEY\fR=\fIVALUE\fR,...]
State metadata for recommendation, in format of
\-\-state\-metadata=key1=value1,key2=value2


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To mark an insight as ACCEPTED:

.RS 2m
$ gcloud alpha recommender insights mark\-accepted abcd\-1234 \e
    \-\-project=project\-name \-\-location=global \e
    \-\-insight\-type=google.compute.firewall.Insight \-\-etag=abc123
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. These variants are also available:

.RS 2m
$ gcloud recommender insights mark\-accepted
$ gcloud beta recommender insights mark\-accepted
.RE

