
.TH "GCLOUD_BETA_DATAFLOW_JOBS" 1



.SH "NAME"
.HP
gcloud beta dataflow jobs \- a group of subcommands for working with Dataflow jobs



.SH "SYNOPSIS"
.HP
\f5gcloud beta dataflow jobs\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR A group of subcommands for working with Dataflow jobs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcancel\fR
\fB(BETA)\fR Cancels all jobs that match the command line arguments.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Outputs the Job object resulting from the Get API.

.TP 2m
\fBdrain\fR
\fB(BETA)\fR Drains all jobs that match the command line arguments.

.TP 2m
\fBexport\-steps\fR
\fB(BETA)\fR Exports information about the steps for the given job.

.TP 2m
\fBlist\fR
\fB(BETA)\fR Lists all jobs in a particular project, optionally filtered by
region.

.TP 2m
\fBrun\fR
\fB(BETA)\fR Runs a job from the specified path.

.TP 2m
\fBshow\fR
\fB(BETA)\fR Shows a short description of the given job.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud dataflow jobs
$ gcloud alpha dataflow jobs
.RE

