
.TH "GCLOUD_ALPHA_SOURCE_PROJECT\-CONFIGS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha source project\-configs describe \- show details about the configuration of a project



.SH "SYNOPSIS"
.HP
\f5gcloud alpha source project\-configs describe\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Show details about the configuration of a project.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBsourcerepo/v1\fR API. The full documentation for this
API can be found at: https://cloud.google.com/source\-repositories/docs/apis



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. This variant is also available:

.RS 2m
$ gcloud beta source project\-configs describe
.RE

