
.TH "GCLOUD_BETA_ERROR\-REPORTING_EVENTS_DELETE" 1



.SH "NAME"
.HP
gcloud beta error\-reporting events delete \- deletes all error events of the project



.SH "SYNOPSIS"
.HP
\f5gcloud beta error\-reporting events delete\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Deletes all error events of the project. All error events which are
stored for the given project are deleted and the error counters are reset to
zero.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice.

