
.TH "GCLOUD_IDENTITY_GROUPS_MEMBERSHIPS" 1



.SH "NAME"
.HP
gcloud identity groups memberships \- manage Cloud Identity Groups Memberships



.SH "SYNOPSIS"
.HP
\f5gcloud identity groups memberships\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Commands for managing Cloud Identity Groups Memberships.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha identity groups memberships
$ gcloud beta identity groups memberships
.RE

