
.TH "GCLOUD_BETA_RUNTIME\-CONFIG_CONFIGS_VARIABLES_GET\-VALUE" 1



.SH "NAME"
.HP
gcloud beta runtime\-config configs variables get\-value \- output values of variable resources



.SH "SYNOPSIS"
.HP
\f5gcloud beta runtime\-config configs variables get\-value\fR \fINAME\fR \fB\-\-config\-name\fR=\fICONFIG_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR This command prints only the value of the variable resource with
the specified name, and does not append a trailing newline character. It can be
used as part of shell expansions.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The variable name.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-config\-name\fR=\fICONFIG_NAME\fR
The name of the configuration resource to use.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To print the value of a variable named "my\-var", run:

.RS 2m
$ gcloud beta runtime\-config configs variables get\-value \e
    \-\-config\-name my\-config my\-var
.RE

Values will be automatically base64\-decoded.



.SH "NOTES"

This command is currently in BETA and may change without notice.

