
.TH "GCLOUD_ALPHA_SERVICE\-DIRECTORY" 1



.SH "NAME"
.HP
gcloud alpha service\-directory \- command groups for Service Directory



.SH "SYNOPSIS"
.HP
\f5gcloud alpha service\-directory\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Command groups for Service Directory.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBendpoints\fR
\fB(ALPHA)\fR Manage Service Directory endpoints.

.TP 2m
\fBlocations\fR
\fB(ALPHA)\fR Manage Service Directory locations.

.TP 2m
\fBnamespaces\fR
\fB(ALPHA)\fR Manage Service Directory services.

.TP 2m
\fBservices\fR
\fB(ALPHA)\fR Manage Service Directory services.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta service\-directory
.RE

