
.TH "GCLOUD_BETA_SECRETS_REPLICATION" 1



.SH "NAME"
.HP
gcloud beta secrets replication \- manage secret replication



.SH "SYNOPSIS"
.HP
\f5gcloud beta secrets replication\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage secret replication on Google Cloud.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBget\fR
\fB(BETA)\fR Describe a secret's replication.

.TP 2m
\fBset\fR
\fB(BETA)\fR Set a secret's replication.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR Update a secret replica's metadata.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice.

