
.TH "GCLOUD_BETA_BIGTABLE_INSTANCES_DELETE" 1



.SH "NAME"
.HP
gcloud beta bigtable instances delete \- delete an existing Bigtable instance



.SH "SYNOPSIS"
.HP
\f5gcloud beta bigtable instances delete\fR \fIINSTANCE\fR [\fIINSTANCE\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Delete an existing Bigtable instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR [\fIINSTANCE\fR ...]
ID of the instances.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha bigtable instances delete
.RE

