
.TH "GCLOUD_COMPUTE_TARGET\-GRPC\-PROXIES_DELETE" 1



.SH "NAME"
.HP
gcloud compute target\-grpc\-proxies delete \- delete one or more target gRPC proxy



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-grpc\-proxies delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-grpc\-proxies delete\fR deletes one or more target
gRPC proxies.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
Names of the target gRPC proxies to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

Delete a global target gRPC proxy by running:

.RS 2m
$ gcloud compute target\-grpc\-proxies delete PROXY_NAME
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute target\-grpc\-proxies delete
$ gcloud beta compute target\-grpc\-proxies delete
.RE

