
.TH "GCLOUD_NETWORK\-MANAGEMENT" 1



.SH "NAME"
.HP
gcloud network\-management \- manage Network Management resources



.SH "SYNOPSIS"
.HP
\f5gcloud network\-management\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Network Management resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBconnectivity\-tests\fR
Manage Network Management ConnectivityTests.

.TP 2m
\fBoperations\fR
Manage Network Management operations.


.RE
.sp

.SH "NOTES"

This variant is also available:

.RS 2m
$ gcloud beta network\-management
.RE

