
.TH "GCLOUD_ALPHA_DATA\-CATALOG_CRAWLER\-RUNS" 1



.SH "NAME"
.HP
gcloud alpha data\-catalog crawler\-runs \- manage crawler runs in Cloud Data Catalog



.SH "SYNOPSIS"
.HP
\f5gcloud alpha data\-catalog crawler\-runs\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage crawler runs in Cloud Data Catalog.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe a Cloud Data Catalog crawler run.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Cloud Data Catalog crawler runs.

.TP 2m
\fBstart\fR
\fB(ALPHA)\fR Start a Cloud Data Catalog crawler run.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

