
.TH "GCLOUD_BETA_ASSET" 1



.SH "NAME"
.HP
gcloud beta asset \- manage the Cloud Asset Inventory



.SH "SYNOPSIS"
.HP
\f5gcloud beta asset\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage the Cloud Asset Inventory.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBoperations\fR
\fB(BETA)\fR Manage Cloud Asset Inventory operations.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBexport\fR
\fB(BETA)\fR Export the cloud assets to Google Cloud Storage.

.TP 2m
\fBget\-history\fR
\fB(BETA)\fR Get the update history of assets that overlaps a time window.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud asset
$ gcloud alpha asset
.RE

