
.TH "GCLOUD_ALPHA_DLP_IMAGES_INSPECT" 1



.SH "NAME"
.HP
gcloud alpha dlp images inspect \- finds potentially sensitive data in image content



.SH "SYNOPSIS"
.HP
\f5gcloud alpha dlp images inspect\fR \fIIMAGE\fR [\fB\-\-exclude\-info\-types\fR] [\fB\-\-include\-quote\fR] [\fB\-\-info\-types\fR=[\fIINFOTYPE\fR,...]] [\fB\-\-max\-findings\fR=\fIMAX_FINDINGS\fR] [\fB\-\-min\-likelihood\fR=\fIMIN_LIKELIHOOD\fR;\ default="possible"] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Finds potentially sensitive data in image content.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE\fR
Image file to search for sensitive info. The file type must be one of PNG, JPEG,
SVG, or BMP.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-exclude\-info\-types\fR
Whether or not to exclude type information of the findings. Type information is
included by default.

.TP 2m
\fB\-\-include\-quote\fR
If True, a contextual quote from the data that triggered a finding is included
in the response. Even if the content is not text, it may be converted to a
textual representation in the response. For example, given the input value 'My
phone number is (415) 555\-0890' and a search for the infoType PHONE_NUMBER, the
contextual quote would be '(415) 555\-0890.'

.TP 2m
\fB\-\-info\-types\fR=[\fIINFOTYPE\fR,...]
Which infoTypes to scan input for. The values must correspond to infoType values
found in documentation. For more information about valid infoTypes, see
infoTypes Reference (https://cloud.google.com/dlp/docs/infotypes\-reference)

.TP 2m
\fB\-\-max\-findings\fR=\fIMAX_FINDINGS\fR
Maximum number of findings that will be returned per execution.

If not specified, no limits are applied.

.TP 2m
\fB\-\-min\-likelihood\fR=\fIMIN_LIKELIHOOD\fR; default="possible"
Only return findings equal to or above this threshold. \fIMIN_LIKELIHOOD\fR must
be one of: \fBlikely\fR, \fBpossible\fR, \fBunlikely\fR, \fBvery\-likely\fR,
\fBvery\-unlikely\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBdlp/v2\fR API. The full documentation for this API can
be found at: https://cloud.google.com/dlp/docs/



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

