
.TH "GCLOUD_ML_SPEECH_OPERATIONS_WAIT" 1



.SH "NAME"
.HP
gcloud ml speech operations wait \- poll long\-running speech recognition operation until it completes



.SH "SYNOPSIS"
.HP
\f5gcloud ml speech operations wait\fR \fIOPERATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Poll a long\-running speech recognition operation until it completes. When the
operation is complete, this command will display the results of the
transcription.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Operation resource \- The ID of the operation to wait for. This represents a
Cloud resource. This must be specified.

.RS 2m
.TP 2m
\fIOPERATION\fR
ID of the operation or fully qualified identifier for the operation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBspeech/v1\fR API. The full documentation for this API
can be found at:
https://cloud.google.com/speech\-to\-text/docs/quickstart\-protocol



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha ml speech operations wait
$ gcloud beta ml speech operations wait
.RE

