
.TH "GCLOUD_COMPUTE_SHARED\-VPC_DISABLE" 1



.SH "NAME"
.HP
gcloud compute shared\-vpc disable \- disable the given project as a shared VPC host



.SH "SYNOPSIS"
.HP
\f5gcloud compute shared\-vpc disable\fR \fIPROJECT_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

That is, after running this command, this project will not be able to share VPC
networks to other projects.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
ID for the project to disable as a shared VPC host


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "EXAMPLES"

To disable the project \f5myproject\fR as a shared VPC host, run:

.RS 2m
$ gcloud compute shared\-vpc disable myproject
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute shared\-vpc disable
$ gcloud beta compute shared\-vpc disable
.RE

