
.TH "GCLOUD_COMPUTE_RESOURCE\-POLICIES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute resource\-policies describe \- describe a Compute Engine resource policy



.SH "SYNOPSIS"
.HP
\f5gcloud compute resource\-policies describe\fR \fINAME\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe a Compute Engine resource policy.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the resource policy to operate on.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the resource policy to operate on. If not specified, you may be
prompted to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

The following command shows the details of a Compute Engine resource policy.

.RS 2m
$ gcloud compute resource\-policies describe my\-resource\-policy \e
    \-\-region=REGION
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute resource\-policies describe
$ gcloud beta compute resource\-policies describe
.RE

