
.TH "GCLOUD_GAME_SERVERS_CONFIGS" 1



.SH "NAME"
.HP
gcloud game servers configs \- deploy and manage Cloud Game Server Configs



.SH "SYNOPSIS"
.HP
\f5gcloud game servers configs\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Deploy and manage Cloud Game Server Configs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a Game Server Config.

.TP 2m
\fBdelete\fR
Delete a Game Server Config.

.TP 2m
\fBdescribe\fR
Describe a Game Server Config.

.TP 2m
\fBlist\fR
List Configs.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha game servers configs
$ gcloud beta game servers configs
.RE

