
.TH "GCLOUD_BETA_BIGTABLE_APP\-PROFILES" 1



.SH "NAME"
.HP
gcloud beta bigtable app\-profiles \- manage Cloud Bigtable app profiles



.SH "SYNOPSIS"
.HP
\f5gcloud beta bigtable app\-profiles\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Manage Cloud Bigtable app profiles.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(BETA)\fR Create a new Bigtable app profile.

.TP 2m
\fBdelete\fR
\fB(BETA)\fR Delete a Bigtable app profile.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe an existing Bigtable app profile.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List Bigtable app profiles.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR Update a Bigtable app profile.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud bigtable app\-profiles
$ gcloud alpha bigtable app\-profiles
.RE

