
.TH "GCLOUD_ALPHA_CONTAINER_HUB_MULTI\-CLUSTER\-SERVICES" 1



.SH "NAME"
.HP
gcloud alpha container hub multi\-cluster\-services \- manage MultiClusterServiceDiscovery Feature



.SH "SYNOPSIS"
.HP
\f5gcloud alpha container hub multi\-cluster\-services\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage MultiClusterServiceDiscovery Feature.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe the status of MultiClusterServices Feature resource.

.TP 2m
\fBdisable\fR
\fB(ALPHA)\fR Disable MultiClusterServices Feature.

.TP 2m
\fBenable\fR
\fB(ALPHA)\fR Enable MultiClusterServices Feature.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

