
.TH "GCLOUD_ALPHA_ML_VISION_SUGGEST\-CROP" 1



.SH "NAME"
.HP
gcloud alpha ml vision suggest\-crop \- suggest a bounding box in an image



.SH "SYNOPSIS"
.HP
\f5gcloud alpha ml vision suggest\-crop\fR \fIIMAGE_PATH\fR [\fB\-\-aspect\-ratios\fR=[\fIASPECT_RATIOS\fR,...]] [\fB\-\-model\-version\fR=\fIMODEL_VERSION\fR;\ default="builtin/stable"] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Returns the coordinates of a bounding box that surrounds the
dominant object or face in an image.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE_PATH\fR
The path to the image to be analyzed. This can be either a local path or a URL.
If you provide a local file, the contents will be sent directly to Google Cloud
Vision. If you provide a URL, it must be in Google Cloud Storage format
(gs://bucket/object) or an HTTP URL (http://... or https://...)


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-aspect\-ratios\fR=[\fIASPECT_RATIOS\fR,...]
A list of aspect ratio hints for the suggested bounding box. Aspect ratios may
be specified either as a decimal number (ex. 1.333) or as a ratio of width to
height (ex 4:3).

.TP 2m
\fB\-\-model\-version\fR=\fIMODEL_VERSION\fR; default="builtin/stable"
The model version to use for the feature. Supported values include
"builtin/stable" and "builtin/latest".


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBvision/v1\fR API. The full documentation for this API
can be found at: https://cloud.google.com/vision/



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. These variants are also available:

.RS 2m
$ gcloud ml vision suggest\-crop
$ gcloud beta ml vision suggest\-crop
.RE

