
.TH "GCLOUD_ALPHA_LIFESCIENCES" 1



.SH "NAME"
.HP
gcloud alpha lifesciences \- manage Cloud Life Sciences resources



.SH "SYNOPSIS"
.HP
\f5gcloud alpha lifesciences\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Life Sciences resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlocations\fR
\fB(ALPHA)\fR Query Cloud Life Sciences locations.

.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Manage Cloud Life Sciences operations.

.TP 2m
\fBpipelines\fR
\fB(ALPHA)\fR Commands for Life Sciences pipelines.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta lifesciences
.RE

