
.TH "GCLOUD_ALPHA_COMPUTE_IMAGES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha compute images describe \- describe a Compute Engine image



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute images describe\fR \fIIMAGE_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fBgcloud alpha compute images describe\fR displays all data
associated with a Compute Engine image in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE_NAME\fR
Name of the disk image to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud compute images describe
$ gcloud beta compute images describe
.RE

