
.TH "GCLOUD_GAME" 1



.SH "NAME"
.HP
gcloud game \- managed Cloud Game Services



.SH "SYNOPSIS"
.HP
\f5gcloud game\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Managed Cloud Game Services.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlocations\fR
Query Cloud Game Services Locations.

.TP 2m
\fBoperations\fR
Deploy and manage Cloud Game Services Operations.

.TP 2m
\fBservers\fR
Managed Cloud Game Servers.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha game
$ gcloud beta game
.RE

