
.TH "GCLOUD_COMPUTE_SSL\-POLICIES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute ssl\-policies describe \- describe a Google Compute Engine ssl policy



.SH "SYNOPSIS"
.HP
\f5gcloud compute ssl\-policies describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute ssl\-policies describe\fR is used to display all data
associated with a Google Compute Engine SSL policy in a project.

An SSL policy specifies the server\-side support for SSL features. An SSL policy
can be attached to a TargetHttpsProxy or a TargetSslProxy. This affects
connections between clients and the HTTPS or SSL proxy load balancer. SSL
policies do not affect the connection between the load balancers and the
backends.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the SSL policy to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute ssl\-policies describe
$ gcloud beta compute ssl\-policies describe
.RE

