
.TH "GCLOUD_ALPHA_ML_TRANSLATE" 1



.SH "NAME"
.HP
gcloud alpha ml translate \- cloud ML Translate command groups



.SH "SYNOPSIS"
.HP
\f5gcloud alpha ml translate\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Cloud ML Translate command groups.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBbatch\-translate\-text\fR
\fB(ALPHA)\fR Translates a large volume of text in asynchronous batch mode.

.TP 2m
\fBdetect\-language\fR
\fB(ALPHA)\fR Use the Google Cloud Translation API to detect languages.

.TP 2m
\fBget\-supported\-languages\fR
\fB(ALPHA)\fR Returns a list of supported languages for translation.

.TP 2m
\fBtranslate\-text\fR
\fB(ALPHA)\fR Use the Google Cloud Translation API to translate between
languages.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta ml translate
.RE

