
.TH "GCLOUD_AI\-PLATFORM_LOCAL" 1



.SH "NAME"
.HP
gcloud ai\-platform local \- AI Platform Local commands



.SH "SYNOPSIS"
.HP
\f5gcloud ai\-platform local\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

AI Platform Local commands.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBpredict\fR
Run prediction locally.

.TP 2m
\fBtrain\fR
Run an AI Platform training job locally.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha ai\-platform local
$ gcloud beta ai\-platform local
.RE

