
.TH "GCLOUD_ALPHA_APIGEE_APPLICATIONS" 1



.SH "NAME"
.HP
gcloud alpha apigee applications \- manage third\-party applications which call Apigee API proxies



.SH "SYNOPSIS"
.HP
\f5gcloud alpha apigee applications\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage third\-party applications which call Apigee API proxies.

\f5gcloud alpha apigee applications\fR manages applications that want to use
APIs exposed via Apigee.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe an Apigee application.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Apigee applications.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

