
.TH "GCLOUD_BETA_ML_SPEECH_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta ml speech operations describe \- get description of a long\-running speech recognition operation



.SH "SYNOPSIS"
.HP
\f5gcloud beta ml speech operations describe\fR \fIOPERATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Get information about a long\-running speech recognition operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Operation resource \- The ID of the operation to describe. This represents a
Cloud resource. This must be specified.

.RS 2m
.TP 2m
\fIOPERATION\fR
The ID of the operation or a fully qualified identifier for the operation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBspeech/v1\fR API. The full documentation for this API
can be found at:
https://cloud.google.com/speech\-to\-text/docs/quickstart\-protocol



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud ml speech operations describe
$ gcloud alpha ml speech operations describe
.RE

