
.TH "GCLOUD_BETA_COMPUTE_TARGET\-TCP\-PROXIES_DELETE" 1



.SH "NAME"
.HP
gcloud beta compute target\-tcp\-proxies delete \- delete target TCP proxies



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute target\-tcp\-proxies delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute target\-tcp\-proxies delete\fR deletes one
or more target TCP proxies.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
Names of the target TCP proxies to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute target\-tcp\-proxies delete
$ gcloud alpha compute target\-tcp\-proxies delete
.RE

