
.TH "GCLOUD_ALPHA_ASSURED" 1



.SH "NAME"
.HP
gcloud alpha assured \- commands for reading and manipulating Assured Workloads data controls



.SH "SYNOPSIS"
.HP
\f5gcloud alpha assured\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Read and manipulate Assured Workloads data controls.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Commands for reading and manipulating Assured Workloads operation
resources.

.TP 2m
\fBworkloads\fR
\fB(ALPHA)\fR Commands for reading and manipulating Assured Workloads resources.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta assured
.RE

