
.TH "GCLOUD_PUBSUB" 1



.SH "NAME"
.HP
gcloud pubsub \- manage Cloud Pub/Sub topics, subscriptions, and snapshots



.SH "SYNOPSIS"
.HP
\f5gcloud pubsub\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Pub/Sub topics, subscriptions, and snapshots.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlite\-subscriptions\fR
Manage Pub/Sub Lite subscriptions.

.TP 2m
\fBlite\-topics\fR
Manage Pub/Sub Lite topics.

.TP 2m
\fBsnapshots\fR
Manage Cloud Pub/Sub snapshots.

.TP 2m
\fBsubscriptions\fR
Manage Cloud Pub/Sub subscriptions.

.TP 2m
\fBtopics\fR
Manage Cloud Pub/Sub topics.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha pubsub
$ gcloud beta pubsub
.RE

