
.TH "GCLOUD_ALPHA_ML_VISION_DETECT\-TEXT\-PDF" 1



.SH "NAME"
.HP
gcloud alpha ml vision detect\-text\-pdf \- detect and transcribe text from PDF files stored in Google Cloud Storage



.SH "SYNOPSIS"
.HP
\f5gcloud alpha ml vision detect\-text\-pdf\fR \fIINPUT_FILE\fR \fIOUTPUT_PATH\fR [\fB\-\-batch\-size\fR=\fIBATCH_SIZE\fR] [\fB\-\-model\-version\fR=\fIMODEL_VERSION\fR;\ default="builtin/stable"] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Detect and transcribe text from PDF files stored in Google Cloud
Storage.

The Vision API accepts PDF files up to 2000 pages. Larger files will return an
error.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINPUT_FILE\fR
Google Cloud Storage location to read the input from. It must be in Google Cloud
Storage format (gs://bucket/object)

.TP 2m
\fIOUTPUT_PATH\fR
Google Cloud Storage location to store the output file. It must be in Google
Cloud Storage format (gs://bucket/object)


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-batch\-size\fR=\fIBATCH_SIZE\fR
Maximum number of response protos to put into each output JSON file on Google
Cloud Storage. The valid range is [1, 100]. If not specified, the default value
is 20.

.TP 2m
\fB\-\-model\-version\fR=\fIMODEL_VERSION\fR; default="builtin/stable"
Model version to use for the feature. \fIMODEL_VERSION\fR must be one of:
\fBbuiltin/latest\fR, \fBbuiltin/stable\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBvision/v1\fR API. The full documentation for this API
can be found at: https://cloud.google.com/vision/



.SH "EXAMPLES"

To detect text for input PDF file 'gs://my_bucket/input_file' and store output
in 'gs://my_bucket/out_put_prefix':

.RS 2m
$ gcloud alpha ml vision detect\-text\-pdf gs://my_bucket/input_file
gs://my_bucket/out_put_prefix
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. These variants are also available:

.RS 2m
$ gcloud ml vision detect\-text\-pdf
$ gcloud beta ml vision detect\-text\-pdf
.RE

