
.TH "GCLOUD_BETA_FILESTORE" 1



.SH "NAME"
.HP
gcloud beta filestore \- create and manipulate Cloud Filestore resources



.SH "SYNOPSIS"
.HP
\f5gcloud beta filestore\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR The gcloud filestore command group lets you create, configure and
manipulate Cloud Filestore instances.

With Cloud Filestore, you can take advantage of Google Cloud Platform's scale,
performance, and value to create and run managed file systems on Google
infrastructure.

More information on Cloud Filestore can be found here:
https://cloud.google.com/filestore/ and detailed documentation can be found
here: https://cloud.google.com/filestore/docs/



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBinstances\fR
\fB(BETA)\fR Manage Cloud Filestore instances.

.TP 2m
\fBlocations\fR
\fB(BETA)\fR List locations where Cloud Filestore is available.

.TP 2m
\fBoperations\fR
\fB(BETA)\fR Read and manipulate Cloud Filestore operations.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha filestore
.RE

