
.TH "GCLOUD_HEALTHCARE" 1



.SH "NAME"
.HP
gcloud healthcare \- manage Cloud Healthcare resources



.SH "SYNOPSIS"
.HP
\f5gcloud healthcare\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Healthcare resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdatasets\fR
Manage Cloud Healthcare API datasets.

.TP 2m
\fBdicom\-stores\fR
Manage Cloud Healthcare API DICOM stores.

.TP 2m
\fBfhir\-stores\fR
Manage Cloud Healthcare API FHIR stores.

.TP 2m
\fBhl7v2\-stores\fR
Manage Cloud Healthcare API HL7v2 stores.

.TP 2m
\fBoperations\fR
Manage Cloud Healthcare API operations.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha healthcare
$ gcloud beta healthcare
.RE

