
.TH "GCLOUD_BETA_COMPUTE_SECURITY\-POLICIES_EXPORT" 1



.SH "NAME"
.HP
gcloud beta compute security\-policies export \- export security policy configs into yaml files



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute security\-policies export\fR \fINAME\fR \fB\-\-file\-name\fR=\fIFILE_NAME\fR [\fB\-\-file\-format\fR=\fIFILE_FORMAT\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Export security policy configs into yaml files.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the security policy to export.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-file\-name\fR=\fIFILE_NAME\fR
The name of the file to export the security policy config to.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-file\-format\fR=\fIFILE_FORMAT\fR
The format of the file to export the security policy config to. Specify either
yaml or json. Defaults to yaml if not specified. \fIFILE_FORMAT\fR must be one
of: \fBjson\fR, \fByaml\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha compute security\-policies export
.RE

