
.TH "GCLOUD_ALPHA_MEMCACHE_OPERATIONS" 1



.SH "NAME"
.HP
gcloud alpha memcache operations \- manage Cloud Memorystore Memcached operations



.SH "SYNOPSIS"
.HP
\f5gcloud alpha memcache operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Memorystore Memcached operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdelete\fR
\fB(ALPHA)\fR Delete a Memorystore Memcached operation.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Display metadata for a Memorystore Memcached operation.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Memorystore Memcached operations.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist. This variant is also available:

.RS 2m
$ gcloud beta memcache operations
.RE

