
.TH "GCLOUD_BETA_SQL_IMPORT" 1



.SH "NAME"
.HP
gcloud beta sql import \- provides commands to import Cloud SQL instances



.SH "SYNOPSIS"
.HP
\f5gcloud beta sql import\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Provides commands to import Cloud SQL instances.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcsv\fR
\fB(BETA)\fR Imports data into a Cloud SQL instance from a CSV file.

.TP 2m
\fBsql\fR
\fB(BETA)\fR Imports data into a Cloud SQL instance from a SQL dump file.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud sql import
$ gcloud alpha sql import
.RE

