
.TH "GCLOUD_ALPHA_COMPUTE_XPN_DISABLE" 1



.SH "NAME"
.HP
gcloud alpha compute xpn disable \- disable the given project as a shared VPC host



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute xpn disable\fR \fIPROJECT_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR That is, after running this command, this project will not be able
to share VPC networks to other projects.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
ID for the project to disable as a shared VPC host


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To disable the project \f5myproject\fR as a shared VPC host, run:

.RS 2m
$ gcloud alpha compute xpn disable myproject
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. These variants are also available:

.RS 2m
$ gcloud compute xpn disable
$ gcloud beta compute xpn disable
.RE

