
.TH "GCLOUD_COMPUTE_ROUTERS_NATS_LIST" 1



.SH "NAME"
.HP
gcloud compute routers nats list \- lists the NATs on a Compute Engine router



.SH "SYNOPSIS"
.HP
\f5gcloud compute routers nats list\fR \fB\-\-router\fR=\fIROUTER\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute routers nats list\fR is used to list the NATs on a Compute
Engine router.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-router\fR=\fIROUTER\fR
The Router to use for NAT.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the NATs to list. If not specified, you may be prompted to select a
region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To list all NATs in router \f5\fIr1\fR\fR in region \f5\fIus\-central1\fR\fR,
run:

.RS 2m
$ gcloud compute routers nats list \-\-router=r1 \-\-region=us\-central1.
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute routers nats list
$ gcloud beta compute routers nats list
.RE

