
.TH "GCLOUD_BETA_ARTIFACTS_DOCKER_TAGS_ADD" 1



.SH "NAME"
.HP
gcloud beta artifacts docker tags add \- add a tag to a container image in Artifact Registry



.SH "SYNOPSIS"
.HP
\f5gcloud beta artifacts docker tags add\fR \fIDOCKER_IMAGE\fR \fIDOCKER_TAG\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Create or update a tag for a container image in Artifact Registry.

A valid Docker tag has the format of

.RS 2m
LOCATION\-docker.pkg.dev/PROJECT\-ID/REPOSITORY\-ID/IMAGE:tag
.RE

A valid container image that can be referenced by tag or digest, has the format
of

.RS 2m
LOCATION\-docker.pkg.dev/PROJECT\-ID/REPOSITORY\-ID/IMAGE:tag
LOCATION\-docker.pkg.dev/PROJECT\-ID/REPOSITORY\-ID/IMAGE@sha256:digest
.RE



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDOCKER_IMAGE\fR
Docker image \- The container image that you want to tag.

A valid container image can be referenced by tag or digest, has the format of
LOCATION\-docker.pkg.dev/PROJECT\-ID/REPOSITORY\-ID/IMAGE:tag
LOCATION\-docker.pkg.dev/PROJECT\-ID/REPOSITORY\-ID/IMAGE@sha256:digest

.TP 2m
\fIDOCKER_TAG\fR
Image tag \- The container image tag.

A valid Docker tag has the format of
LOCATION\-docker.pkg.dev/PROJECT\-ID/REPOSITORY\-ID/IMAGE:tag


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To add tag \f5my\-tag\fR to image \f5busy\-box\fR referenced by digest
\f5abcxyz\fR in \f5us\-west1\fR:

.RS 2m
$ gcloud beta artifacts docker tags add \e
    us\-west1\-docker.pkg.dev/my\-project/my\-repository/\e
busy\-box@sha256:abcxyz \e
    us\-west1\-docker.pkg.dev/my\-project/my\-repository/busy\-box:my\-tag
.RE

To add tag \f5my\-tag\fR to image \f5busy\-box\fR referenced by tag \f5latest\fR
in \f5us\-west1\fR:

.RS 2m
$ gcloud beta artifacts docker tags add \e
    us\-west1\-docker.pkg.dev/my\-project/my\-repository/\e
busy\-box:latest \e
    us\-west1\-docker.pkg.dev/my\-project/my\-repository/busy\-box:my\-tag
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha artifacts docker tags add
.RE

