
.TH "GCLOUD_DATA\-CATALOG_TAG\-TEMPLATES_FIELDS" 1



.SH "NAME"
.HP
gcloud data\-catalog tag\-templates fields \- manage tag template fields in Cloud Data Catalog



.SH "SYNOPSIS"
.HP
\f5gcloud data\-catalog tag\-templates fields\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage tag template fields in Cloud Data Catalog.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a Cloud Data Catalog tag template field.

.TP 2m
\fBdelete\fR
Delete a Cloud Data Catalog tag template field.

.TP 2m
\fBrename\fR
Rename a Cloud Data Catalog tag template field.

.TP 2m
\fBupdate\fR
Update a Cloud Data Catalog tag template field.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha data\-catalog tag\-templates fields
$ gcloud beta data\-catalog tag\-templates fields
.RE

