
.TH "GCLOUD_BETA_COMPUTE_TARGET\-TCP\-PROXIES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta compute target\-tcp\-proxies describe \- display detailed information about a target TCP proxy



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute target\-tcp\-proxies describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute target\-tcp\-proxies describe\fR displays
all data associated with a target TCP proxy in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the target TCP proxy to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute target\-tcp\-proxies describe
$ gcloud alpha compute target\-tcp\-proxies describe
.RE

