
.TH "GCLOUD_ALPHA_SOURCE_REPOS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud alpha source repos set\-iam\-policy \- set the IAM policy for the named repository



.SH "SYNOPSIS"
.HP
\f5gcloud alpha source repos set\-iam\-policy\fR \fIREPOSITORY_NAME\fR \fIPOLICY_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command sets the IAM policy for the given repository from the
policy in the provided file.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIREPOSITORY_NAME\fR
Name of the repository.

.TP 2m
\fIPOLICY_FILE\fR
JSON or YAML file with IAM policy. See
https://cloud.google.com/resource\-manager/reference/rest/Shared.Types/Policy


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To set the IAM policy, issue the following command:

.RS 2m
$ gcloud alpha source repos set\-iam\-policy REPOSITORY_NAME \e
    POLICY_FILE
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud source repos set\-iam\-policy
$ gcloud beta source repos set\-iam\-policy
.RE

