
.TH "GCLOUD_BETA_COMPUTE_INTERCONNECTS_LOCATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta compute interconnects locations describe \- describe a Google Compute Engine interconnect location



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute interconnects locations describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Displays all data associated with Google Compute Engine
interconnect location in a project.

Example of usage: $ gcloud beta compute interconnects locations describe
my\-location



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the interconnect location to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute interconnects locations describe
$ gcloud alpha compute interconnects locations describe
.RE

