
.TH "GCLOUD_COMPUTE_OS\-CONFIG" 1



.SH "NAME"
.HP
gcloud compute os\-config \- manage OS Config tasks for Compute Engine VM instances



.SH "SYNOPSIS"
.HP
\f5gcloud compute os\-config\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage OS Config tasks for Compute Engine VM instances.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBpatch\-deployments\fR
Manage guest OS patch deployments for Compute Engine VM instances.

.TP 2m
\fBpatch\-jobs\fR
Manage OS patches for Compute Engine VMs.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute os\-config
$ gcloud beta compute os\-config
.RE

