
.TH "GCLOUD_ALPHA_MONITORING_CHANNEL\-DESCRIPTORS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha monitoring channel\-descriptors describe \- describe a notification channel descriptor



.SH "SYNOPSIS"
.HP
\f5gcloud alpha monitoring channel\-descriptors describe\fR \fIDESCRIPTOR\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Describe a notification channel descriptor.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Channel descriptor resource \- The notification channel descriptor to describe.
This represents a Cloud resource. (NOTE) Some attributes are not given arguments
in this group but can be set in other ways. To set the [project] attribute: Set
the property [core/project] or provide the flag [\-\-project] on the command
line. This must be specified.

.RS 2m
.TP 2m
\fIDESCRIPTOR\fR
The ID of the channel_descriptor or a fully qualified identifier for the
channel_descriptor.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBmonitoring/v3\fR API. The full documentation for this
API can be found at: https://cloud.google.com/monitoring/api/



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/.

