
.TH "GCLOUD_COMPUTE_SOLE\-TENANCY" 1



.SH "NAME"
.HP
gcloud compute sole\-tenancy \- read and manage Google Compute Engine sole\-tenancy resources



.SH "SYNOPSIS"
.HP
\f5gcloud compute sole\-tenancy\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manage Google Compute Engine sole\-tenancy resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBnode\-groups\fR
Read Google Compute Engine sole\-tenancy node groups.

.TP 2m
\fBnode\-templates\fR
Read and manage Google Compute Engine sole\-tenancy node templates.

.TP 2m
\fBnode\-types\fR
Read Google Compute Engine sole\-tenancy node types.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha compute sole\-tenancy
$ gcloud beta compute sole\-tenancy
.RE

