
.TH "GCLOUD_BETA_APP_MIGRATE\-CONFIG_DISPATCH\-XML\-TO\-YAML" 1



.SH "NAME"
.HP
gcloud beta app migrate\-config dispatch\-xml\-to\-yaml \- translates a dispatch.xml into dispatch.yaml



.SH "SYNOPSIS"
.HP
\f5gcloud beta app migrate\-config dispatch\-xml\-to\-yaml\fR \fIXML_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Convert a dispatch.xml file to dispatch.yaml.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIXML_FILE\fR
Path to the dispatch.xml file.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice.

