
.TH "GCLOUD_BETA_ML_SPEECH_OPERATIONS" 1



.SH "NAME"
.HP
gcloud beta ml speech operations \- interact with Google Cloud Speech operations



.SH "SYNOPSIS"
.HP
\f5gcloud beta ml speech operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Get information about Google Cloud Speech long\-running operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Get description of a long\-running speech recognition operation.

.TP 2m
\fBwait\fR
\fB(BETA)\fR Poll long\-running speech recognition operation until it completes.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud ml speech operations
$ gcloud alpha ml speech operations
.RE

