
.TH "GCLOUD_ALPHA_EMULATORS" 1



.SH "NAME"
.HP
gcloud alpha emulators \- set up your local development environment using emulators



.SH "SYNOPSIS"
.HP
\f5gcloud alpha emulators\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Set up your local development environment using emulators.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBbigtable\fR
\fB(ALPHA)\fR Manage your local Bigtable emulator.

.TP 2m
\fBdatastore\fR
\fB(ALPHA)\fR Manage your local datastore emulator.

.TP 2m
\fBpubsub\fR
\fB(ALPHA)\fR Manage your local pubsub emulator.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBstart\fR
\fB(ALPHA)\fR Start a number of emulators behind a proxy.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. This variant is also available:

.RS 2m
$ gcloud beta emulators
.RE

