
.TH "GCLOUD_ALPHA_SQL_OPERATIONS_WAIT" 1



.SH "NAME"
.HP
gcloud alpha sql operations wait \- waits for one or more operations to complete



.SH "SYNOPSIS"
.HP
\f5gcloud alpha sql operations wait\fR \fIOPERATION\fR [\fIOPERATION\fR\ ...] [\fB\-\-timeout\fR=\fITIMEOUT\fR;\ default=300] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Waits for one or more operations to complete.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR [\fIOPERATION\fR ...]
An identifier that uniquely identifies the operation.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-timeout\fR=\fITIMEOUT\fR; default=300
Maximum number of seconds to wait for an operation to complete. By default, wait
for 300s. Set to \fBunlimited\fR to wait indefinitely.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. These variants are also available:

.RS 2m
$ gcloud sql operations wait
$ gcloud beta sql operations wait
.RE

