
.TH "GCLOUD_ALPHA_BIGTABLE" 1



.SH "NAME"
.HP
gcloud alpha bigtable \- manage your Cloud Bigtable storage



.SH "SYNOPSIS"
.HP
\f5gcloud alpha bigtable\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage your Cloud Bigtable storage.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBapp\-profiles\fR
\fB(ALPHA)\fR Manage Cloud Bigtable app profiles.

.TP 2m
\fBbackups\fR
\fB(ALPHA)\fR Manage Cloud Bigtable backups.

.TP 2m
\fBclusters\fR
\fB(ALPHA)\fR Manage Cloud Bigtable clusters.

.TP 2m
\fBinstances\fR
\fB(ALPHA)\fR Manage Cloud Bigtable instances.

.TP 2m
\fBoperations\fR
\fB(ALPHA)\fR Manage Cloud Bigtable operations.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud bigtable
$ gcloud beta bigtable
.RE

