
.TH "GCLOUD_PUBSUB_LITE\-TOPICS" 1



.SH "NAME"
.HP
gcloud pubsub lite\-topics \- manage Pub/Sub Lite topics



.SH "SYNOPSIS"
.HP
\f5gcloud pubsub lite\-topics\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Pub/Sub Lite topics.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a Pub/Sub Lite topic.

.TP 2m
\fBdelete\fR
Delete a Pub/Sub Lite topic.

.TP 2m
\fBdescribe\fR
Describe a Pub/Sub Lite topic.

.TP 2m
\fBlist\fR
List Pub/Sub Lite topics.

.TP 2m
\fBlist\-subscriptions\fR
List Pub/Sub Lite subscriptions for a given Lite topic.

.TP 2m
\fBupdate\fR
Update a Pub/Sub Lite topic.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha pubsub lite\-topics
$ gcloud beta pubsub lite\-topics
.RE

