
.TH "GCLOUD_BETA_IDENTITY_GROUPS_MEMBERSHIPS_DELETE" 1



.SH "NAME"
.HP
gcloud beta identity groups memberships delete \- delete a membership from an existing group



.SH "SYNOPSIS"
.HP
\f5gcloud beta identity groups memberships delete\fR \fB\-\-group\-email\fR=\fIGROUP_EMAIL\fR \fB\-\-member\-email\fR=\fIMEMBER_EMAIL\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Delete a membership from an existing group.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-group\-email\fR=\fIGROUP_EMAIL\fR
The email address of the group the new membership is being removed from.

.TP 2m
\fB\-\-member\-email\fR=\fIMEMBER_EMAIL\fR
The email address of the group or user being removed from the group identified
by group\-email.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBcloudidentity/v1beta1\fR API. The full documentation
for this API can be found at: https://cloud.google.com/identity/



.SH "EXAMPLES"

To delete a memberships from a group:

.RS 2m
$ gcloud beta identity groups memberships delete \e
    \-\-group\-email="eng\-discuss@foo.com" \e
    \-\-member\-email="user@foo.com"
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud identity groups memberships delete
$ gcloud alpha identity groups memberships delete
.RE

