
.TH "GCLOUD_AI\-PLATFORM_MODELS_DELETE" 1



.SH "NAME"
.HP
gcloud ai\-platform models delete \- delete an existing AI Platform model



.SH "SYNOPSIS"
.HP
\f5gcloud ai\-platform models delete\fR \fIMODEL\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIMODEL\fR
Name of the model.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Google Cloud region of the regional endpoint to use for this command. If
unspecified, the command uses the global endpoint of the AI Platform Training
and Prediction API.

Learn more about regional endpoints and see a list of available regions:
https://cloud.google.com/ai\-platform/prediction/docs/regional\-endpoints

\fIREGION\fR must be one of: \fBasia\-east1\fR, \fBeurope\-west4\fR,
\fBus\-central1\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "EXAMPLES"

To delete all models matching the regular expression \f5vision[0\-9]+\fR, run:

.RS 2m
$ gcloud ai\-platform models list \-\-uri \e
      \-\-filter 'name ~ vision[0\-9]+' |
      xargs \-n 1 gcloud ai\-platform models delete
.RE



.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha ai\-platform models delete
$ gcloud beta ai\-platform models delete
.RE

