
.TH "GCLOUD_ALPHA_PUBSUB" 1



.SH "NAME"
.HP
gcloud alpha pubsub \- manage Cloud Pub/Sub topics and subscriptions



.SH "SYNOPSIS"
.HP
\f5gcloud alpha pubsub\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Cloud Pub/Sub topics and subscriptions.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBsnapshots\fR
\fB(ALPHA)\fR These features are part of an invite\-only release of the Cloud
Pub/Sub API.

.TP 2m
\fBsubscriptions\fR
\fB(ALPHA)\fR Manage Cloud Pubsub subscriptions.

.TP 2m
\fBtopics\fR
\fB(ALPHA)\fR Manage Cloud Pubsub topics.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. These variants are also available:

.RS 2m
$ gcloud pubsub
$ gcloud beta pubsub
.RE

