
.TH "GCLOUD_ALPHA_RUN_SERVICES_GET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud alpha run services get\-iam\-policy \- get the IAM policy for a Cloud Run service



.SH "SYNOPSIS"
.HP
\f5gcloud alpha run services get\-iam\-policy\fR (\fISERVICE\fR\ :\ \fB\-\-region\fR=\fIREGION\fR) [\fB\-\-platform\fR=\fIPLATFORM\fR] [\fB\-\-filter\fR=\fIEXPRESSION\fR] [\fB\-\-limit\fR=\fILIMIT\fR] [\fB\-\-page\-size\fR=\fIPAGE_SIZE\fR] [\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command gets the IAM policy for a service. If formatted as
JSON, the output can be edited and used as a policy file for
\fBset\-iam\-policy\fR. The output includes an "etag" field identifying the
version emitted and allowing detection of concurrent policy updates; see $
gcloud alpha run registries set\-iam\-policy for additional details.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Service resource \- The service for which to display the IAM policy. The
arguments in this group can be used to specify the attributes of this resource.
(NOTE) Some attributes are not given arguments in this group but can be set in
other ways. To set the [project] attribute: provide the argument [service] on
the command line with a fully specified name; set the property [core/project];
provide the argument [\-\-project] on the command line. This must be specified.

.RS 2m
.TP 2m
\fISERVICE\fR
ID of the service or fully qualified identifier for the service. This positional
must be specified if any of the other arguments in this group are specified.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The Cloud Run region.


.RE
.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-platform\fR=\fIPLATFORM\fR
Target platform for running commands. \fIPLATFORM\fR must be one of:

.RS 2m
.TP 2m
\fBgke\fR
Cloud Run on Google Kubernetes Engine. This platform is not supported by this
command.

.TP 2m
\fBkubernetes\fR
Use a Knative\-compatible kubernetes cluster. This platform is not supported by
this command.

.TP 2m
\fBmanaged\fR
Fully managed version of Cloud Run. Use with the \f5\-\-region\fR flag or set
the [run/region] property to specify a Cloud Run region.

.RE
.sp



.RE
.sp

.SH "LIST COMMAND FLAGS"

.RS 2m
.TP 2m
\fB\-\-filter\fR=\fIEXPRESSION\fR
Apply a Boolean filter \fIEXPRESSION\fR to each resource item to be listed. If
the expression evaluates \f5True\fR, then that item is listed. For more details
and examples of filter expressions, run $ gcloud topic filters. This flag
interacts with other flags that are applied in this order: \fB\-\-flatten\fR,
\fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.

.TP 2m
\fB\-\-limit\fR=\fILIMIT\fR
Maximum number of resources to list. The default is \fBunlimited\fR. This flag
interacts with other flags that are applied in this order: \fB\-\-flatten\fR,
\fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.

.TP 2m
\fB\-\-page\-size\fR=\fIPAGE_SIZE\fR
Some services group resource list output into pages. This flag specifies the
maximum number of resources per page. The default is determined by the service
if it supports paging, otherwise it is \fBunlimited\fR (no paging). Paging may
be applied before or after \fB\-\-filter\fR and \fB\-\-limit\fR depending on the
service.

.TP 2m
\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]
Comma\-separated list of resource field key names to sort by. The default order
is ascending. Prefix a field with ``~'' for descending order on that field. This
flag interacts with other flags that are applied in this order:
\fB\-\-flatten\fR, \fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "API REFERENCE"

This command uses the \fBrun/v1alpha1\fR API. The full documentation for this
API can be found at: https://cloud.google.com/run/



.SH "EXAMPLES"

To print the IAM policy for a given service, run:

.RS 2m
$ gcloud alpha run services get\-iam\-policy \-\-region=us\-central1 \e
    my\-service
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. This variant is also available:

.RS 2m
$ gcloud beta run services get\-iam\-policy
.RE

