
.TH "GCLOUD_BETA_CONTAINER_BINAUTHZ_ATTESTORS_PUBLIC\-KEYS_ADD" 1



.SH "NAME"
.HP
gcloud beta container binauthz attestors public\-keys add \- add a public key to an Attestor



.SH "SYNOPSIS"
.HP
\f5gcloud beta container binauthz attestors public\-keys add\fR \fB\-\-attestor\fR=\fIATTESTOR\fR \fB\-\-public\-key\-file\fR=\fIPUBLIC_KEY_FILE\fR [\fB\-\-comment\fR=\fICOMMENT\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Add a public key to an Attestor.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m

Attestor resource \- The attestor to which the public key should be added. This
represents a Cloud resource. (NOTE) Some attributes are not given arguments in
this group but can be set in other ways. To set the [project] attribute: provide
the argument [\-\-attestor] on the command line with a fully specified name;
provide the argument [\-\-project] on the command line; set the property
[core/project]. This must be specified.

.RS 2m
.TP 2m
\fB\-\-attestor\fR=\fIATTESTOR\fR
ID of the attestor or fully qualified identifier for the attestor.

.RE
.sp
.TP 2m
\fB\-\-public\-key\-file\fR=\fIPUBLIC_KEY_FILE\fR
The path to the file containing the ASCII\-armored PGP public key to add.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-comment\fR=\fICOMMENT\fR
The comment describing the public key.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha container binauthz attestors public\-keys add
.RE

