
.TH "GCLOUD_BETA_BIGTABLE_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta bigtable operations describe \- describe a Cloud Bigtable operation



.SH "SYNOPSIS"
.HP
\f5gcloud beta bigtable operations describe\fR \fIOPERATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Describe a Cloud Bigtable operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Operation resource \- Cloud Bigtable operation to describe. This represents a
Cloud resource. This must be specified.

.RS 2m
.TP 2m
\fIOPERATION\fR
ID of the operation or fully qualified identifier for the operation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBbigtableadmin/v2\fR API. The full documentation for
this API can be found at: https://cloud.google.com/bigtable/



.SH "EXAMPLES"

To view details for operation 'OPERATION_ID', run:

.RS 2m
$ gcloud beta bigtable operations describe OPERATION_ID
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud bigtable operations describe
$ gcloud alpha bigtable operations describe
.RE

