
.TH "GCLOUD_BETA_COMPUTE_OS\-LOGIN_SSH\-KEYS" 1



.SH "NAME"
.HP
gcloud beta compute os\-login ssh\-keys \- list, add, update, and remove OS Login SSH Keys



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute os\-login ssh\-keys\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR List, add, update, and remove OS Login SSH Keys.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\fR
\fB(BETA)\fR Add an SSH public key to an OS Login profile.

.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Describe an SSH Public Key from an OS Login Profile.

.TP 2m
\fBlist\fR
\fB(BETA)\fR List SSH public keys from an OS Login profile.

.TP 2m
\fBremove\fR
\fB(BETA)\fR Remove an SSH public key from an OS Login profile.

.TP 2m
\fBupdate\fR
\fB(BETA)\fR Update an SSH public key in an OS Login profile.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute os\-login ssh\-keys
$ gcloud alpha compute os\-login ssh\-keys
.RE

