
.TH "GCLOUD_ALPHA_BQ" 1



.SH "NAME"
.HP
gcloud alpha bq \- interact with and manage resources in Google BigQuery



.SH "SYNOPSIS"
.HP
\f5gcloud alpha bq\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Interact with and manage resources in Google BigQuery.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdatasets\fR
\fB(ALPHA)\fR Manage Google BigQuery datasets.

.TP 2m
\fBjobs\fR
\fB(ALPHA)\fR Interact with and manage jobs in Google BigQuery.

.TP 2m
\fBtables\fR
\fB(ALPHA)\fR Interact with and manage Google BigQuery tables.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

