
.TH "GCLOUD_NETWORK\-MANAGEMENT_OPERATIONS" 1



.SH "NAME"
.HP
gcloud network\-management operations \- manage Network Management operations



.SH "SYNOPSIS"
.HP
\f5gcloud network\-management operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Network Management operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe a Network Management operation.

.TP 2m
\fBlist\fR
List Network Management operations.


.RE
.sp

.SH "NOTES"

This variant is also available:

.RS 2m
$ gcloud beta network\-management operations
.RE

