
.TH "GCLOUD_SPANNER_ROWS" 1



.SH "NAME"
.HP
gcloud spanner rows \- manage the rows in Cloud Spanner databases



.SH "SYNOPSIS"
.HP
\f5gcloud spanner rows\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage the rows in Cloud Spanner databases.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdelete\fR
Delete a row in a Cloud Spanner database.

.TP 2m
\fBinsert\fR
Insert a row in a Cloud Spanner database.

.TP 2m
\fBupdate\fR
Update a row in a Cloud Spanner database.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha spanner rows
$ gcloud beta spanner rows
.RE

