
.TH "GCLOUD_ALPHA_CONTAINER_HUB_CONFIG\-MANAGEMENT_ENABLE" 1



.SH "NAME"
.HP
gcloud alpha container hub config\-management enable \- enable Config Management feature



.SH "SYNOPSIS"
.HP
\f5gcloud alpha container hub config\-management enable\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR This command enables Config Management feature in Hub.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

