
.TH "GCLOUD_ALPHA_FIRESTORE_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha firestore operations describe \- retrieves information about a Cloud Firestore admin operation



.SH "SYNOPSIS"
.HP
\f5gcloud alpha firestore operations describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Retrieves information about a Cloud Firestore admin operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The unique name of the Operation to retrieve, formatted as either the full or
relative resource path:

.RS 2m
projects/my\-app\-id/databases/(default)/operations/foo
.RE

or:

.RS 2m
foo
.RE


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. This variant is also available:

.RS 2m
$ gcloud beta firestore operations describe
.RE

