
.TH "GCLOUD_ALPHA_COMPUTE_INTERCONNECTS_LOCATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha compute interconnects locations describe \- describe a Google Compute Engine interconnect location



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute interconnects locations describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Displays all data associated with Google Compute Engine
interconnect location in a project.

Example of usage: $ gcloud alpha compute interconnects locations describe
my\-location



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the interconnect location to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. These variants are also available:

.RS 2m
$ gcloud compute interconnects locations describe
$ gcloud beta compute interconnects locations describe
.RE

