
.TH "GCLOUD_ALPHA_PUBSUB_TOPICS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha pubsub topics describe \- describes a Cloud Pub/Sub topic



.SH "SYNOPSIS"
.HP
\f5gcloud alpha pubsub topics describe\fR \fITOPIC\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Describes a Cloud Pub/Sub topic.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Topic resource \- Name of the topic to describe. This represents a Cloud
resource. (NOTE) Some attributes are not given arguments in this group but can
be set in other ways. To set the [project] attribute: Set the property
[core/project] or provide the flag [\-\-project] on the command line. This must
be specified.

.RS 2m
.TP 2m
\fITOPIC\fR
The ID of the topic or a fully qualified identifier for the topic.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. Usually, users
of ALPHA commands and flags need to apply for access, agree to applicable terms,
and have their projects whitelisted. Contact Google or sign up on a product's
page for ALPHA access. Product pages can be found at
https://cloud.google.com/products/. These variants are also available:

.RS 2m
$ gcloud pubsub topics describe
$ gcloud beta pubsub topics describe
.RE

