
.TH "GCLOUD_ALPHA_CONTAINER_IMAGES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud alpha container images describe \- lists container analysis data for a given image



.SH "SYNOPSIS"
.HP
\f5gcloud alpha container images describe\fR \fIIMAGE_NAME\fR [\fB\-\-metadata\-filter\fR=\fIMETADATA_FILTER\fR] [\fB\-\-show\-all\-metadata\fR] [\fB\-\-show\-build\-details\fR] [\fB\-\-show\-deployment\fR] [\fB\-\-show\-image\-basis\fR] [\fB\-\-show\-package\-vulnerability\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Lists container analysis data for a valid image.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE_NAME\fR
The fully qualified name(s) of image(s) to describe. The name(s) should be
formatted as *.gcr.io/PROJECT_ID/IMAGE_PATH@sha256:DIGEST or
*.gcr.io/PROJECT_ID/IMAGE_PATH:TAG.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-metadata\-filter\fR=\fIMETADATA_FILTER\fR
Additional filter to fetch metadata for a given fully qualified image reference.

.TP 2m
\fB\-\-show\-all\-metadata\fR
Include all metadata in the output.

.TP 2m
\fB\-\-show\-build\-details\fR
Include build metadata in the output.

.TP 2m
\fB\-\-show\-deployment\fR
Include deployment metadata in the output.

.TP 2m
\fB\-\-show\-image\-basis\fR
Include base image metadata in the output.

.TP 2m
\fB\-\-show\-package\-vulnerability\fR
Include vulnerability metadata in the output.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

Describe container analysis data for a specified image:

.RS 2m
$ gcloud alpha container images describe \e
    gcr.io/myproject/myimage@digest
      OR
$ gcloud alpha container images describe gcr.io/myproject/myimage:tag
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. These variants are also available:

.RS 2m
$ gcloud container images describe
$ gcloud beta container images describe
.RE

