
.TH "GCLOUD_ALPHA_NETWORK\-CONNECTIVITY_HUBS_DELETE" 1



.SH "NAME"
.HP
gcloud alpha network\-connectivity hubs delete \- delete a hub



.SH "SYNOPSIS"
.HP
\f5gcloud alpha network\-connectivity hubs delete\fR \fIHUB\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Delete the specified hub.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m

Hub resource \- Name of the hub to be deleted. This represents a Cloud resource.
(NOTE) Some attributes are not given arguments in this group but can be set in
other ways. To set the [project] attribute: provide the argument [hub] on the
command line with a fully specified name; set the property [core/project];
provide the argument [\-\-project] on the command line. This must be specified.

.RS 2m
.TP 2m
\fIHUB\fR
ID of the hub or fully qualified identifier for the hub.


.RE
.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Return immediately, without waiting for the operation in progress to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "API REFERENCE"

This command uses the \fBnetworkconnectivity/v1alpha1\fR API. The full
documentation for this API can be found at: https://cloud.google.com/



.SH "EXAMPLES"

Deletes a hub named \f5\fImy\-hub\fR\fR.

.RS 2m
$ gcloud alpha network\-connectivity hubs delete my\-hub
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
allowlist.

