
.TH "GCLOUD_ALPHA_COMPUTE_COMMITMENTS" 1



.SH "NAME"
.HP
gcloud alpha compute commitments \- manage Google Compute Engine commitments



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute commitments\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Manage Google Compute Engine commitments.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
\fB(ALPHA)\fR Create Google Compute Engine commitments.

.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe a Google Compute Engine commitment.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List Google Compute Engine commitments.

.TP 2m
\fBupdate\-reservations\fR
\fB(ALPHA)\fR Update the resource shape of reservations within the commitment.


.RE
.sp

.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist. These variants are also available:

.RS 2m
$ gcloud compute commitments
$ gcloud beta compute commitments
.RE

