
.TH "GCLOUD_BETA_COMPUTE_NETWORKS_SUBNETS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud beta compute networks subnets set\-iam\-policy \- set the IAM Policy for a Google Compute Engine subnetwork



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute networks subnets set\-iam\-policy\fR \fINAME\fR \fIPOLICY_FILE\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute networks subnets set\-iam\-policy\fR sets
the Iam Policy associated with a Google Compute Engine subnetwork in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
Name of the subnetwork to set the IAM Policy of.

.TP 2m
\fIPOLICY_FILE\fR
Path to a local JSON or YAML formatted file containing a valid policy.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the subnetwork to set the IAM Policy of. If not specified, you may
be prompted to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha compute networks subnets set\-iam\-policy
.RE

