
.TH "GCLOUD_BETA_COMPUTE_SNAPSHOTS_DELETE" 1



.SH "NAME"
.HP
gcloud beta compute snapshots delete \- delete Google Compute Engine snapshots



.SH "SYNOPSIS"
.HP
\f5gcloud beta compute snapshots delete\fR \fISNAPSHOT_NAME\fR [\fISNAPSHOT_NAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR \fBgcloud beta compute snapshots delete\fR deletes one or more
Google Compute Engine snapshots.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISNAPSHOT_NAME\fR [\fISNAPSHOT_NAME\fR ...]
Names of the snapshots to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud compute snapshots delete
$ gcloud alpha compute snapshots delete
.RE

