
.TH "GCLOUD_HEALTHCARE_OPERATIONS" 1



.SH "NAME"
.HP
gcloud healthcare operations \- manage Cloud Healthcare API operations



.SH "SYNOPSIS"
.HP
\f5gcloud healthcare operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Healthcare API operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe a Cloud Healthcare API operation.

.TP 2m
\fBlist\fR
List Cloud Healthcare API operations.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha healthcare operations
$ gcloud beta healthcare operations
.RE

