
.TH "GCLOUD_ALPHA_FIREBASE_TEST_IOS_MODELS" 1



.SH "NAME"
.HP
gcloud alpha firebase test ios models \- explore iOS models available in the Test Environment catalog



.SH "SYNOPSIS"
.HP
\f5gcloud alpha firebase test ios models\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR Explore iOS models available in the Test Environment catalog.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flags\-file, \-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project,
\-\-quiet, \-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$
gcloud help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(ALPHA)\fR Describe an iOS model.

.TP 2m
\fBlist\fR
\fB(ALPHA)\fR List all iOS models available for testing.


.RE
.sp

.SH "EXAMPLES"

To list all iOS models available for running tests, along with their model names
and supported iOS versions, run:

.RS 2m
$ gcloud alpha firebase test ios models list
.RE

To view information about a single iOS model, run:

.RS 2m
$ gcloud alpha firebase test ios models describe MODEL_ID
.RE



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you will have to apply for early access and have your projects registered on the
API whitelist to use it. To do so, contact Support at
https://cloud.google.com/support/. These variants are also available:

.RS 2m
$ gcloud firebase test ios models
$ gcloud beta firebase test ios models
.RE

