
.TH "GCLOUD_ALPHA_COMPUTE_BACKEND\-SERVICES_SET\-SECURITY\-POLICY" 1



.SH "NAME"
.HP
gcloud alpha compute backend\-services set\-security\-policy \- set the security policy for a backend service



.SH "SYNOPSIS"
.HP
\f5gcloud alpha compute backend\-services set\-security\-policy\fR \fIBACKEND_SERVICE_NAME\fR \fB\-\-security\-policy\fR=\fISECURITY_POLICY\fR [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(ALPHA)\fR \fB(DEPRECATED)\fR This command is deprecated and will not be
promoted to beta. Please use "gcloud beta backend\-services update" instead.


\fBgcloud alpha compute backend\-services set\-security\-policy\fR is used to
set the security policy for a backend service. Setting an empty string will
clear the existing security policy.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBACKEND_SERVICE_NAME\fR
Name of the backend service to operate on.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-security\-policy\fR=\fISECURITY_POLICY\fR
The security policy that will be set for this backend service.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If set, the backend service is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Region of the backend service to operate on. Overrides the default
\fBcompute/region\fR property value for this command invocation.


.RE
.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "NOTES"

This command is currently in ALPHA and may change without notice. If this
command fails with API permission errors despite specifying the right project,
you may be trying to access an API with an invitation\-only early access
whitelist.

