
.TH "GCLOUD_BETA_API\-GATEWAY" 1



.SH "NAME"
.HP
gcloud beta api\-gateway \- manage Cloud API Gateway resources



.SH "SYNOPSIS"
.HP
\f5gcloud beta api\-gateway\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Commands for managing Cloud API Gateway resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBapi\-configs\fR
\fB(BETA)\fR Manage Cloud API Gateway API Configs.

.TP 2m
\fBapis\fR
\fB(BETA)\fR Manage Cloud API Gateway APIs.

.TP 2m
\fBgateways\fR
\fB(BETA)\fR Manage Cloud API Gateway Gateways.

.TP 2m
\fBoperations\fR
\fB(BETA)\fR Manage operations for Cloud API Gateways.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha api\-gateway
.RE

