
.TH "GCLOUD_TOPIC_UNINSTALL" 1



.SH "NAME"
.HP
gcloud topic uninstall \- supplementary help for uninstalling Cloud SDK



.SH "DESCRIPTION"


.SH "Uninstalling Google Cloud SDK"

Note: For installations completed using an OS package (such as \f5apt\-get\fR,
\f5yum\fR, etc.), uninstall Cloud SDK via the OS package manager.

Note: For Windows installations, execute the uninstaller.exe found under your
Cloud SDK directory.

To completely remove Cloud SDK, follow these instructions:

.RS 2m
.IP "\(bu" 2m
Locate your installation directory by running:
.RE
.sp

.RS 2m
$ gcloud info \-\-format='value(installation.sdk_root)'
.RE

.RS 2m
.IP "\(bu" 2m
Locate your user config directory (typically \f5~/.config/gcloud\fR on MacOS and
Linux) by running:
.RE
.sp

.RS 2m
$ gcloud info \-\-format='value(config.paths.global_config_dir)'
.RE

.RS 2m
.IP "\(bu" 2m
Delete both these directories.
.RE
.sp

.RS 2m
.IP "\(bu" 2m
Additionally, remove lines sourcing \f5completion.bash.inc\fR and
\f5paths.bash.inc\fR in your \f5.bashrc\fR or equivalent shell init file, if you
added them during installation.
.RE
.sp

.RS 2m
.IP "\(bu" 2m
Review the contents of the \f5.boto\fR file in your home directory and remove
the sections '[GoogleCompute]' and '[GSUtil]'. In addition, review the sections
\'[OAuth2]' and '[Credentials]' for settings that are no longer needed.
.RE
.sp
