
.TH "GCLOUD_BETA_TASKS_LOCATIONS" 1



.SH "NAME"
.HP
gcloud beta tasks locations \- get information about Cloud Tasks locations



.SH "SYNOPSIS"
.HP
\f5gcloud beta tasks locations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Get information about Cloud Tasks locations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
\fB(BETA)\fR Show details about a location.

.TP 2m
\fBlist\fR
\fB(BETA)\fR Lists the locations where Cloud Tasks is available.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud tasks locations
$ gcloud alpha tasks locations
.RE

