
.TH "GCLOUD_ASSET_OPERATIONS" 1



.SH "NAME"
.HP
gcloud asset operations \- manage Cloud Asset Inventory operations



.SH "SYNOPSIS"
.HP
\f5gcloud asset operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Asset Inventory operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe a Cloud Asset Inventory operation.


.RE
.sp

.SH "NOTES"

These variants are also available:

.RS 2m
$ gcloud alpha asset operations
$ gcloud beta asset operations
.RE

