
.TH "GCLOUD_BETA_EMULATORS" 1



.SH "NAME"
.HP
gcloud beta emulators \- set up your local development environment using emulators



.SH "SYNOPSIS"
.HP
\f5gcloud beta emulators\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Set up your local development environment using emulators.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity.

Run \fB$ gcloud help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBbigtable\fR
\fB(BETA)\fR Manage your local Bigtable emulator.

.TP 2m
\fBdatastore\fR
\fB(BETA)\fR Manage your local datastore emulator.

.TP 2m
\fBfirestore\fR
\fB(BETA)\fR Manage your local firestore emulator.

.TP 2m
\fBpubsub\fR
\fB(BETA)\fR Manage your local pubsub emulator.

.TP 2m
\fBspanner\fR
\fB(BETA)\fR Manage your local Spanner emulator.


.RE
.sp

.SH "NOTES"

This command is currently in BETA and may change without notice. This variant is
also available:

.RS 2m
$ gcloud alpha emulators
.RE

