
.TH "GCLOUD_BETA_FIREBASE_TEST_IOS_VERSIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud beta firebase test ios versions describe \- describe an iOS operating system version



.SH "SYNOPSIS"
.HP
\f5gcloud beta firebase test ios versions describe\fR \fIVERSION_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(BETA)\fR Describe an iOS operating system version.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSION_ID\fR
The version ID to describe, found using $ gcloud beta firebase test ios versions
list.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-billing\-project,
\-\-configuration, \-\-flags\-file, \-\-flatten, \-\-format, \-\-help,
\-\-impersonate\-service\-account, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To describe an iOS operating system version available for testing, run:

.RS 2m
gcloud beta firebase test ios versions describe 12.1
.RE

To describe an iOS operating system version available for testing in JSON
format, run:

.RS 2m
gcloud beta firebase test ios versions describe 12.1 \-\-format=json
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice. These variants
are also available:

.RS 2m
$ gcloud firebase test ios versions describe
$ gcloud alpha firebase test ios versions describe
.RE

