# -*- coding: utf-8 -*- #
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""This is a command for testing."""

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from googlecloudsdk.calliope import base as calliope_base


@calliope_base.ReleaseTracks(calliope_base.ReleaseTrack.ALPHA,
                             calliope_base.ReleaseTrack.BETA)
class ExplicitNotes(calliope_base.Command):
  """A command with explicit and autogenerated NOTES.

  ## NOTES

  Explicit notes should appear along with BETA autogenerated notes.
  """

  @staticmethod
  def Args(parser):
    parser.add_argument('--common', category=calliope_base.COMMONLY_USED_FLAGS,
                        help='This flag is common.')

  def Run(self, args):
    pass


@calliope_base.ReleaseTracks(calliope_base.ReleaseTrack.GA)
class CommonFlags(calliope_base.Command):
  """A command with common flags and explicit NOTES.

  ## NOTES

  Move along, no autogenerated notes to see here.
  """

  @staticmethod
  def Args(parser):
    parser.add_argument('--common', category=calliope_base.COMMONLY_USED_FLAGS,
                        help='This flag is common.')

  def Run(self, args):
    pass
