# -*- coding: utf-8 -*- #
# Copyright 2016 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the suggest_commands module."""

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from googlecloudsdk.calliope import suggest_commands
from googlecloudsdk.command_lib.static_completion import lookup
from tests.lib import calliope_test_base
from tests.lib import parameterized
from tests.lib.parameterized_line_no import LineNo as T
from tests.unit.calliope.testdata import gcloud_commands

import mock


class GetCommandSuggestionsTest(calliope_test_base.CalliopeTestBase,
                                parameterized.TestCase):

  def SetUp(self):
    self.root = gcloud_commands.ROOT
    self.StartObjectPatch(lookup, 'LoadCompletionCliTree',
                          return_value=self.root)

  def testGetCanonicalCommands(self):
    self.assertEqual(
        [
            ['app', 'browse'],
            ['app', 'create'],
            ['app', 'deploy'],
            ['app', 'describe'],
            ['app', 'domain-mappings', 'create'],
            ['app', 'domain-mappings', 'delete'],
            ['app', 'domain-mappings', 'describe'],
            ['app', 'domain-mappings', 'list'],
            ['app', 'domain-mappings', 'update'],
            ['app', 'firewall-rules', 'create'],
            ['app', 'firewall-rules', 'delete'],
            ['app', 'firewall-rules', 'describe'],
            ['app', 'firewall-rules', 'list'],
            ['app', 'firewall-rules', 'test-ip'],
            ['app', 'firewall-rules', 'update'],
            ['app', 'instances', 'delete'],
            ['app', 'instances', 'describe'],
            ['app', 'instances', 'disable-debug'],
            ['app', 'instances', 'enable-debug'],
            ['app', 'instances', 'list'],
            ['app', 'instances', 'scp'],
            ['app', 'instances', 'ssh'],
            ['app', 'logs', 'read'],
            ['app', 'logs', 'tail'],
            ['app', 'open-console'],
            ['app', 'operations', 'describe'],
            ['app', 'operations', 'list'],
            ['app', 'operations', 'wait'],
            ['app', 'regions', 'list'],
            ['app', 'services', 'browse'],
            ['app', 'services', 'delete'],
            ['app', 'services', 'describe'],
            ['app', 'services', 'list'],
            ['app', 'services', 'set-traffic'],
            ['app', 'ssl-certificates', 'create'],
            ['app', 'ssl-certificates', 'delete'],
            ['app', 'ssl-certificates', 'describe'],
            ['app', 'ssl-certificates', 'list'],
            ['app', 'ssl-certificates', 'update'],
            ['app', 'update'],
            ['app', 'versions', 'browse'],
            ['app', 'versions', 'delete'],
            ['app', 'versions', 'describe'],
            ['app', 'versions', 'list'],
            ['app', 'versions', 'migrate'],
            ['app', 'versions', 'start'],
            ['app', 'versions', 'stop'],
            ['auth', 'activate-service-account'],
            ['auth', 'application-default', 'login'],
            ['auth', 'application-default', 'print-access-token'],
            ['auth', 'application-default', 'revoke'],
            ['auth', 'configure-docker'],
            ['auth', 'list'],
            ['auth', 'login'],
            ['auth', 'revoke'],
            ['bigtable', 'clusters', 'describe'],
            ['bigtable', 'clusters', 'list'],
            ['bigtable', 'instances', 'add-iam-policy-binding'],
            ['bigtable', 'instances', 'create'],
            ['bigtable', 'instances', 'delete'],
            ['bigtable', 'instances', 'describe'],
            ['bigtable', 'instances', 'get-iam-policy'],
            ['bigtable', 'instances', 'list'],
            ['bigtable', 'instances', 'remove-iam-policy-binding'],
            ['bigtable', 'instances', 'set-iam-policy'],
            ['bigtable', 'instances', 'update'],
            ['bigtable', 'instances', 'upgrade'],
            ['builds', 'cancel'],
            ['builds', 'describe'],
            ['builds', 'list'],
            ['builds', 'log'],
            ['builds', 'submit'],
            ['components', 'install'],
            ['components', 'list'],
            ['components', 'reinstall'],
            ['components', 'remove'],
            ['components', 'repositories', 'add'],
            ['components', 'repositories', 'list'],
            ['components', 'repositories', 'remove'],
            ['components', 'restore'],
            ['components', 'update'],
            ['composer', 'environments', 'create'],
            ['composer', 'environments', 'delete'],
            ['composer', 'environments', 'describe'],
            ['composer', 'environments', 'list'],
            ['composer', 'environments', 'run'],
            ['composer', 'environments', 'storage', 'dags', 'delete'],
            ['composer', 'environments', 'storage', 'dags', 'export'],
            ['composer', 'environments', 'storage', 'dags', 'import'],
            ['composer', 'environments', 'storage', 'dags', 'list'],
            ['composer', 'environments', 'storage', 'data', 'delete'],
            ['composer', 'environments', 'storage', 'data', 'export'],
            ['composer', 'environments', 'storage', 'data', 'import'],
            ['composer', 'environments', 'storage', 'data', 'list'],
            ['composer', 'environments', 'storage', 'plugins', 'delete'],
            ['composer', 'environments', 'storage', 'plugins', 'export'],
            ['composer', 'environments', 'storage', 'plugins', 'import'],
            ['composer', 'environments', 'storage', 'plugins', 'list'],
            ['composer', 'environments', 'update'],
            ['composer', 'operations', 'delete'],
            ['composer', 'operations', 'describe'],
            ['composer', 'operations', 'list'],
            ['composer', 'operations', 'wait'],
            ['compute', 'accelerator-types', 'describe'],
            ['compute', 'accelerator-types', 'list'],
            ['compute', 'addresses', 'create'],
            ['compute', 'addresses', 'delete'],
            ['compute', 'addresses', 'describe'],
            ['compute', 'addresses', 'list'],
            ['compute', 'backend-buckets', 'add-signed-url-key'],
            ['compute', 'backend-buckets', 'create'],
            ['compute', 'backend-buckets', 'delete'],
            ['compute', 'backend-buckets', 'delete-signed-url-key'],
            ['compute', 'backend-buckets', 'describe'],
            ['compute', 'backend-buckets', 'list'],
            ['compute', 'backend-buckets', 'update'],
            ['compute', 'backend-services', 'add-backend'],
            ['compute', 'backend-services', 'add-signed-url-key'],
            ['compute', 'backend-services', 'create'],
            ['compute', 'backend-services', 'delete'],
            ['compute', 'backend-services', 'delete-signed-url-key'],
            ['compute', 'backend-services', 'describe'],
            ['compute', 'backend-services', 'edit'],
            ['compute', 'backend-services', 'get-health'],
            ['compute', 'backend-services', 'list'],
            ['compute', 'backend-services', 'remove-backend'],
            ['compute', 'backend-services', 'update'],
            ['compute', 'backend-services', 'update-backend'],
            ['compute', 'commitments', 'create'],
            ['compute', 'commitments', 'describe'],
            ['compute', 'commitments', 'list'],
            ['compute', 'config-ssh'],
            ['compute', 'connect-to-serial-port'],
            ['compute', 'copy-files'],
            ['compute', 'disk-types', 'describe'],
            ['compute', 'disk-types', 'list'],
            ['compute', 'disks', 'add-labels'],
            ['compute', 'disks', 'create'],
            ['compute', 'disks', 'delete'],
            ['compute', 'disks', 'describe'],
            ['compute', 'disks', 'list'],
            ['compute', 'disks', 'move'],
            ['compute', 'disks', 'remove-labels'],
            ['compute', 'disks', 'resize'],
            ['compute', 'disks', 'snapshot'],
            ['compute', 'disks', 'update'],
            ['compute', 'firewall-rules', 'create'],
            ['compute', 'firewall-rules', 'delete'],
            ['compute', 'firewall-rules', 'describe'],
            ['compute', 'firewall-rules', 'list'],
            ['compute', 'firewall-rules', 'update'],
            ['compute', 'forwarding-rules', 'create'],
            ['compute', 'forwarding-rules', 'delete'],
            ['compute', 'forwarding-rules', 'describe'],
            ['compute', 'forwarding-rules', 'list'],
            ['compute', 'forwarding-rules', 'set-target'],
            ['compute', 'health-checks', 'create', 'http'],
            ['compute', 'health-checks', 'create', 'https'],
            ['compute', 'health-checks', 'create', 'ssl'],
            ['compute', 'health-checks', 'create', 'tcp'],
            ['compute', 'health-checks', 'delete'],
            ['compute', 'health-checks', 'describe'],
            ['compute', 'health-checks', 'list'],
            ['compute', 'health-checks', 'update', 'http'],
            ['compute', 'health-checks', 'update', 'https'],
            ['compute', 'health-checks', 'update', 'ssl'],
            ['compute', 'health-checks', 'update', 'tcp'],
            ['compute', 'http-health-checks', 'create'],
            ['compute', 'http-health-checks', 'delete'],
            ['compute', 'http-health-checks', 'describe'],
            ['compute', 'http-health-checks', 'list'],
            ['compute', 'http-health-checks', 'update'],
            ['compute', 'https-health-checks', 'create'],
            ['compute', 'https-health-checks', 'delete'],
            ['compute', 'https-health-checks', 'describe'],
            ['compute', 'https-health-checks', 'list'],
            ['compute', 'https-health-checks', 'update'],
            ['compute', 'images', 'add-labels'],
            ['compute', 'images', 'create'],
            ['compute', 'images', 'delete'],
            ['compute', 'images', 'deprecate'],
            ['compute', 'images', 'describe'],
            ['compute', 'images', 'describe-from-family'],
            ['compute', 'images', 'export'],
            ['compute', 'images', 'import'],
            ['compute', 'images', 'list'],
            ['compute', 'images', 'remove-labels'],
            ['compute', 'images', 'update'],
            ['compute', 'instance-groups', 'describe'],
            ['compute', 'instance-groups', 'get-named-ports'],
            ['compute', 'instance-groups', 'list'],
            ['compute', 'instance-groups', 'list-instances'],
            ['compute', 'instance-groups', 'managed', 'abandon-instances'],
            ['compute', 'instance-groups', 'managed', 'create'],
            ['compute', 'instance-groups', 'managed', 'delete'],
            ['compute', 'instance-groups', 'managed', 'delete-instances'],
            ['compute', 'instance-groups', 'managed', 'describe'],
            ['compute', 'instance-groups', 'managed', 'get-named-ports'],
            ['compute', 'instance-groups', 'managed', 'list'],
            ['compute', 'instance-groups', 'managed', 'list-instances'],
            ['compute', 'instance-groups', 'managed', 'recreate-instances'],
            ['compute', 'instance-groups', 'managed', 'resize'],
            ['compute', 'instance-groups', 'managed', 'set-autoscaling'],
            ['compute', 'instance-groups', 'managed', 'set-instance-template'],
            ['compute', 'instance-groups', 'managed', 'set-named-ports'],
            ['compute', 'instance-groups', 'managed', 'set-target-pools'],
            ['compute', 'instance-groups', 'managed', 'stop-autoscaling'],
            ['compute', 'instance-groups', 'managed', 'wait-until-stable'],
            ['compute', 'instance-groups', 'set-named-ports'],
            ['compute', 'instance-groups', 'unmanaged', 'add-instances'],
            ['compute', 'instance-groups', 'unmanaged', 'create'],
            ['compute', 'instance-groups', 'unmanaged', 'delete'],
            ['compute', 'instance-groups', 'unmanaged', 'describe'],
            ['compute', 'instance-groups', 'unmanaged', 'get-named-ports'],
            ['compute', 'instance-groups', 'unmanaged', 'list'],
            ['compute', 'instance-groups', 'unmanaged', 'list-instances'],
            ['compute', 'instance-groups', 'unmanaged', 'remove-instances'],
            ['compute', 'instance-groups', 'unmanaged', 'set-named-ports'],
            ['compute', 'instance-templates', 'create'],
            ['compute', 'instance-templates', 'create-with-container'],
            ['compute', 'instance-templates', 'delete'],
            ['compute', 'instance-templates', 'describe'],
            ['compute', 'instance-templates', 'list'],
            ['compute', 'instances', 'add-access-config'],
            ['compute', 'instances', 'add-labels'],
            ['compute', 'instances', 'add-metadata'],
            ['compute', 'instances', 'add-tags'],
            ['compute', 'instances', 'attach-disk'],
            ['compute', 'instances', 'create'],
            ['compute', 'instances', 'create-with-container'],
            ['compute', 'instances', 'delete'],
            ['compute', 'instances', 'delete-access-config'],
            ['compute', 'instances', 'describe'],
            ['compute', 'instances', 'detach-disk'],
            ['compute', 'instances', 'get-serial-port-output'],
            ['compute', 'instances', 'list'],
            ['compute', 'instances', 'move'],
            ['compute', 'instances', 'network-interfaces', 'update'],
            ['compute', 'instances', 'remove-labels'],
            ['compute', 'instances', 'remove-metadata'],
            ['compute', 'instances', 'remove-tags'],
            ['compute', 'instances', 'reset'],
            ['compute', 'instances', 'set-disk-auto-delete'],
            ['compute', 'instances', 'set-machine-type'],
            ['compute', 'instances', 'set-scheduling'],
            ['compute', 'instances', 'set-service-account'],
            ['compute', 'instances', 'simulate-maintenance-event'],
            ['compute', 'instances', 'start'],
            ['compute', 'instances', 'stop'],
            ['compute', 'instances', 'tail-serial-port-output'],
            ['compute', 'instances', 'update'],
            ['compute', 'instances', 'update-access-config'],
            ['compute', 'instances', 'update-container'],
            ['compute', 'interconnects', 'attachments', 'dedicated', 'create'],
            ['compute', 'interconnects', 'attachments', 'dedicated', 'update'],
            ['compute', 'interconnects', 'attachments', 'delete'],
            ['compute', 'interconnects', 'attachments', 'describe'],
            ['compute', 'interconnects', 'attachments', 'list'],
            ['compute', 'interconnects', 'attachments', 'partner', 'create'],
            ['compute', 'interconnects', 'attachments', 'partner', 'update'],
            ['compute', 'interconnects', 'create'],
            ['compute', 'interconnects', 'delete'],
            ['compute', 'interconnects', 'describe'],
            ['compute', 'interconnects', 'list'],
            ['compute', 'interconnects', 'locations', 'describe'],
            ['compute', 'interconnects', 'locations', 'list'],
            ['compute', 'interconnects', 'update'],
            ['compute', 'machine-types', 'describe'],
            ['compute', 'machine-types', 'list'],
            ['compute', 'networks', 'create'],
            ['compute', 'networks', 'delete'],
            ['compute', 'networks', 'describe'],
            ['compute', 'networks', 'list'],
            ['compute', 'networks', 'peerings', 'create'],
            ['compute', 'networks', 'peerings', 'delete'],
            ['compute', 'networks', 'peerings', 'list'],
            ['compute', 'networks', 'subnets', 'create'],
            ['compute', 'networks', 'subnets', 'delete'],
            ['compute', 'networks', 'subnets', 'describe'],
            ['compute', 'networks', 'subnets', 'expand-ip-range'],
            ['compute', 'networks', 'subnets', 'list'],
            ['compute', 'networks', 'subnets', 'list-usable'],
            ['compute', 'networks', 'subnets', 'update'],
            ['compute', 'networks', 'update'],
            ['compute', 'operations', 'describe'],
            ['compute', 'operations', 'list'],
            ['compute', 'os-login', 'describe-profile'],
            ['compute', 'os-login', 'remove-profile'],
            ['compute', 'os-login', 'ssh-keys', 'add'],
            ['compute', 'os-login', 'ssh-keys', 'describe'],
            ['compute', 'os-login', 'ssh-keys', 'list'],
            ['compute', 'os-login', 'ssh-keys', 'remove'],
            ['compute', 'os-login', 'ssh-keys', 'update'],
            ['compute', 'project-info', 'add-metadata'],
            ['compute', 'project-info', 'describe'],
            ['compute', 'project-info', 'remove-metadata'],
            ['compute', 'project-info', 'set-usage-bucket'],
            ['compute', 'project-info', 'update'],
            ['compute', 'regions', 'describe'],
            ['compute', 'regions', 'list'],
            ['compute', 'reset-windows-password'],
            ['compute', 'routers', 'add-bgp-peer'],
            ['compute', 'routers', 'add-interface'],
            ['compute', 'routers', 'create'],
            ['compute', 'routers', 'delete'],
            ['compute', 'routers', 'describe'],
            ['compute', 'routers', 'get-status'],
            ['compute', 'routers', 'list'],
            ['compute', 'routers', 'remove-bgp-peer'],
            ['compute', 'routers', 'remove-interface'],
            ['compute', 'routers', 'update'],
            ['compute', 'routers', 'update-bgp-peer'],
            ['compute', 'routers', 'update-interface'],
            ['compute', 'routes', 'create'],
            ['compute', 'routes', 'delete'],
            ['compute', 'routes', 'describe'],
            ['compute', 'routes', 'list'],
            ['compute', 'scp'],
            ['compute', 'shared-vpc', 'associated-projects', 'add'],
            ['compute', 'shared-vpc', 'associated-projects', 'list'],
            ['compute', 'shared-vpc', 'associated-projects', 'remove'],
            ['compute', 'shared-vpc', 'disable'],
            ['compute', 'shared-vpc', 'enable'],
            ['compute', 'shared-vpc', 'get-host-project'],
            ['compute', 'shared-vpc', 'list-associated-resources'],
            ['compute', 'shared-vpc', 'organizations', 'list-host-projects'],
            ['compute', 'sign-url'],
            ['compute', 'snapshots', 'add-labels'],
            ['compute', 'snapshots', 'delete'],
            ['compute', 'snapshots', 'describe'],
            ['compute', 'snapshots', 'list'],
            ['compute', 'snapshots', 'remove-labels'],
            ['compute', 'snapshots', 'update'],
            ['compute', 'sole-tenancy', 'node-groups', 'create'],
            ['compute', 'sole-tenancy', 'node-groups', 'delete'],
            ['compute', 'sole-tenancy', 'node-groups', 'describe'],
            ['compute', 'sole-tenancy', 'node-groups', 'list'],
            ['compute', 'sole-tenancy', 'node-groups', 'list-nodes'],
            ['compute', 'sole-tenancy', 'node-groups', 'update'],
            ['compute', 'sole-tenancy', 'node-templates', 'create'],
            ['compute', 'sole-tenancy', 'node-templates', 'delete'],
            ['compute', 'sole-tenancy', 'node-templates', 'describe'],
            ['compute', 'sole-tenancy', 'node-templates', 'list'],
            ['compute', 'sole-tenancy', 'node-types', 'describe'],
            ['compute', 'sole-tenancy', 'node-types', 'list'],
            ['compute', 'ssh'],
            ['compute', 'ssl-certificates', 'create'],
            ['compute', 'ssl-certificates', 'delete'],
            ['compute', 'ssl-certificates', 'describe'],
            ['compute', 'ssl-certificates', 'list'],
            ['compute', 'ssl-policies', 'create'],
            ['compute', 'ssl-policies', 'delete'],
            ['compute', 'ssl-policies', 'describe'],
            ['compute', 'ssl-policies', 'list'],
            ['compute', 'ssl-policies', 'list-available-features'],
            ['compute', 'ssl-policies', 'update'],
            ['compute', 'target-http-proxies', 'create'],
            ['compute', 'target-http-proxies', 'delete'],
            ['compute', 'target-http-proxies', 'describe'],
            ['compute', 'target-http-proxies', 'list'],
            ['compute', 'target-http-proxies', 'update'],
            ['compute', 'target-https-proxies', 'create'],
            ['compute', 'target-https-proxies', 'delete'],
            ['compute', 'target-https-proxies', 'describe'],
            ['compute', 'target-https-proxies', 'list'],
            ['compute', 'target-https-proxies', 'update'],
            ['compute', 'target-instances', 'create'],
            ['compute', 'target-instances', 'delete'],
            ['compute', 'target-instances', 'describe'],
            ['compute', 'target-instances', 'list'],
            ['compute', 'target-pools', 'add-health-checks'],
            ['compute', 'target-pools', 'add-instances'],
            ['compute', 'target-pools', 'create'],
            ['compute', 'target-pools', 'delete'],
            ['compute', 'target-pools', 'describe'],
            ['compute', 'target-pools', 'get-health'],
            ['compute', 'target-pools', 'list'],
            ['compute', 'target-pools', 'remove-health-checks'],
            ['compute', 'target-pools', 'remove-instances'],
            ['compute', 'target-pools', 'set-backup'],
            ['compute', 'target-ssl-proxies', 'create'],
            ['compute', 'target-ssl-proxies', 'delete'],
            ['compute', 'target-ssl-proxies', 'describe'],
            ['compute', 'target-ssl-proxies', 'list'],
            ['compute', 'target-ssl-proxies', 'update'],
            ['compute', 'target-tcp-proxies', 'create'],
            ['compute', 'target-tcp-proxies', 'delete'],
            ['compute', 'target-tcp-proxies', 'describe'],
            ['compute', 'target-tcp-proxies', 'list'],
            ['compute', 'target-tcp-proxies', 'update'],
            ['compute', 'target-vpn-gateways', 'create'],
            ['compute', 'target-vpn-gateways', 'delete'],
            ['compute', 'target-vpn-gateways', 'describe'],
            ['compute', 'target-vpn-gateways', 'list'],
            ['compute', 'tpus', 'accelerator-types', 'describe'],
            ['compute', 'tpus', 'accelerator-types', 'list'],
            ['compute', 'tpus', 'create'],
            ['compute', 'tpus', 'delete'],
            ['compute', 'tpus', 'describe'],
            ['compute', 'tpus', 'list'],
            ['compute', 'tpus', 'locations', 'describe'],
            ['compute', 'tpus', 'locations', 'list'],
            ['compute', 'tpus', 'reimage'],
            ['compute', 'tpus', 'start'],
            ['compute', 'tpus', 'stop'],
            ['compute', 'tpus', 'versions', 'describe'],
            ['compute', 'tpus', 'versions', 'list'],
            ['compute', 'url-maps', 'add-host-rule'],
            ['compute', 'url-maps', 'add-path-matcher'],
            ['compute', 'url-maps', 'create'],
            ['compute', 'url-maps', 'delete'],
            ['compute', 'url-maps', 'describe'],
            ['compute', 'url-maps', 'edit'],
            ['compute', 'url-maps', 'invalidate-cdn-cache'],
            ['compute', 'url-maps', 'list'],
            ['compute', 'url-maps', 'list-cdn-cache-invalidations'],
            ['compute', 'url-maps', 'remove-host-rule'],
            ['compute', 'url-maps', 'remove-path-matcher'],
            ['compute', 'url-maps', 'set-default-service'],
            ['compute', 'vpn-tunnels', 'create'],
            ['compute', 'vpn-tunnels', 'delete'],
            ['compute', 'vpn-tunnels', 'describe'],
            ['compute', 'vpn-tunnels', 'list'],
            ['compute', 'zones', 'describe'],
            ['compute', 'zones', 'list'],
            ['config', 'configurations', 'activate'],
            ['config', 'configurations', 'create'],
            ['config', 'configurations', 'delete'],
            ['config', 'configurations', 'describe'],
            ['config', 'configurations', 'list'],
            ['config', 'get-value'],
            ['config', 'list'],
            ['config', 'set'],
            ['config', 'unset'],
            ['container', 'clusters', 'create'],
            ['container', 'clusters', 'delete'],
            ['container', 'clusters', 'describe'],
            ['container', 'clusters', 'get-credentials'],
            ['container', 'clusters', 'list'],
            ['container', 'clusters', 'resize'],
            ['container', 'clusters', 'update'],
            ['container', 'clusters', 'upgrade'],
            ['container', 'get-server-config'],
            ['container', 'images', 'add-tag'],
            ['container', 'images', 'delete'],
            ['container', 'images', 'describe'],
            ['container', 'images', 'list'],
            ['container', 'images', 'list-tags'],
            ['container', 'images', 'untag'],
            ['container', 'node-pools', 'create'],
            ['container', 'node-pools', 'delete'],
            ['container', 'node-pools', 'describe'],
            ['container', 'node-pools', 'list'],
            ['container', 'node-pools', 'rollback'],
            ['container', 'node-pools', 'update'],
            ['container', 'operations', 'describe'],
            ['container', 'operations', 'list'],
            ['container', 'operations', 'wait'],
            ['dataflow', 'jobs', 'cancel'],
            ['dataflow', 'jobs', 'describe'],
            ['dataflow', 'jobs', 'drain'],
            ['dataflow', 'jobs', 'list'],
            ['dataflow', 'jobs', 'run'],
            ['dataflow', 'jobs', 'show'],
            ['dataproc', 'clusters', 'create'],
            ['dataproc', 'clusters', 'delete'],
            ['dataproc', 'clusters', 'describe'],
            ['dataproc', 'clusters', 'diagnose'],
            ['dataproc', 'clusters', 'get-iam-policy'],
            ['dataproc', 'clusters', 'list'],
            ['dataproc', 'clusters', 'set-iam-policy'],
            ['dataproc', 'clusters', 'update'],
            ['dataproc', 'jobs', 'delete'],
            ['dataproc', 'jobs', 'describe'],
            ['dataproc', 'jobs', 'get-iam-policy'],
            ['dataproc', 'jobs', 'kill'],
            ['dataproc', 'jobs', 'list'],
            ['dataproc', 'jobs', 'set-iam-policy'],
            ['dataproc', 'jobs', 'submit', 'hadoop'],
            ['dataproc', 'jobs', 'submit', 'hive'],
            ['dataproc', 'jobs', 'submit', 'pig'],
            ['dataproc', 'jobs', 'submit', 'pyspark'],
            ['dataproc', 'jobs', 'submit', 'spark'],
            ['dataproc', 'jobs', 'submit', 'spark-sql'],
            ['dataproc', 'jobs', 'update'],
            ['dataproc', 'jobs', 'wait'],
            ['dataproc', 'operations', 'cancel'],
            ['dataproc', 'operations', 'delete'],
            ['dataproc', 'operations', 'describe'],
            ['dataproc', 'operations', 'get-iam-policy'],
            ['dataproc', 'operations', 'list'],
            ['dataproc', 'operations', 'set-iam-policy'],
            ['dataproc', 'workflow-templates', 'add-job', 'hadoop'],
            ['dataproc', 'workflow-templates', 'add-job', 'hive'],
            ['dataproc', 'workflow-templates', 'add-job', 'pig'],
            ['dataproc', 'workflow-templates', 'add-job', 'pyspark'],
            ['dataproc', 'workflow-templates', 'add-job', 'spark'],
            ['dataproc', 'workflow-templates', 'add-job', 'spark-sql'],
            ['dataproc', 'workflow-templates', 'create'],
            ['dataproc', 'workflow-templates', 'delete'],
            ['dataproc', 'workflow-templates', 'describe'],
            ['dataproc', 'workflow-templates', 'export'],
            ['dataproc', 'workflow-templates', 'get-iam-policy'],
            ['dataproc', 'workflow-templates', 'import'],
            ['dataproc', 'workflow-templates', 'instantiate'],
            ['dataproc', 'workflow-templates', 'instantiate-from-file'],
            ['dataproc', 'workflow-templates', 'list'],
            ['dataproc', 'workflow-templates', 'remove-job'],
            ['dataproc', 'workflow-templates', 'set-cluster-selector'],
            ['dataproc', 'workflow-templates', 'set-iam-policy'],
            ['dataproc', 'workflow-templates', 'set-managed-cluster'],
            ['datastore', 'cleanup-indexes'],
            ['datastore', 'create-indexes'],
            ['datastore', 'export'],
            ['datastore', 'import'],
            ['datastore', 'indexes', 'cleanup'],
            ['datastore', 'indexes', 'create'],
            ['datastore', 'indexes', 'describe'],
            ['datastore', 'indexes', 'list'],
            ['datastore', 'operations', 'cancel'],
            ['datastore', 'operations', 'delete'],
            ['datastore', 'operations', 'describe'],
            ['datastore', 'operations', 'list'],
            ['debug', 'logpoints', 'create'],
            ['debug', 'logpoints', 'delete'],
            ['debug', 'logpoints', 'list'],
            ['debug', 'snapshots', 'create'],
            ['debug', 'snapshots', 'delete'],
            ['debug', 'snapshots', 'describe'],
            ['debug', 'snapshots', 'list'],
            ['debug', 'snapshots', 'wait'],
            ['debug', 'source', 'gen-repo-info-file'],
            ['debug', 'targets', 'list'],
            ['deployment-manager', 'deployments', 'cancel-preview'],
            ['deployment-manager', 'deployments', 'create'],
            ['deployment-manager', 'deployments', 'delete'],
            ['deployment-manager', 'deployments', 'describe'],
            ['deployment-manager', 'deployments', 'list'],
            ['deployment-manager', 'deployments', 'stop'],
            ['deployment-manager', 'deployments', 'update'],
            ['deployment-manager', 'manifests', 'describe'],
            ['deployment-manager', 'manifests', 'list'],
            ['deployment-manager', 'operations', 'describe'],
            ['deployment-manager', 'operations', 'list'],
            ['deployment-manager', 'operations', 'wait'],
            ['deployment-manager', 'resources', 'describe'],
            ['deployment-manager', 'resources', 'list'],
            ['deployment-manager', 'types', 'list'],
            ['dns', 'dns-keys', 'describe'],
            ['dns', 'dns-keys', 'list'],
            ['dns', 'managed-zones', 'create'],
            ['dns', 'managed-zones', 'delete'],
            ['dns', 'managed-zones', 'describe'],
            ['dns', 'managed-zones', 'list'],
            ['dns', 'managed-zones', 'update'],
            ['dns', 'operations', 'describe'],
            ['dns', 'operations', 'list'],
            ['dns', 'project-info', 'describe'],
            ['dns', 'record-sets', 'changes', 'describe'],
            ['dns', 'record-sets', 'changes', 'list'],
            ['dns', 'record-sets', 'export'],
            ['dns', 'record-sets', 'import'],
            ['dns', 'record-sets', 'list'],
            ['dns', 'record-sets', 'transaction', 'abort'],
            ['dns', 'record-sets', 'transaction', 'add'],
            ['dns', 'record-sets', 'transaction', 'describe'],
            ['dns', 'record-sets', 'transaction', 'execute'],
            ['dns', 'record-sets', 'transaction', 'remove'],
            ['dns', 'record-sets', 'transaction', 'start'],
            ['docker'],
            ['domains', 'list-user-verified'],
            ['domains', 'verify'],
            ['endpoints', 'configs', 'describe'],
            ['endpoints', 'configs', 'list'],
            ['endpoints', 'operations', 'describe'],
            ['endpoints', 'operations', 'list'],
            ['endpoints', 'operations', 'wait'],
            ['endpoints', 'services', 'add-iam-policy-binding'],
            ['endpoints', 'services', 'check-iam-policy'],
            ['endpoints', 'services', 'delete'],
            ['endpoints', 'services', 'deploy'],
            ['endpoints', 'services', 'describe'],
            ['endpoints', 'services', 'get-iam-policy'],
            ['endpoints', 'services', 'list'],
            ['endpoints', 'services', 'remove-iam-policy-binding'],
            ['endpoints', 'services', 'undelete'],
            ['feedback'],
            ['firebase', 'test', 'android', 'locales', 'describe'],
            ['firebase', 'test', 'android', 'locales', 'list'],
            ['firebase', 'test', 'android', 'models', 'describe'],
            ['firebase', 'test', 'android', 'models', 'list'],
            ['firebase', 'test', 'android', 'run'],
            ['firebase', 'test', 'android', 'versions', 'describe'],
            ['firebase', 'test', 'android', 'versions', 'list'],
            ['firebase', 'test', 'ios', 'locales', 'describe'],
            ['firebase', 'test', 'ios', 'locales', 'list'],
            ['firebase', 'test', 'ios', 'models', 'describe'],
            ['firebase', 'test', 'ios', 'models', 'list'],
            ['firebase', 'test', 'ios', 'run'],
            ['firebase', 'test', 'ios', 'versions', 'describe'],
            ['firebase', 'test', 'ios', 'versions', 'list'],
            ['firebase', 'test', 'network-profiles', 'describe'],
            ['firebase', 'test', 'network-profiles', 'list'],
            ['functions', 'call'],
            ['functions', 'delete'],
            ['functions', 'deploy'],
            ['functions', 'describe'],
            ['functions', 'event-types', 'list'],
            ['functions', 'list'],
            ['functions', 'logs', 'read'],
            ['functions', 'regions', 'list'],
            ['help'],
            ['iam', 'list-grantable-roles'],
            ['iam', 'list-testable-permissions'],
            ['iam', 'roles', 'copy'],
            ['iam', 'roles', 'create'],
            ['iam', 'roles', 'delete'],
            ['iam', 'roles', 'describe'],
            ['iam', 'roles', 'list'],
            ['iam', 'roles', 'undelete'],
            ['iam', 'roles', 'update'],
            ['iam', 'service-accounts', 'add-iam-policy-binding'],
            ['iam', 'service-accounts', 'create'],
            ['iam', 'service-accounts', 'delete'],
            ['iam', 'service-accounts', 'describe'],
            ['iam', 'service-accounts', 'get-iam-policy'],
            ['iam', 'service-accounts', 'keys', 'create'],
            ['iam', 'service-accounts', 'keys', 'delete'],
            ['iam', 'service-accounts', 'keys', 'list'],
            ['iam', 'service-accounts', 'list'],
            ['iam', 'service-accounts', 'remove-iam-policy-binding'],
            ['iam', 'service-accounts', 'set-iam-policy'],
            ['iam', 'service-accounts', 'sign-blob'],
            ['iam', 'service-accounts', 'update'],
            ['info'],
            ['init'],
            ['iot', 'devices', 'configs', 'describe'],
            ['iot', 'devices', 'configs', 'get-value'],
            ['iot', 'devices', 'configs', 'list'],
            ['iot', 'devices', 'configs', 'update'],
            ['iot', 'devices', 'create'],
            ['iot', 'devices', 'credentials', 'clear'],
            ['iot', 'devices', 'credentials', 'create'],
            ['iot', 'devices', 'credentials', 'delete'],
            ['iot', 'devices', 'credentials', 'describe'],
            ['iot', 'devices', 'credentials', 'list'],
            ['iot', 'devices', 'credentials', 'update'],
            ['iot', 'devices', 'delete'],
            ['iot', 'devices', 'describe'],
            ['iot', 'devices', 'list'],
            ['iot', 'devices', 'states', 'list'],
            ['iot', 'devices', 'update'],
            ['iot', 'registries', 'create'],
            ['iot', 'registries', 'credentials', 'clear'],
            ['iot', 'registries', 'credentials', 'create'],
            ['iot', 'registries', 'credentials', 'delete'],
            ['iot', 'registries', 'credentials', 'describe'],
            ['iot', 'registries', 'credentials', 'list'],
            ['iot', 'registries', 'delete'],
            ['iot', 'registries', 'describe'],
            ['iot', 'registries', 'get-iam-policy'],
            ['iot', 'registries', 'list'],
            ['iot', 'registries', 'set-iam-policy'],
            ['iot', 'registries', 'update'],
            ['kms', 'decrypt'],
            ['kms', 'encrypt'],
            ['kms', 'keyrings', 'add-iam-policy-binding'],
            ['kms', 'keyrings', 'create'],
            ['kms', 'keyrings', 'describe'],
            ['kms', 'keyrings', 'get-iam-policy'],
            ['kms', 'keyrings', 'list'],
            ['kms', 'keyrings', 'remove-iam-policy-binding'],
            ['kms', 'keyrings', 'set-iam-policy'],
            ['kms', 'keys', 'add-iam-policy-binding'],
            ['kms', 'keys', 'create'],
            ['kms', 'keys', 'describe'],
            ['kms', 'keys', 'get-iam-policy'],
            ['kms', 'keys', 'list'],
            ['kms', 'keys', 'remove-iam-policy-binding'],
            ['kms', 'keys', 'remove-rotation-schedule'],
            ['kms', 'keys', 'set-iam-policy'],
            ['kms', 'keys', 'set-primary-version'],
            ['kms', 'keys', 'set-rotation-schedule'],
            ['kms', 'keys', 'update'],
            ['kms', 'keys', 'versions', 'create'],
            ['kms', 'keys', 'versions', 'describe'],
            ['kms', 'keys', 'versions', 'destroy'],
            ['kms', 'keys', 'versions', 'disable'],
            ['kms', 'keys', 'versions', 'enable'],
            ['kms', 'keys', 'versions', 'list'],
            ['kms', 'keys', 'versions', 'restore'],
            ['kms', 'locations', 'list'],
            ['logging', 'logs', 'delete'],
            ['logging', 'logs', 'list'],
            ['logging', 'metrics', 'create'],
            ['logging', 'metrics', 'delete'],
            ['logging', 'metrics', 'describe'],
            ['logging', 'metrics', 'list'],
            ['logging', 'metrics', 'update'],
            ['logging', 'read'],
            ['logging', 'resource-descriptors', 'list'],
            ['logging', 'sinks', 'create'],
            ['logging', 'sinks', 'delete'],
            ['logging', 'sinks', 'describe'],
            ['logging', 'sinks', 'list'],
            ['logging', 'sinks', 'update'],
            ['logging', 'write'],
            ['ml', 'language', 'analyze-entities'],
            ['ml', 'language', 'analyze-entity-sentiment'],
            ['ml', 'language', 'analyze-sentiment'],
            ['ml', 'language', 'analyze-syntax'],
            ['ml', 'language', 'classify-text'],
            ['ml', 'speech', 'operations', 'describe'],
            ['ml', 'speech', 'operations', 'wait'],
            ['ml', 'speech', 'recognize'],
            ['ml', 'speech', 'recognize-long-running'],
            ['ml', 'video', 'detect-explicit-content'],
            ['ml', 'video', 'detect-labels'],
            ['ml', 'video', 'detect-shot-changes'],
            ['ml', 'video', 'operations', 'describe'],
            ['ml', 'video', 'operations', 'wait'],
            ['ml', 'vision', 'detect-document'],
            ['ml', 'vision', 'detect-faces'],
            ['ml', 'vision', 'detect-image-properties'],
            ['ml', 'vision', 'detect-labels'],
            ['ml', 'vision', 'detect-landmarks'],
            ['ml', 'vision', 'detect-logos'],
            ['ml', 'vision', 'detect-safe-search'],
            ['ml', 'vision', 'detect-text'],
            ['ml', 'vision', 'detect-web'],
            ['ml', 'vision', 'suggest-crop'],
            ['ml-engine', 'jobs', 'cancel'],
            ['ml-engine', 'jobs', 'describe'],
            ['ml-engine', 'jobs', 'list'],
            ['ml-engine', 'jobs', 'stream-logs'],
            ['ml-engine', 'jobs', 'submit', 'prediction'],
            ['ml-engine', 'jobs', 'submit', 'training'],
            ['ml-engine', 'jobs', 'update'],
            ['ml-engine', 'local', 'predict'],
            ['ml-engine', 'local', 'train'],
            ['ml-engine', 'models', 'add-iam-policy-binding'],
            ['ml-engine', 'models', 'create'],
            ['ml-engine', 'models', 'delete'],
            ['ml-engine', 'models', 'describe'],
            ['ml-engine', 'models', 'get-iam-policy'],
            ['ml-engine', 'models', 'list'],
            ['ml-engine', 'models', 'remove-iam-policy-binding'],
            ['ml-engine', 'models', 'set-iam-policy'],
            ['ml-engine', 'models', 'update'],
            ['ml-engine', 'operations', 'cancel'],
            ['ml-engine', 'operations', 'delete'],
            ['ml-engine', 'operations', 'describe'],
            ['ml-engine', 'operations', 'list'],
            ['ml-engine', 'operations', 'wait'],
            ['ml-engine', 'predict'],
            ['ml-engine', 'versions', 'create'],
            ['ml-engine', 'versions', 'delete'],
            ['ml-engine', 'versions', 'describe'],
            ['ml-engine', 'versions', 'list'],
            ['ml-engine', 'versions', 'set-default'],
            ['ml-engine', 'versions', 'update'],
            ['organizations', 'add-iam-policy-binding'],
            ['organizations', 'describe'],
            ['organizations', 'get-iam-policy'],
            ['organizations', 'list'],
            ['organizations', 'remove-iam-policy-binding'],
            ['organizations', 'set-iam-policy'],
            ['projects', 'add-iam-policy-binding'],
            ['projects', 'create'],
            ['projects', 'delete'],
            ['projects', 'describe'],
            ['projects', 'get-iam-policy'],
            ['projects', 'list'],
            ['projects', 'remove-iam-policy-binding'],
            ['projects', 'set-iam-policy'],
            ['projects', 'undelete'],
            ['projects', 'update'],
            ['pubsub', 'subscriptions', 'ack'],
            ['pubsub', 'subscriptions', 'create'],
            ['pubsub', 'subscriptions', 'delete'],
            ['pubsub', 'subscriptions', 'describe'],
            ['pubsub', 'subscriptions', 'list'],
            ['pubsub', 'subscriptions', 'modify-message-ack-deadline'],
            ['pubsub', 'subscriptions', 'modify-push-config'],
            ['pubsub', 'subscriptions', 'pull'],
            ['pubsub', 'topics', 'create'],
            ['pubsub', 'topics', 'delete'],
            ['pubsub', 'topics', 'describe'],
            ['pubsub', 'topics', 'list'],
            ['pubsub', 'topics', 'list-subscriptions'],
            ['pubsub', 'topics', 'publish'],
            ['redis', 'instances', 'create'],
            ['redis', 'instances', 'delete'],
            ['redis', 'instances', 'describe'],
            ['redis', 'instances', 'list'],
            ['redis', 'instances', 'update'],
            ['redis', 'operations', 'describe'],
            ['redis', 'operations', 'list'],
            ['redis', 'regions', 'describe'],
            ['redis', 'regions', 'list'],
            ['redis', 'zones', 'list'],
            ['services', 'disable'],
            ['services', 'enable'],
            ['services', 'list'],
            ['services', 'operations', 'describe'],
            ['services', 'operations', 'list'],
            ['services', 'operations', 'wait'],
            ['source', 'repos', 'clone'],
            ['source', 'repos', 'create'],
            ['source', 'repos', 'delete'],
            ['source', 'repos', 'describe'],
            ['source', 'repos', 'get-iam-policy'],
            ['source', 'repos', 'list'],
            ['source', 'repos', 'set-iam-policy'],
            ['spanner', 'databases', 'add-iam-policy-binding'],
            ['spanner', 'databases', 'create'],
            ['spanner', 'databases', 'ddl', 'describe'],
            ['spanner', 'databases', 'ddl', 'update'],
            ['spanner', 'databases', 'delete'],
            ['spanner', 'databases', 'describe'],
            ['spanner', 'databases', 'execute-sql'],
            ['spanner', 'databases', 'get-iam-policy'],
            ['spanner', 'databases', 'list'],
            ['spanner', 'databases', 'remove-iam-policy-binding'],
            ['spanner', 'databases', 'sessions', 'delete'],
            ['spanner', 'databases', 'sessions', 'list'],
            ['spanner', 'databases', 'set-iam-policy'],
            ['spanner', 'instance-configs', 'describe'],
            ['spanner', 'instance-configs', 'list'],
            ['spanner', 'instances', 'add-iam-policy-binding'],
            ['spanner', 'instances', 'create'],
            ['spanner', 'instances', 'delete'],
            ['spanner', 'instances', 'describe'],
            ['spanner', 'instances', 'get-iam-policy'],
            ['spanner', 'instances', 'list'],
            ['spanner', 'instances', 'remove-iam-policy-binding'],
            ['spanner', 'instances', 'set-iam-policy'],
            ['spanner', 'instances', 'update'],
            ['spanner', 'operations', 'cancel'],
            ['spanner', 'operations', 'describe'],
            ['spanner', 'operations', 'list'],
            ['sql', 'backups', 'create'],
            ['sql', 'backups', 'delete'],
            ['sql', 'backups', 'describe'],
            ['sql', 'backups', 'list'],
            ['sql', 'backups', 'restore'],
            ['sql', 'connect'],
            ['sql', 'databases', 'create'],
            ['sql', 'databases', 'delete'],
            ['sql', 'databases', 'describe'],
            ['sql', 'databases', 'list'],
            ['sql', 'databases', 'patch'],
            ['sql', 'export', 'csv'],
            ['sql', 'export', 'sql'],
            ['sql', 'flags', 'list'],
            ['sql', 'import', 'csv'],
            ['sql', 'import', 'sql'],
            ['sql', 'instances', 'clone'],
            ['sql', 'instances', 'create'],
            ['sql', 'instances', 'delete'],
            ['sql', 'instances', 'describe'],
            ['sql', 'instances', 'export'],
            ['sql', 'instances', 'failover'],
            ['sql', 'instances', 'import'],
            ['sql', 'instances', 'list'],
            ['sql', 'instances', 'patch'],
            ['sql', 'instances', 'promote-replica'],
            ['sql', 'instances', 'reset-ssl-config'],
            ['sql', 'instances', 'restart'],
            ['sql', 'instances', 'restore-backup'],
            ['sql', 'operations', 'describe'],
            ['sql', 'operations', 'list'],
            ['sql', 'operations', 'wait'],
            ['sql', 'ssl', 'client-certs', 'create'],
            ['sql', 'ssl', 'client-certs', 'delete'],
            ['sql', 'ssl', 'client-certs', 'describe'],
            ['sql', 'ssl', 'client-certs', 'list'],
            ['sql', 'ssl-certs', 'create'],
            ['sql', 'ssl-certs', 'delete'],
            ['sql', 'ssl-certs', 'describe'],
            ['sql', 'ssl-certs', 'list'],
            ['sql', 'tiers', 'list'],
            ['sql', 'users', 'create'],
            ['sql', 'users', 'delete'],
            ['sql', 'users', 'list'],
            ['sql', 'users', 'set-password'],
            ['topic', 'arg-files'],
            ['topic', 'cli-trees'],
            ['topic', 'command-conventions'],
            ['topic', 'configurations'],
            ['topic', 'datetimes'],
            ['topic', 'escaping'],
            ['topic', 'filters'],
            ['topic', 'flags-file'],
            ['topic', 'formats'],
            ['topic', 'gcloudignore'],
            ['topic', 'offline-help'],
            ['topic', 'projections'],
            ['topic', 'resource-keys'],
            ['topic', 'startup'],
            ['version'],
        ],
        sorted(suggest_commands._GetCanonicalCommands(self.root)))

  def testGetScoredCommandsContaining(self):
    self.assertEqual(
        [
            (['app', 'logs', 'read'], 145),
            (['app', 'logs', 'tail'], 145),
            (['logging', 'logs', 'delete'], 129),
            (['logging', 'logs', 'list'], 129),
            (['app', 'browse'], 91),
            (['app', 'create'], 91),
            (['app', 'deploy'], 91),
            (['app', 'describe'], 91),
            (['app', 'open-console'], 91),
            (['app', 'update'], 91),
            (['auth', 'application-default', 'login'], 87),
            (['logging', 'read'], 85),
            (['logging', 'write'], 85),
            (['app', 'domain-mappings', 'create'], 81),
            (['app', 'domain-mappings', 'delete'], 81),
            (['app', 'domain-mappings', 'describe'], 81),
            (['app', 'domain-mappings', 'list'], 81),
            (['app', 'domain-mappings', 'update'], 81),
            (['app', 'firewall-rules', 'create'], 81),
            (['app', 'firewall-rules', 'delete'], 81),
            (['app', 'firewall-rules', 'describe'], 81),
            (['app', 'firewall-rules', 'list'], 81),
            (['app', 'firewall-rules', 'test-ip'], 81),
            (['app', 'firewall-rules', 'update'], 81),
            (['app', 'instances', 'delete'], 81),
            (['app', 'instances', 'describe'], 81),
            (['app', 'instances', 'disable-debug'], 81),
            (['app', 'instances', 'enable-debug'], 81),
            (['app', 'instances', 'list'], 81),
            (['app', 'instances', 'scp'], 81),
            (['app', 'instances', 'ssh'], 81),
            (['app', 'operations', 'describe'], 81),
            (['app', 'operations', 'list'], 81),
            (['app', 'operations', 'wait'], 81),
            (['app', 'regions', 'list'], 81),
            (['app', 'services', 'browse'], 81),
            (['app', 'services', 'delete'], 81),
            (['app', 'services', 'describe'], 81),
            (['app', 'services', 'list'], 81),
            (['app', 'services', 'set-traffic'], 81),
            (['app', 'ssl-certificates', 'create'], 81),
            (['app', 'ssl-certificates', 'delete'], 81),
            (['app', 'ssl-certificates', 'describe'], 81),
            (['app', 'ssl-certificates', 'list'], 81),
            (['app', 'ssl-certificates', 'update'], 81),
            (['app', 'versions', 'browse'], 81),
            (['app', 'versions', 'delete'], 81),
            (['app', 'versions', 'describe'], 81),
            (['app', 'versions', 'list'], 81),
            (['app', 'versions', 'migrate'], 81),
            (['app', 'versions', 'start'], 81),
            (['app', 'versions', 'stop'], 81),
            (['logging', 'metrics', 'create'], 75),
            (['logging', 'metrics', 'delete'], 75),
            (['logging', 'metrics', 'describe'], 75),
            (['logging', 'metrics', 'list'], 75),
            (['logging', 'metrics', 'update'], 75),
            (['logging', 'resource-descriptors', 'list'], 75),
            (['logging', 'sinks', 'create'], 75),
            (['logging', 'sinks', 'delete'], 75),
            (['logging', 'sinks', 'describe'], 75),
            (['logging', 'sinks', 'list'], 75),
            (['logging', 'sinks', 'update'], 75),
            (['functions', 'logs', 'read'], 54),
            (['builds', 'log'], 51),
            (['auth', 'application-default', 'print-access-token'], 50),
            (['auth', 'application-default', 'revoke'], 50),
            (['compute', 'os-login', 'describe-profile'], 50),
            (['compute', 'os-login', 'remove-profile'], 50),
            (['debug', 'logpoints', 'create'], 50),
            (['debug', 'logpoints', 'delete'], 50),
            (['debug', 'logpoints', 'list'], 50),
            (['auth', 'login'], 47),
            (['compute', 'os-login', 'ssh-keys', 'add'], 40),
            (['compute', 'os-login', 'ssh-keys', 'describe'], 40),
            (['compute', 'os-login', 'ssh-keys', 'list'], 40),
            (['compute', 'os-login', 'ssh-keys', 'remove'], 40),
            (['compute', 'os-login', 'ssh-keys', 'update'], 40),
            (['ml', 'vision', 'detect-logos'], 25),
            (['ml-engine', 'jobs', 'stream-logs'], 25)
        ],
        suggest_commands._GetScoredCommandsContaining(['log', 'app']))

  @parameterized.named_parameters(
      T(
          ['log', 'app'],
          [
              'gcloud app logs read',
              'gcloud app logs tail',
              'gcloud logging logs delete',
              'gcloud logging logs list',
          ]
      ),
      T(
          ['update'],
          [
              'gcloud app update',
              'gcloud components update',
              'gcloud projects update',
              'gcloud compute health-checks update http',
              'gcloud compute health-checks update https',
              'gcloud compute health-checks update ssl',
              'gcloud compute health-checks update tcp'
          ]
      ),
      T(
          ['get', 'image'],
          [
              'gcloud compute images describe',
              'gcloud container images describe',
              'gcloud compute images describe-from-family',
          ]
      ),
      T(
          ['instances'],
          [
              'gcloud app instances',
              'gcloud bigtable instances',
              'gcloud compute instance-groups',
              'gcloud compute instance-templates',
              'gcloud compute instances',
              'gcloud compute target-instances',
              'gcloud redis instances',
              'gcloud spanner instance-configs',
              'gcloud spanner instances',
              'gcloud sql instances'
          ]
      ),
      T(
          ['list', 'instance'],
          [
              'gcloud compute instance-groups list-instances',
              'gcloud app instances list',
              'gcloud bigtable instances list',
              'gcloud compute instances list',
              'gcloud redis instances list',
              'gcloud spanner instances list',
              'gcloud sql instances list',
              'gcloud compute instance-groups list',
              'gcloud compute instance-templates list',
              'gcloud compute target-instances list'
          ]
      ),
      T(
          ['get', 'config'],
          [
              'gcloud config configurations describe',
              'gcloud config get-value',
              'gcloud config configurations activate',
              'gcloud config configurations create',
              'gcloud config configurations delete',
              'gcloud config configurations list'
          ]
      ),
      T(
          ['auth', 'revoke', 'login'],
          [
              'gcloud auth login',
              'gcloud auth revoke',
              'gcloud auth application-default login',
              'gcloud auth application-default revoke'
          ]
      ),
      T(
          ['component', 'ad', 'repository'],
          [
              'gcloud components repositories add',
              'gcloud components install',
              'gcloud components list',
              'gcloud components reinstall',
              'gcloud components remove',
              'gcloud components restore',
              'gcloud components update',
              'gcloud components repositories list',
              'gcloud components repositories remove'
          ]
      ),
      T(
          ['submit'],
          [
              'gcloud builds submit',
              'gcloud dataproc jobs submit hadoop',
              'gcloud dataproc jobs submit hive',
              'gcloud dataproc jobs submit pig',
              'gcloud dataproc jobs submit pyspark',
              'gcloud dataproc jobs submit spark',
              'gcloud dataproc jobs submit spark-sql',
              'gcloud ml-engine jobs submit prediction',
              'gcloud ml-engine jobs submit training'
          ]
      ),
      T(
          ['copy-files'],
          [
              'gcloud compute copy-files',
              'gcloud compute scp'
          ]
      ),
      T(
          ['nonexistent'], []
      )
  )
  def testGetCommandSuggestions(self, command, suggestions):
    self.assertEqual(suggestions,
                     suggest_commands.GetCommandSuggestions(command))

  def testGetSurfaceHistoryFrequencies(self):
    test_logs_dir = self.Resource('tests', 'unit', 'calliope', 'testdata',
                                  'logs')
    self.assertEqual(
        {
            'compute.instances': 0.6666666666666666,
            'components': 0.3333333333333333
        },
        suggest_commands._GetSurfaceHistoryFrequencies(test_logs_dir))

  def testGetSurfaceHistoryFrequenciesEmpty(self):
    self.assertEqual({}, suggest_commands._GetSurfaceHistoryFrequencies(None))

  @mock.patch('googlecloudsdk.calliope.suggest_commands.'
              '_GetSurfaceHistoryFrequencies',
              return_value={
                  'logging': 0.6,
                  'compute.instances': 0.4
              })
  def testGetScoredCommandsContainingWithLogs(
      self,
      mock_get_surface_history_frequencies):
    self.assertEqual(
        [
            (['app', 'logs', 'read'], 145),
            (['app', 'logs', 'tail'], 145),
            (['logging', 'read'], 145),
            (['logging', 'write'], 145),
            (['logging', 'logs', 'delete'], 129),
            (['logging', 'logs', 'list'], 129),
            (['app', 'browse'], 91),
            (['app', 'create'], 91),
            (['app', 'deploy'], 91),
            (['app', 'describe'], 91),
            (['app', 'open-console'], 91),
            (['app', 'update'], 91),
            (['auth', 'application-default', 'login'], 87),
            (['app', 'domain-mappings', 'create'], 81),
            (['app', 'domain-mappings', 'delete'], 81),
            (['app', 'domain-mappings', 'describe'], 81),
            (['app', 'domain-mappings', 'list'], 81),
            (['app', 'domain-mappings', 'update'], 81),
            (['app', 'firewall-rules', 'create'], 81),
            (['app', 'firewall-rules', 'delete'], 81),
            (['app', 'firewall-rules', 'describe'], 81),
            (['app', 'firewall-rules', 'list'], 81),
            (['app', 'firewall-rules', 'test-ip'], 81),
            (['app', 'firewall-rules', 'update'], 81),
            (['app', 'instances', 'delete'], 81),
            (['app', 'instances', 'describe'], 81),
            (['app', 'instances', 'disable-debug'], 81),
            (['app', 'instances', 'enable-debug'], 81),
            (['app', 'instances', 'list'], 81),
            (['app', 'instances', 'scp'], 81),
            (['app', 'instances', 'ssh'], 81),
            (['app', 'operations', 'describe'], 81),
            (['app', 'operations', 'list'], 81),
            (['app', 'operations', 'wait'], 81),
            (['app', 'regions', 'list'], 81),
            (['app', 'services', 'browse'], 81),
            (['app', 'services', 'delete'], 81),
            (['app', 'services', 'describe'], 81),
            (['app', 'services', 'list'], 81),
            (['app', 'services', 'set-traffic'], 81),
            (['app', 'ssl-certificates', 'create'], 81),
            (['app', 'ssl-certificates', 'delete'], 81),
            (['app', 'ssl-certificates', 'describe'], 81),
            (['app', 'ssl-certificates', 'list'], 81),
            (['app', 'ssl-certificates', 'update'], 81),
            (['app', 'versions', 'browse'], 81),
            (['app', 'versions', 'delete'], 81),
            (['app', 'versions', 'describe'], 81),
            (['app', 'versions', 'list'], 81),
            (['app', 'versions', 'migrate'], 81),
            (['app', 'versions', 'start'], 81),
            (['app', 'versions', 'stop'], 81),
            (['logging', 'metrics', 'create'], 75),
            (['logging', 'metrics', 'delete'], 75),
            (['logging', 'metrics', 'describe'], 75),
            (['logging', 'metrics', 'list'], 75),
            (['logging', 'metrics', 'update'], 75),
            (['logging', 'resource-descriptors', 'list'], 75),
            (['logging', 'sinks', 'create'], 75),
            (['logging', 'sinks', 'delete'], 75),
            (['logging', 'sinks', 'describe'], 75),
            (['logging', 'sinks', 'list'], 75),
            (['logging', 'sinks', 'update'], 75),
            (['functions', 'logs', 'read'], 54),
            (['builds', 'log'], 51),
            (['auth', 'application-default', 'print-access-token'], 50),
            (['auth', 'application-default', 'revoke'], 50),
            (['compute', 'os-login', 'describe-profile'], 50),
            (['compute', 'os-login', 'remove-profile'], 50),
            (['debug', 'logpoints', 'create'], 50),
            (['debug', 'logpoints', 'delete'], 50),
            (['debug', 'logpoints', 'list'], 50),
            (['auth', 'login'], 47),
            (['compute', 'os-login', 'ssh-keys', 'add'], 40),
            (['compute', 'os-login', 'ssh-keys', 'describe'], 40),
            (['compute', 'os-login', 'ssh-keys', 'list'], 40),
            (['compute', 'os-login', 'ssh-keys', 'remove'], 40),
            (['compute', 'os-login', 'ssh-keys', 'update'], 40),
            (['ml', 'vision', 'detect-logos'], 25),
            (['ml-engine', 'jobs', 'stream-logs'], 25)
        ],
        suggest_commands._GetScoredCommandsContaining(['log', 'app']))
    self.assertEqual(1, mock_get_surface_history_frequencies.call_count)

  @mock.patch('googlecloudsdk.calliope.suggest_commands.'
              '_GetSurfaceHistoryFrequencies',
              return_value={
                  'dataproc.jobs.submit': 0.2,
                  'ml-engine.jobs.submit': 0.3,
                  'compute.instances': 0.5
              })
  def testGetCommandSuggestionsWithLogs(self,
                                        mock_get_surface_history_frequencies):
    self.assertEqual(
        [
            'gcloud ml-engine jobs submit prediction',
            'gcloud ml-engine jobs submit training',
            'gcloud dataproc jobs submit hadoop',
            'gcloud dataproc jobs submit hive',
            'gcloud dataproc jobs submit pig',
            'gcloud dataproc jobs submit pyspark',
            'gcloud dataproc jobs submit spark',
            'gcloud dataproc jobs submit spark-sql',
            'gcloud builds submit'
        ],
        suggest_commands.GetCommandSuggestions(['submit']))
    self.assertEqual(1, mock_get_surface_history_frequencies.call_count)

if __name__ == '__main__':
  calliope_test_base.main()
