
.TH "GCLOUD_MARKDOWN_MARKDOWN\-COMMAND" 1



.SH "NAME"
.HP
gcloud markdown markdown\-command \- markdown command docstring index



.SH "SYNOPSIS"
.HP
\f5gcloud markdown markdown\-command\fR [[\fIUSER\fR@]\fIINSTANCE\fR:]\fISRC\fR [[[\fIUSER\fR@]\fIINSTANCE\fR:]\fISRC\fR\ ...] [[\fIUSER\fR@]\fIINSTANCE\fR:]\fIDEST\fR [\fIUSER\fR@]\fIINSTANCE\fR [\fB\-\-dict\-flag\fR\ [\fIITEM\fR,...];\ default="aaa=1,bbb=22,ccc=aha"] [\fB\-\-false\-flag\fR] [\fB\-\-list\-flag\fR\ [\fIITEM\fR,...];\ default="aaa,bbb,ccc"] [\fB\-\-optional\-flag\fR\ \fIOPTIONAL_FLAG\fR] [\fB\-\-question\-flag\fR\ \fIQUESTION_FLAG\fR] [\fB\-\-root\-flag\fR\ \fIROOT_PATH\fR;\ default="/"] [\fB\-\-true\-flag\fR] [\fB\-\-value\-flag\fR\ \fIVALUE_FLAG\fR;\ default="VALUE"] [\fB\-\-[no\-]action\-required\fR] [\fIGCLOUD\-WIDE\-FLAG\ ...\fR] [\-\-\ \fIIMPLEMENTATION\-ARGS\fR\ ...]


.SH "DESCRIPTION"

Markdown command docstring description. This is a markdown test. If you change
the docstrings or help strings or argparse flags or argparse positionals in this
file you should get test regressions. Use gcloud markdown foo. Don't forget the
\f5\fIMAGIC_SAUCE@FOO_BAR.COM\fR\fR arg.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
[[\fIUSER\fR@]\fIINSTANCE\fR:]\fISRC\fR [[[\fIUSER\fR@]\fIINSTANCE\fR:]\fISRC\fR ...]
Specifies a source file.

.TP 2m
[[\fIUSER\fR@]\fIINSTANCE\fR:]\fIDEST\fR
Specifies a destination for the source files.

.TP 2m
[\fIUSER\fR@]\fIINSTANCE\fR
Specifies the instance to SSH into.

\f5\fIUSER\fR\fR specifies the username with which to SSH. If omitted, $USER
from the environment is selected.

.TP 2m
[\-\- \fIIMPLEMENTATION\-ARGS\fR ...]
Flags and positionals passed to the underlying ssh implementation.

The '\-\-' argument must be specified between gcloud specific args on the left
and IMPLEMENTATION\-ARGS on the right. Example:

.RS 2m
$ gcloud markdown markdown\-command example\-instance \e
    \-\-zone us\-central1\-a \-\- \-vvv \-L 80:%INSTANCE%:80
.RE


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-dict\-flag\fR [\fIITEM\fR,...]; default="aaa=1,bbb=22,ccc=aha"
Command star flag help.

.TP 2m
\fB\-\-false\-flag\fR
Command false flag detailed help.

.TP 2m
\fB\-\-list\-flag\fR [\fIITEM\fR,...]; default="aaa,bbb,ccc"
Command star flag help.

.TP 2m
\fB\-\-question\-flag\fR \fIQUESTION_FLAG\fR
Command question flag help.

.TP 2m
\fB\-\-root\-flag\fR \fIROOT_PATH\fR; default="/"
Command value flag help.

.TP 2m
\fB\-\-true\-flag\fR
Command true flag help.

.TP 2m
\fB\-\-value\-flag\fR \fIVALUE_FLAG\fR; default="VALUE"
Command value flag help.

.TP 2m
\fB\-\-[no\-]action\-required\fR
Enables/disables the fake flag. Use \-\-action\-required to enable and
\-\-no\-action\-required to disable.


.RE
.sp

.SH "GROUP FLAGS"

.RS 2m
.TP 2m
\fB\-\-optional\-flag\fR \fIOPTIONAL_FLAG\fR
Optional flag.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To foo the command run:

.RS 2m
$ gcloud markdown markdown\-command list \-\-foo
.RE

To bar the parent command run:

.RS 2m
$ gcloud markdown \-\-bar list
.RE


.SH "NOTES"
A special note.
