
.TH "gcloud RELEASE_NOTES" ""

.SH "Google Cloud SDK \- Release Notes"

Copyright 2013\-2014 Google Inc. All rights reserved.


.SH "0.9.41 (2014/12/17)"

.RS 2m
.IP "\(bu" 2m
Progress Bars.
.IP "\(bu" 2m
Compute Instances start/stop commands.
.RE
.sp


.SH "0.9.35 (2014/11/04)"

.RS 2m
.IP "\(bu" 2m
Added support for Google Container Engine. It is available under the 'gcloud
preview container' command group.
.RE
.sp


.SH "0.9.33 (2014/09/30)"

.RS 2m
.IP "\(bu" 2m
Overhaul of 'gcloud sql'
.RS 2m
.IP "\(em" 2m
Updated the output for all commands.
.IP "\(em" 2m
Updated usage for 'gcloud sql ssl\-certs create'.
.RE
.RE
.sp


.SH "0.9.31 (2014/09/02)"

.RS 2m
.IP "\(bu" 2m
Added support for creating and maintaining Cloud SQL read replica instances.
.RS 2m
.IP "\(em" 2m
Added \fB\-\-master\-instance\-name\fR property that can be set during replica
creation to indicate the replication master for the read replica instance.
.IP "\(em" 2m
Added \fB\-\-enable\-database\-replication\fR,
\fB\-\-no\-enable\-database\-replication\fR flags that can be used to start,
stop replication for the read replica instance.
.IP "\(em" 2m
Added 'promote\-replica' command that promotes a read replica instance into a
stand\-alone Cloud SQL instance.
.RE
.sp
.IP "\(bu" 2m
Added several new features to the compute component:
.RS 2m
.IP "\(em" 2m
Implemented new subcommands for interacting with HTTP load balancing:
.RS 2m
.IP "\(bu" 2m
gcloud compute backend\-services update
.IP "\(bu" 2m
gcloud compute url\-maps add\-host\-rule
.IP "\(bu" 2m
gcloud compute url\-maps add\-path\-matcher
.IP "\(bu" 2m
gcloud compute url\-maps remove\-host\-rule
.IP "\(bu" 2m
gcloud compute url\-maps remove\-path\-matcher
.IP "\(bu" 2m
gcloud compute url\-maps set\-default\-service
.RE
.sp
.IP "\(em" 2m
Added support for automatically generating initial Windows username and password
when creating a virtual machine instance from a Windowsuimage or a disk
initializaed from a Windows image.
.IP "\(em" 2m
Added a new scope alias for Cloud SQL administration: 'sql\-admin'.
.RE
.RE
.sp


.SH "0.9.27 (2014/06/18)"

.RS 2m
.IP "\(bu" 2m
Added \fB\-\-shell\fR mode to all gcloud commands
.RS 2m
.IP "\(em" 2m
Type a partial command followed by \fB\-\-shell\fR to drop into a sub shell at
that point in the command tree.
.IP "\(em" 2m
e.g.: $ gcloud compute \-\-shell gcloud compute $ instances list gcloud compute
$ copy\-files ...
.RE
.sp
.IP "\(bu" 2m
Updated gsutil to 4.3
.IP "\(bu" 2m
Allow installed crcmod to be used by default with gsutil by enabling site
packages
.RE
.sp


.SH "0.9.26 (2014/06/04)"

.RS 2m
.IP "\(bu" 2m
Windows support for SSH and SCP to Compute VMs
.RS 2m
.IP "\(em" 2m
The following will now work natively on Windows without the need for cygwin:
.RS 2m
.IP "\(bu" 2m
gcloud compute ssh
.IP "\(bu" 2m
gcloud compute copy\-files
.IP "\(bu" 2m
gcutil ssh
.IP "\(bu" 2m
gcutil push
.IP "\(bu" 2m
gcutil pull
.RE
.RE
.sp
.IP "\(bu" 2m
Support for Java apps in 'gcloud preview app run'
.IP "\(bu" 2m
Updated gsutil to 4.1
.IP "\(bu" 2m
Updated gcutil to 1.16.0
.IP "\(bu" 2m
Updated all App Engine tools to 1.9.6
.RS 2m
.IP "\(em" 2m
https://code.google.com/p/googleappengine/wiki/SdkReleaseNotes.
.IP "\(em" 2m
https://code.google.com/p/googleappengine/wiki/SdkForJavaReleaseNotes

.RE
.RE
.sp

.SH "NOTES"
A special note.
